### ISSUE TITLE
Connection pool Google Cloud SQL connection loss issue using Cloud Functions for Firebase

### ISSUE THREAD

**Issue by kireerik** [sidorares/node-mysql2#1011]
I am using [connection pools](https://github.com/sidorares/node-mysql2#using-connection-pools) with [Promise wrapper](https://github.com/sidorares/node-mysql2#using-promise-wrapper) in [Cloud Functions for Firebase](https://firebase.google.com/docs/functions) connecting to a [Google Cloud SQL (for MySQL)](https://cloud.google.com/sql/docs/mysql/) instance.

I follow all the [Connecting to Cloud SQL Connection Reuse](https://cloud.google.com/functions/docs/sql#connection_reuse) recommendations:
- > using a globally scoped connection pool
- > not close connections at the end of the function call

I also follow all the [Connecting to Cloud SQL Connection Pools & Connection Loss](https://cloud.google.com/functions/docs/sql#connection_pools_connection_loss) recommendations:
- > use a client library that supports connection pools that automatically reconnect broken client connections
- maximum connections is set to `1`
- By now I am only using `1` connection pool per cloud function.

Sometimes the following error occurs in production:
```
Unhandled rejection
```
```
Error: Connection lost: The server closed the connection.
    at PromisePool.query (/srv/node_modules/mysql2/promise.js:330:22)
.
.
.
    at functions.region.https.onRequest (/srv/index/handleRequest/index.js:10:3)
    at cloudFunction (/srv/node_modules/firebase-functions/lib/providers/https.js:49:9)
    at /worker/worker.js:783:7
    at /worker/worker.js:766:11
    at _combinedTickCallback (internal/process/next_tick.js:132:7)
```

As I read this library should reconnect by it self: https://github.com/sidorares/node-mysql2/issues/572#issuecomment-304774468 https://github.com/sidorares/node-mysql2/issues/836#issuecomment-414281593
Am I correct?

> (Somewhat similar issue: https://github.com/mysqljs/mysql/issues/2151)

Relevant source code:
`mysqlPool.js`:
```JavaScript
const functions = require('firebase-functions')
, mysql = require('mysql2')

, {mysql: {user, password, database}} = functions.config()

, mysqlConfig = {
	user, password, database
	, connectionLimit: 1
	, decimalNumbers: true
}

if (process.env.NODE_ENV == 'production')
	mysqlConfig.socketPath = '/cloudsql/'
		+ '<CLOUD SQL INSTANCE CONNECTION NAME>'

module.exports = mysql.createPool(mysqlConfig).promise()
```

Usage:
```JavaScript
const mysqlPool = require('./mysqlPool')
```

I am using the `mysqlPool.`**`query`** and `mysqlPool.`**`execute`** functions multiple times as I need them.

Versions:
- Node.js: `8.15.0` [runtime](https://cloud.google.com/functions/docs/concepts/nodejs-8-runtime)
- `mysql2`: `1.7.0`
- `firebase-functions`: `3.2.0`

**Comment by kireerik** [comment]
@sidorares What do you think? The connection pool should reconnect on it's own, am I correct?

**Comment by sidorares** [comment]
Didn't have time to look into it yet. Pool doesn't actively reconnect. When you ask new connection from pool, it's reused if there is one idle available, or new connection created if all busy and you are below the limit of active connections (If over the limit you wait until somebody return connection)

When active connection dies for any reason it's just removed from the pool

**Comment by niteshv0909** [comment]
I am also facing same issue with pool. here is my connection.js 

```
const pool = mysql.createPool({
    connectionLimit: 3,
    host: config.database.host,
    user: config.database.user,
    password: config.database.password,
    database: config.database.db,

});
const promisifiedPool = pool.promise();

const executeQuery = async (query) => {
    return new Promise((resolve, reject) => {
        promisifiedPool.query(query)
            .then(([rows, fields]) => {
                return resolve(rows);
            }).catch(reject);
    });
};
```
Following is my stack trace. 
```
{ Error: Connection lost: The server closed the connection.
    at PromisePool.query (/var/www/lbb-product-feeds/node_modules/mysql2/promise.js:330:22)
    at /var/www/lbb-product-feeds/src/core/mysql.js:16:25
    at new Promise (<anonymous>)
    at executeQuery$ (/var/www/lbb-product-feeds/src/core/mysql.js:15:12)
    at tryCatch (/var/www/lbb-product-feeds/node_modules/regenerator-runtime/runtime.js:45:40)
    at Generator.invoke [as _invoke] (/var/www/lbb-product-feeds/node_modules/regenerator-runtime/runtime.js:271:22)
    at Generator.prototype.(anonymous function) [as next] (/var/www/lbb-product-feeds/node_modules/regenerator-runtime/runtime.js:97:21)
    at tryCatch (/var/www/lbb-product-feeds/node_modules/regenerator-runtime/runtime.js:45:40)
    at invoke (/var/www/lbb-product-feeds/node_modules/regenerator-runtime/runtime.js:135:20)
    at /var/www/lbb-product-feeds/node_modules/regenerator-runtime/runtime.js:170:11
  message: 'Connection lost: The server closed the connection.',
  code: 'PROTOCOL_CONNECTION_LOST',
  errno: undefined,
  sqlState: undefined,
  sqlMessage: undefined }
```

**Comment by iturn** [comment]
This also happens on cloud run

**Comment by doender** [comment]
I'm also facing this on cloud run now and then. Are there any configuration changes we can make to alleviate this issue?

**Comment by adminDelcom** [comment]
None that i've found @doender

**Comment by panzerdp** [comment]
Having the same problem on Cloud Run.

**Comment by iturn** [comment]
Are all if you also using the v2.x of this package? I haven't tried the v3 branche

**Comment by panzerdp** [comment]
> Are all if you also using the v2.x of this package? I haven't tried the v3 branche

@iturn I'm using the version `3.6.0`.

**Comment by iturn** [comment]
Ok so it remains a issue, well in any case i had a lot of google cloud premium support on it and they were sure it wasnt on their side

**Comment by N-Andronopoulos** [comment]
NestJS in Cloud Run with:
`"mysql2": "^3.6.0",`
`"typeorm": "0.3.17"`

Settings: 
```
{
  type: 'mysql',
  socketPath: `${cfg.get('DB_SOCKET_PATH') || '/cloudsql'}/${cfg.get('INSTANCE_CONNECTION_NAME')}`,
  username: cfg.get('DB_USER'),
  password: cfg.get('DB_PASS'),
  database: cfg.get('DB_NAME'),
  autoLoadEntities: true,
  synchronize: false,
  logging: false,
  keepConnectionAlive: true,
  connectTimeout: 5000,
  extra: {
    // Connection Pooling
    waitForConnections: true,
    connectionLimit: 80,
    maxIdle: 10, // max idle connections, the default value is the same as `connectionLimit`
    idleTimeout: 60000, // idle connections timeout, in milliseconds, the default value 60000
    queueLimit: 0,
  }
}
 ```

Happens to us too 8 times per month. 
Dunno if SQL Cloud proxy related.

Maybe we should use a lower `idleTimeout: 60000` than `wait_timeout: 28800`?

**Comment by weilinzung** [comment]
We are using Cloud Run and have this error too with an Express app, here is the stack trace:


```
QueryFailedError
home/node_modules/.pnpm/typeorm@0.2.45_ioredis@5.3.2_mysql2@3.6.0_redis@3.1.1/node_modules/src/error/TypeORMError.ts:7
Connection lost: The server closed the connection.
Oct 19th 2023, 01:45:42 EDT

STACKTRACE

QueryFailedError Connection lost: The server closed the connection. 
    home/node_modules/.pnpm/typeorm@0.2.45_ioredis@5.3.2_mysql2@3.6.0_redis@3.1.1/node_modules/src/error/TypeORMError.ts:7:8 e.TypeORMError [as constructor]
    home/node_modules/.pnpm/typeorm@0.2.45_ioredis@5.3.2_mysql2@3.6.0_redis@3.1.1/node_modules/src/error/QueryFailedError.ts:9:8 new QueryFailedError
    home/node_modules/.pnpm/typeorm@0.2.45_ioredis@5.3.2_mysql2@3.6.0_redis@3.1.1/node_modules/typeorm/src/driver/mysql/MysqlQueryRunner.ts:196:36 t.onResult
    home/node_modules/.pnpm/mysql2@3.6.0/node_modules/mysql2/lib/connection.js:228:20 _k._notifyError
    home/node_modules/.pnpm/mysql2@3.6.0/node_modules/mysql2/lib/connection.js:123:11 Socket.<anonymous>
    node:events:513:28 Socket.emit
    node:domain:489:12 Socket.emit
    node:net:301:12 Pipe.<anonymous>
    node:internal/async_hooks:130:17 Pipe.callbackTrampoline


```

**Comment by edudesouza** [comment]
Hi there I had the same problem and resolve this way:

`const con_prod = mysql.createPool({

  connectionLimit       : 50,
  socketPath            : "/cloudsql/......",
  user                  : ".....",
  password              : ".....",
  database              : "......",
  maxIdle               : 10, 
  idleTimeout           : 60000,
  queueLimit            : 0,
  enableKeepAlive       : true,
  keepAliveInitialDelay : 0,

});`

`async function getConnectionFromPool(pool) {
    
    return new Promise((resolve, reject) => {
      pool.getConnection((err, connection) => {

        if(err) {
          enviar_email("Edu", "eduardo@.......com.br", "ERRO BB Con SQL", sql_query+'<hr/>'+err.sqlMessage);   
        }else{
          resolve(connection);
        }          

      });
    });

  }`

then check the conection

const connection = await getConnectionFromPool(con_prod);

console.log('-> Conection: ', connection.state );
console.log('-> Conection: ', connection.threadId );

connection.query(sql_query, (err,rows) =>{});
connection.release();
