### ISSUE TITLE
Pool connections won't release

### ISSUE THREAD

**Issue by Tino-F** [sidorares/node-mysql2#1012]
So I have 2 files. 1 of them is used to export the pool, and the other creates a connection from the pool and uses that connection to preform a transaction. However, after I commit and release the transaction, the connection don't get released for reuse and I get an error message saying , `Error: No connections available.`

sqlConnectionPool.js
```js
const mysql = require('mysql2');
const pool = mysql.createPool({
  host: 'localhost',
  user: process.env.SQL_USER,
  password: process.env.SQL_PASS,
  database: 'Test',
  waitForConnections: false,
  connectionLimit: 3,
  queueLimit: 0
});
const promisePool = pool.promise();

console.log('\x1b[32m' + '[SQL] Connected to database' + '\x1b[0m');

function uncaughtException( p ) {

  console.log( 'An uncaughtException has occured \n', p );

  console.log('\x1b[33m' + '[SQL] Disconnecting from database...' + '\x1b[0m');

  pool.end(function (err) {

    console.log('\x1b[32m' + '[SQL] Disconnected.' + '\x1b[0m');
    process.exit()

  });

}

function exitHandler() {

  console.log('\x1b[33m' + '[SQL] Disconnecting from database...' + '\x1b[0m');

  pool.end(function (err) {

    console.log('\x1b[32m' + '[SQL] Disconnected.' + '\x1b[0m');
    process.exit()

  });

}

process.on( 'SIGINT', exitHandler );
process.on( 'uncaughtException', uncaughtException );

module.exports = promisePool;
```

registerUser.js
```js

const pool            = require('../../sqlConnectionPool.js'),
  writeErr            = require('../fx/writeError'),
  unexpectedMessage   = {
  success: false,
  message: 'An unexpected error has occured, please try again later'
};

query1 = 'INSERT ...'
query2 = 'SELECT ...'
query3 = 'INSERT ...'
query4 = 'INSERT ...'

module.exports = async ( req, res, next ) {

  const connection = await pool.getConnection();
  await connection.beginTransaction();
  
  try {

      await connection.execute( query1, [ data ] );
      await connection.execute( query2, [ data ] );
      await connection.execute( query3, [ data ] );
      await connection.execute( query4, [ data ] );

      await connection.commit();
      connection.release();
      next();

  } catch ( err ) {

      await connection.rollback();
      connection.release();

      writeErr( `Failed to execute registration transaction.\n ${err}` );
      res.json( unexpectedMessage );

  }

}

```

registerUserRoute.js
```js

const argon2              = require('argon2'),
  transporter             = require('../emailTransport'),
  config                  = require('../config'),
  sendVerificationCode    = require('./fx/sendVerificationCode'),
  writeErr                = require('./fx/writeError'),
  validateEmail           = require('./validateNewInput/email'),
  validateFirstName       = require('./validateNewInput/firstName'),
  validateLastName        = require('./validateNewInput/lastName'),
  validateUsername        = require('./validateNewInput/username'),
  validateDescription     = require('./validateNewInput/description'),
  validatePassword        = require('./validateNewInput/password'),
  vaidateTOS              = require('./validateNewInput/underTOSAgreement'),
  validateDevice          = require('./validateInput/device'),
  registerToDB            = require('./sqlActions/registerUser');

async function encryptPassword( req, res, next ) {
  try {

    const hash = await argon2.hash( req.body.password );
    req.body.password = hash;
    next();

  } catch ( err ) {

    writeErr( err );
    res.json({
      success: false,
      message: 'An unexpected error has occured, please try again later.'
    });

  }
}

function Register ( req, res, next ) {

  res.json({
    message: `An verification email has been sent to ${req.body.email}.`,
    success: true
  });

}

module.exports = app => {

  app.route('/api/register')
  .post([
    validateEmail,
    validateFirstName,
    validateLastName,
    validateUsername,
    validateDescription,
    validateDevice,
    validatePassword,
    vaidateTOS,
    encryptPassword,
    registerToDB,
    sendVerificationCode,
    ( req, res, next ) => { console.log('Registered user'); next() },
    Register
  ])

}

```

And finally, here is the terminal output when I try registering users:
```
[SQL] Connected to database
Starting API on http://localhost:3000/.
Registered user
Registered user
Registered user
(node:12228) UnhandledPromiseRejectionWarning: Error: No connections available.
    at C:\Users\tinof\Documents\web\Veil-API\node_modules\mysql2\lib\pool.js:67:40
    at processTicksAndRejections (internal/process/task_queues.js:75:11)
(node:12228) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
```

**Comment by chengshubei** [comment]
I've had this problem before. Hope to be resolved

**Comment by sidorares** [comment]
@Tino-F you are not awaiting `connection.release()`. Under load this can potentially cause going over connections limit ( but it should eventually release connection ).

Could you reduce your example to something self contained? ( including temp tables creation and all the initial data ) Would be much easier to debug

**Comment by knoxcard** [comment]
@Tino-F - change all instances of `connection.release()` to `await connection.release()` and let us know the results here, thanks!

**Comment by Tino-F** [comment]
I actually solved this issue. There was a query on the login route that took a very long time and it was holding up the connections. The example registration attempts were actually an artillery.io test scenario that was trying to login with the credentials right after registration and I forgot that it was testing the login too. 

Thanks for the help tho everyone!
