### ISSUE TITLE
cannot conect to remote server ETEMEDOUT ERROR

### ISSUE THREAD

**Issue by Cosmin-Ciolacu** [sidorares/node-mysql2#1039]
Hi
I want to connect at my remote server in node:
this is node cod:
`const mysql =require('mysql2`)`
```
const conn = mysql.createConnection({
    host: 'MY_HOST_IP',
    port: 3306,
    user: 'MY_USER'
    password: 'MY_PASSWORD',
    connectTimeout: 30000
})
```
When run my code it shows me this error:
```
Error: connect ETIMEDOUT
    at Connection._handleTimeoutError (/Users/cosminciolacu/Desktop/test_data_js/node_modules/mysql2/lib/connection.js:169:17)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7) 
```
Thank you

**Comment by sidorares** [comment]
Does this happen if you don't set `connectTimeout: 30000` ?

**Comment by jeet6287** [comment]
@Cosmin-Ciolacu did you find anything ??, because i am facing the same issue.
Error: connect ETIMEDOUT
    at Connection._handleTimeoutError (/home/ec2-user/workspace/odinnodeserver/node_modules/mysql2/lib/connection.js:169:17)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7) {
  errorno: 'ETIMEDOUT',
  code: 'ETIMEDOUT',
  syscall: 'connect',
  fatal: true
}

**Comment by Cosmin-Ciolacu** [comment]
Ai don’t find nothing
