### ISSUE TITLE
Long stack trace missing from errors

### ISSUE THREAD

**Issue by abney317** [sidorares/node-mysql2#1067]
I am unable to see the long version of the stack traces from errors.

```
Error: Unknown column 'test' in 'field list'
    at Packet.asError (C:\example\node_modules\mysql2\lib\packets\packet.js:712:17)
    at Query.execute (C:\example\node_modules\mysql2\lib\commands\command.js:28:26)
    at PoolConnection.handlePacket (C:\example\node_modules\mysql2\lib\connection.js:408:32)
    at PacketParser.onPacket (C:\example\node_modules\mysql2\lib\connection.js:70:12)
    at PacketParser.executeStart (C:\example\node_modules\mysql2\lib\packet_parser.js:75:16)
    at Socket.<anonymous> (C:\example\node_modules\mysql2\lib\connection.js:77:25)
    at Socket.emit (events.js:200:13)
    at Socket.EventEmitter.emit (domain.js:471:20)
    at addChunk (_stream_readable.js:290:12)
    at readableAddChunk (_stream_readable.js:271:11) {
  code: 'ER_BAD_FIELD_ERROR',
  errno: 1054,
  sqlState: '42S22',
  sqlMessage: "Unknown column 'test' in 'field list'"
}
```

Becomes a bit difficult to debug things without any of my own code referenced in the stack trace.

[Node MySQL](https://github.com/mysqljs/mysql) has the long stack traces.
Is there a way to enable this, am I missing something, or has it just not been implemented here for MySQL2?

**Comment by sidorares** [comment]
No, it's just not implemented ( [here is how mysqljs is doing it](https://github.com/mysqljs/mysql/blob/8ae456f54d346dc84d49bba5a01888653ba2981b/lib/protocol/sequences/Sequence.js#L102-L121) ). The reason was partially performance ( having `new Error()` anywhere in the code used to prevent v8 from some optimisations even if it's behind the flag ), it's much better now so I might consider adding

You can do it yourself in your code by adding 3rd party long stack trace library such as https://github.com/mattinsler/longjohn

With async/await it's handled automatically by v8, so promise wrapper has much better stacks

**Comment by jpike88** [comment]
it's frustrating having to hunt around because the stack trace is useless, could you please consider making this a priority if it's easy to do

**Comment by jpike88** [comment]
And can just hide behind a flag if you're so worried about performance?

**Comment by samuel-soubeyran** [comment]
Came here while troubleshooting similar issues in a codebase using knex+mysql2. I don't think there is a way to make knex use the promise wrapper.

**Comment by RedSpid3r** [comment]
Just came here to bump this because having useless stack traces is exceedingly frustrating when trying to debug. Is there any ETA on when this might be looked at/considered for implementation? If not I may have to revert to using mysqljs because it's just not feasible to be unable to track down issues when they are impacting production environment

**Comment by K1Z4** [comment]
I had this issue because I was wrapping con.query in my own promise wrapper. 

Once I updated my code to use 'mysql2/promise' the stack traces were helpful again.

```
Error: Unknown column 'invalid' in 'field list'
    at PromisePoolConnection.query (/home/k1z4/Utils/node_modules/mysql2/promise.js:94:22)
    at FriendRepository.query (file:///home/k1z4/Utils/src/mysqlBase.js:6:21)
    at FriendRepository.insert (file:///home/k1z4/Utils/src/mysqlBase.js:72:27)
    at file:///home/k1z4/Utils/test/testApp.js:43:28
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async FriendRepository.inTransaction (file:///home/k1z4/Utils/src/mysqlBase.js:105:32)
    at async file:///home/k1z4/Utils/test/testApp.js:76:1 {
  code: 'ER_BAD_FIELD_ERROR',
  errno: 1054,
  sql: "INSERT INTO friend SET `name` = 'test4', `invalid` = 'invalid'",
  sqlState: '42S22',
  sqlMessage: "Unknown column 'invalid' in 'field list'"
}
```

My new query func with **useful** stack traces:
```
   static query(sqlString, params, pool = getPool()) {
        return pool.query(sqlString, params).then(([rows, fields]) => rows)
    }
```

My old query func with **bad** stack traces:
```
    static query(sqlString, params, con = getPool()) {
        if (typeof (sqlString) !== 'string') throw new Error("sqlString must be a string");
        if (!typeof params == 'object') throw new Error("params must be an object");

        return new Promise((resolve, reject) => {
            con.query(sqlString, params, (error, results, fields) => {
                if (error) {
                    return reject(error);
                }

                resolve(results, fields);
            });
        });
    }
```

**Comment by nolimitdev** [comment]
Yes, I have just found this bug, that after migrating from npm/mysql to npm/mysql2 traces are lost. Option `trace : true/false` described in mysql lib https://github.com/mysqljs/mysql#connection-options is not working in this mysql2 lib. Fortunately we can not migrate to mysql2 due to this bug.

**Comment by mukunda-** [comment]
Just adding my +1 here. Diagnosing errors is extremely tedious if the stack trace is missing. NestJS recommends mysql2, but I can't continue with it if I see cryptic errors like these:

![Image](https://github.com/user-attachments/assets/b1a2e557-a07a-4fc0-b643-c3dceecb27b7)

**Comment by nolimitdev** [comment]
@mukunda- as @K1Z4 wrote the only one solution is to use `import mysql from 'mysql2/promise'` instead of `import mysql from 'mysql2'`. Additionally if you use own wrapper class, methods can not by marked as async (so you can not use `await` inside methods) but you must use older way then/catch and return promise manually...


```
import mysql from 'mysql2/promise';

class MySQL {
    constructor(options) {
        this.pool = null;
        this.connect(options);
    }

    connect(options) {
        this.pool = mysql.createPool(options);
    }

    // Do not use "async query(query, args = null) {" + await inside because you will lose stack trace
    query(query, args = null) {
        return new Promise((resolve, reject) => {
            this.pool.query(query, args)
                .then(([result]) => {
                    resolve(result);
                })
                .catch((error) => {
                    reject(error);
                });
        });
    }
}
```

**Comment by mukunda-** [comment]
@nolimitdev I find that in my case it's actually a typeorm issue, not the mysql driver.

With typeorm, the original mysql lib also only captures up to the typeorm driver with the "trace" option, and the rest is truncated. I've opened an issue there: https://github.com/typeorm/typeorm/issues/11271

**Comment by aaronabf** [comment]
Bumping this.

**Comment by bramtechs** [comment]
Would like seeing this improved.
