### ISSUE TITLE
use mysql-proxy some bug

### ISSUE THREAD

**Issue by einsqing** [sidorares/node-mysql2#1115]
```
Warning: got packets out of order. Expected 9 but received 33
Warning: got packets out of order. Expected 10 but received 34
Warning: got packets out of order. Expected 11 but received 35
Warning: got packets out of order. Expected 12 but received 36
Warning: got packets out of order. Expected 13 but received 37
Warning: got packets out of order. Expected 14 but received 38
undefined:1
[object Object]
 ^

SyntaxError: Unexpected token o in JSON at position 1
    at JSON.parse (<anonymous>)
    at new TextRow (eval at line.toFunction (/Users/heqing/git/haika/node_modules/generate-function/index.js:172:21), <anonymous>:16:26)
    at Query.row (/Users/heqing/git/haika/node_modules/mysql2/lib/commands/query.js:223:17)
    at Query.execute (/Users/heqing/git/haika/node_modules/mysql2/lib/commands/command.js:39:22)
    at Connection.handlePacket (/Users/heqing/git/haika/node_modules/mysql2/lib/connection.js:417:32)
    at PacketParser.onPacket (/Users/heqing/git/haika/node_modules/mysql2/lib/connection.js:75:12)
    at PacketParser.executeStart (/Users/heqing/git/haika/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.<anonymous> (/Users/heqing/git/haika/node_modules/mysql2/lib/connection.js:82:25)
    at Socket.emit (events.js:200:13)
    at addChunk (_stream_readable.js:290:12)
    at readableAddChunk (_stream_readable.js:271:11)
    at Socket.Readable.push (_stream_readable.js:226:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:166:17)
```

**Comment by sidorares** [comment]
can you please convert that to more self contained example?

From previous messages it might look like you are trying to read JSON field from your client part of the proxy but server incorrectly gives `"[object Object]"` string as a content of that field

**Comment by einsqing** [comment]
@sidorares Because there are JSON fields in the data table

**Comment by einsqing** [comment]
@sidorares 
```
[
  'return ((function () {\n  return function TextRow(packet, fields, options, ' +
    'CharsetToEncoding) {\n    // "id": LONG\n    this["id"] = ' +
    'packet.parseLengthCodedIntNoBigCheck();\n    // "menuId": LONG\n    ' +
    'this["menuId"] = packet.parseLengthCodedIntNoBigCheck();\n    // "areaId": ' +
    'LONG\n    this["areaId"] = packet.parseLengthCodedIntNoBigCheck();\n    // ' +
    '"userId": LONG\n    this["userId"] = ' +
    'packet.parseLengthCodedIntNoBigCheck();\n    // "name": VAR_STRING\n    ' +
    'this["name"] = ' +
    'packet.readLengthCodedString(CharsetToEncoding[fields[4].characterSet]);\n ' +
    '   // "address": VAR_STRING\n    this["address"] = ' +
    'packet.readLengthCodedString(CharsetToEncoding[fields[5].characterSet]);\n ' +
    '   // "location": GEOMETRY\n    this["location"] = ' +
    'packet.parseGeometryValue();\n    // "tel": VAR_STRING\n    this["tel"] = ' +
    'packet.readLengthCodedString(CharsetToEncoding[fields[7].characterSet]);\n ' +
    '   // "status": LONG\n    this["status"] = ' +
    'packet.parseLengthCodedIntNoBigCheck();\n    // "rank": LONG\n    ' +
    'this["rank"] = packet.parseLengthCodedIntNoBigCheck();\n    // "extra": ' +
    'JSON\n    this["extra"] = ' +
    'JSON.parse(packet.readLengthCodedString("utf8"));\n    // "createdAt": ' +
    `TIMESTAMP\n    this["createdAt"] = packet.parseDateTime('local');\n    // ` +
    '"updatedAt": TIMESTAMP\n    this["updatedAt"] = ' +
    `packet.parseDateTime('local');\n    // "deletedAt": TIMESTAMP\n    ` +
    `this["deletedAt"] = packet.parseDateTime('local');\n  };\n})())`
]
```

**Comment by sidorares** [comment]
This is likely because in the client JSON fields gets automatically parsed, what you see is

value on the database side "{}", type JSON ->
client sees JSON field type, returns row as `field = {}` object ( not string )
it is sent back from proxy as `field.toString()` ( which is `[object Object]` )
that's interpreted by client connected to proxy as incorrect JSON

You need to check field type and for JSON fields send it using `JSON.stringify()`

**Comment by einsqing** [comment]
thx，resolve it
