### ISSUE TITLE
Fatal `Packets out of order` exception using `mysql` lib connecting to `mysql2` proxy

### ISSUE THREAD

**Issue by haganbt** [sidorares/node-mysql2#1162]
Using the [example proxy](https://github.com/sidorares/node-mysql2/blob/master/examples/mysqlproxy.js), when making a client connection using the `mysql` library, a fatal exception occurs and the connection is lost.

Client example:

```javascript
const knex = require("knex")({
  client: "mysql",
  connection: {
    host: "127.0.0.1",
    port: 4000,
    user: "***",
    password: "***",
    database: "***"
  },
});

knex.raw("select 1").then(console.log);
```

The server exception:

```
nodemon] starting `node index.js`
connection
Warning: got packets out of order. Expected 3 but received 0
proxying query: select 1
events.js:298
      throw er; // Unhandled 'error' event
      ^

Error: Connection lost: The server closed the connection.
    at Socket.<anonymous> (/foo/node_modules/mysql2/lib/connection.js:91:31)
    at Socket.emit (events.js:321:20)
    at TCP.<anonymous> (net.js:668:12)
Emitted 'error' event on Connection instance at:
    at Connection._notifyError (/foo/node_modules/mysql2/lib/connection.js:221:12)
    at Socket.<anonymous> (/foo/node_modules/mysql2/lib/connection.js:97:12)
    at Socket.emit (events.js:321:20)
    at TCP.<anonymous> (net.js:668:12) {
  fatal: true,
  code: 'PROTOCOL_CONNECTION_LOST'
}
```

Client exception:

```
(node:1521) UnhandledPromiseRejectionWarning: Error: Packets out of order. Got: 4 Expected: 1
```

Please let me know if I can provide any further detail to help debug.

**Comment by haganbt** [comment]
Testing further, I notice that when logging `conn.clientHelloReply.encoding`, I see:

mysql2 client: `utf8`
mysql client: `cesu8`

Not sure if this is useful?

**Comment by haganbt** [comment]
Could this be related to the client encoding?

If I connect using `mysql2` I see `conn.clientHelloReply.encoding` set to `utf8`. If I connect using `mysql` I see `cesu8`.

Not sure, just an observation that might be useful.

**Comment by MartinGassner** [comment]
The exception disappears If I reset the `sequenceId` on the connection manually. 

I need to set it to `0` within the `authCallback`:

```javascript
conn.serverHandshake({
  protocolVersion: 10,
  serverVersion: 'node.js rocks',
  connectionId: 1234,
  statusFlags: 2,
  characterSet: 8,
  capabilityFlags: 0xffffff,
  authCallback: () => {
    conn.writeOk()
    conn.sequenceId = 0
  }
});
```

Also I set it to `1` within the "query" event:

```javascript
conn.on('query', sql => {
  console.log(`proxying query: ${sql}`);
  conn.sequenceId = 1
  remote.query(sql, function (err) {
    // overloaded args, either (err, result :object)
    // or (err, rows :array, columns :array)
    if (Array.isArray(arguments[1])) {
      // response to a 'select', 'show' or similar
      const rows = arguments[1], columns = arguments[2];
      console.log('rows', rows);
      console.log('columns', columns);
      conn.writeTextResult(rows, columns);
    } else {
      // response to an 'insert', 'update' or 'delete'
      const result = arguments[1];
      console.log('result', result);
      conn.writeOk(result);
    }
  });
});
```

I'm not sure if this is a valid solution. What do you think @sidorares ?
Maybe you have more context about this issue.

**Comment by sidorares** [comment]
I'm planning to make a very different version of server api ( not sure yet what it will become exactly ). The goal is to make it much easier to make high level server, where you handle commands ( not packets ).

"Packets out of order" problem is because packet counter has to be reset at the end of the command, and right now that not handles correctly automatically

**Comment by sidorares** [comment]
maybe not very clear description of what's intended: at the moment your server handler is called whenever client sends command, but unlike client where you add command ( and it has state machine to perform state updates as it exchanges multiple packets until the end of command ) on server side you need to write each packet manually

**Comment by dtikhonov-iex** [comment]
Thanks for this workaround, @MartinGassner.  I was hoping that the bug was something obvious (and I spent some time reading the code trying to figure it out), but from @sidorares's description it seems that this is a structural issue.

**Comment by haganbt** [comment]
@dtikhonov-iex see https://github.com/sidorares/node-mysql2/issues/528#issuecomment-944949065 also.
