### ISSUE TITLE
Proxy example: EPIPE error

### ISSUE THREAD

**Issue by haganbt** [sidorares/node-mysql2#1199]
When using `mysql2` as a proxy, using Wordpress as the client, several SQL requests are made when the wordpress home page is requested in quick succession. The first 4 queries succeed without issue, however the 5th fails with:

```
Error: write EPIPE
    at afterWriteDispatched (internal/stream_base_commons.js:156:25)
    at writeGeneric (internal/stream_base_commons.js:147:3)
    at Socket._writeGeneric (net.js:785:11)
    at Socket._write (net.js:797:8)
    at writeOrBuffer (_stream_writable.js:352:12)
    at Socket.Writable.write (_stream_writable.js:303:10)
    at Connection.write (/Users/VisualStudio/connection-manager-mysql/node_modules/mysql2/lib/connection.js:226:17)
    at Connection.writePacket (/Users/VisualStudio/connection-manager-mysql/node_modules/mysql2/lib/connection.js:271:12)
    at /Users/VisualStudio/connection-manager-mysql/node_modules/mysql2/lib/connection.js:743:12
    at Array.forEach (<anonymous>) {
  errno: -32,
  code: 'EPIPE',
  syscall: 'write',
  fatal: true
}
```

FYI, here is the sql that is executed:

```sql
SET NAMES utf8mb4;

SET NAMES 'utf8mb4' COLLATE 'utf8mb4_unicode_520_ci';

SELECT @@SESSION.sql_mode;

SET SESSION sql_mode='IGNORE_SPACE,NO_ZERO_IN_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION';

SELECT option_name, option_value FROM wp_options WHERE autoload = 'yes';
```

Im not sure how to debug this further. Appreciate any guidance.

**Comment by sidorares** [comment]
any error logs from wordpress side? what client is used? I assume it's https://www.php.net/manual/en/book.mysqli.php
Can you reduce scenario to a single short php script with 5 sequential queries?

**Comment by haganbt** [comment]
Many thanks @sidorares, the PHP error log reports this error for every sql query:

```
[Mon Sep 07 11:17:33.707720 2020] [php7:warn] [pid 10467] [client ::1:57622] PHP Warning:  Packets out of order. Expected 1 received 3. Packet size=1 in /Users/foo/www/wordpress/wp-includes/wp-db.php on line 2033
```

RE PHP client, you are correct, its mysqli. Currently running PHP 7.4. As suggested, I have written a basic PHP script that runs the same sql in the same order. This actually fails after the first query with:

```
Error: Connection lost: The server closed the connection.
    at Socket.<anonymous> (/Users/VisualStudio/connection-manager-mysql/node_modules/mysql2/lib/connection.js:91:31)
    at Socket.emit (events.js:314:20)
    at Socket.EventEmitter.emit (domain.js:486:12)
    at TCP.<anonymous> (net.js:673:12) {
  fatal: true,
  code: 'PROTOCOL_CONNECTION_LOST'
}
```

Nothing is logged on the apache side.  Im not sure why it cannot be replicated by the manual script however in an attempt to debug the packets out of order issue further, I ran this against a vanilla proxy example. I logged this yesterday as #1198 however thought that the `EPIPE` error may be the cause. In fact I think #1198 is the actual cause. I will close this ticket in favor of #1198.
