### ISSUE TITLE
Proxy: crash when operating between “real” mysql CLI and MariaDB

### ISSUE THREAD

**Issue by domq** [sidorares/node-mysql2#1207]
What I did:
1. Set up [mariadb:5.5](https://hub.docker.com/_/mariadb) in Docker on port 3306, create database `test` with `GRANT ALL` to `root` etc.
1. `npm init; npm add mysql2`
1. Paste [the proxy sample code](https://www.npmjs.com/package/mysql2/v/0.15.5#examples) into index.js, change `host:'127.0.0.1'` and run that (node v14.8.0; tested with node-mysql2 version v2.2.1 as well as today's master branch)

What I wanted: crash-less proxying bliss

What I got:

```
connection
Trace
    at Packet.readLengthCodedNumberExt (/Users/quatrava/Dev/FMPCQRS/node_modules/mysql2/lib/packets/packet.js:226:13)
    at Packet.readLengthCodedNumber (/Users/quatrava/Dev/FMPCQRS/node_modules/mysql2/lib/packets/packet.js:188:17)
    at Function.fromPacket (/Users/quatrava/Dev/FMPCQRS/node_modules/mysql2/lib/packets/handshake_response.js:116:32)
    at ServerHandshake.readClientReply (/Users/quatrava/Dev/FMPCQRS/node_modules/mysql2/lib/commands/server_handshake.js:38:56)
    at ServerHandshake.execute (/Users/quatrava/Dev/FMPCQRS/node_modules/mysql2/lib/commands/command.js:39:22)
    at Connection.handlePacket (/Users/quatrava/Dev/FMPCQRS/node_modules/mysql2/lib/connection.js:425:32)
    at PacketParser.onPacket (/Users/quatrava/Dev/FMPCQRS/node_modules/mysql2/lib/connection.js:75:12)
    at PacketParser.executeStart (/Users/quatrava/Dev/FMPCQRS/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.<anonymous> (/Users/quatrava/Dev/FMPCQRS/node_modules/mysql2/lib/connection.js:82:25)
    at Socket.emit (events.js:314:20)
/Users/quatrava/Dev/FMPCQRS/node_modules/mysql2/lib/packets/packet.js:227
    throw new Error(`Should not reach here: ${tag}`);
    ^

Error: Should not reach here: undefined
    at Packet.readLengthCodedNumberExt (/Users/quatrava/Dev/FMPCQRS/node_modules/mysql2/lib/packets/packet.js:227:11)
    at Packet.readLengthCodedNumber (/Users/quatrava/Dev/FMPCQRS/node_modules/mysql2/lib/packets/packet.js:188:17)
    at Function.fromPacket (/Users/quatrava/Dev/FMPCQRS/node_modules/mysql2/lib/packets/handshake_response.js:116:32)
    at ServerHandshake.readClientReply (/Users/quatrava/Dev/FMPCQRS/node_modules/mysql2/lib/commands/server_handshake.js:38:56)
    at ServerHandshake.execute (/Users/quatrava/Dev/FMPCQRS/node_modules/mysql2/lib/commands/command.js:39:22)
    at Connection.handlePacket (/Users/quatrava/Dev/FMPCQRS/node_modules/mysql2/lib/connection.js:425:32)
    at PacketParser.onPacket (/Users/quatrava/Dev/FMPCQRS/node_modules/mysql2/lib/connection.js:75:12)
    at PacketParser.executeStart (/Users/quatrava/Dev/FMPCQRS/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.<anonymous> (/Users/quatrava/Dev/FMPCQRS/node_modules/mysql2/lib/connection.js:82:25)
    at Socket.emit (events.js:314:20)
```

**Comment by haganbt** [comment]
@domq I recall seeing this some time ago also when using the proxy example. I think this was resolved by manually setting the packet `sequenceId`. See the example here: https://github.com/sidorares/node-mysql2/issues/1198#issuecomment-688537539

As I say im not 100% sure if that is the solution but worth a quick test.

**Comment by jpacora** [comment]
@sidorares @haganbt any solutions? Still hacing this error with the proxy example.
