### ISSUE TITLE
Incorrect arguments to mysqld_stmt_execute

### ISSUE THREAD

**Issue by perry-mitchell** [sidorares/node-mysql2#1239]
Hi, love this library!

Have been using it successfully across a large number of projects and it's worked flawlessly for me so far. Just now I've seen that I have a single test case failing on the CI server (Gitlab), MySQL 8, failing with the following error:

```
VError: Failed executing query: \"SELECT * FROM message WHERE chat_id = ? ORDER BY sent DESC LIMIT ? OFFSET ?\" [01ensmg6m4dea0gh7gsjgaa5gb, 50, 0]: Incorrect arguments to mysqld_stmt_execute
    at ConnectionPool.<anonymous> (/data/node_modules/@my-company/mysql-connection-pool/dist/ConnectionPool.js:128:27)
    at Generator.throw (<anonymous>)
    at rejected (/data/node_modules/@my-company/mysql-connection-pool/dist/ConnectionPool.js:6:65)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
caused by: Error: Incorrect arguments to mysqld_stmt_execute
    at PromiseConnection.execute (/data/node_modules/mysql2/promise.js:110:22)
    at ConnectionPool.<anonymous> (/data/node_modules/@my-company/mysql-connection-pool/dist/ConnectionPool.js:117:58)
    at Generator.next (<anonymous>)
    at fulfilled (/data/node_modules/@my-company/mysql-connection-pool/dist/ConnectionPool.js:5:58)
```

Now this error is wrapped by my own logic, but the cause I think it quite clear: `Incorrect arguments to mysqld_stmt_execute`. The query being passed to the `execute` method on the `mysql2/promise` library is `SELECT * FROM message WHERE chat_id = ? ORDER BY sent DESC LIMIT ? OFFSET ?` and the values are `["01ensmg6m4dea0gh7gsjgaa5gb", 50, 0]`. For some reason this only fails on the CI, and not locally on any of my (or my colleagues') machines.

If I change this to `query` instead of `execute`, it works on the CI. If I form this query manually using the values that were passed-in, and run it, it also works. 

Any idea what's happening here? Is there some failure in how the parameters are being transferred to the MySQL service before being inserted?

**Comment by perry-mitchell** [comment]
Not sure it helps, but this is the usage:

```typescript
export async function getChatMessages(
    chatID: string,
    limit: number,
    offset: number = 0,
    connection = getConnection()
): Promise<Array<MessageSlow>> {
    const [
        rows
    ] = await connection.execute(
        `SELECT * FROM message WHERE chat_id = ? ORDER BY sent DESC LIMIT ? OFFSET ?`,
        [chatID, limit, offset]
    );
    // Snip
}
```

**Comment by sidorares** [comment]
Could you try to prepare from mysql cli? 
```
mysql> PREPARE stmt1 FROM 'SELECT * FROM message WHERE chat_id = ? ORDER BY sent DESC LIMIT ? OFFSET ?';
```

trying to make sure sql syntax is valid ( there are limitation on to what can be a placeholder in PS )

**Comment by sidorares** [comment]
hm, re reading your text, it works on local machine. Can you double check your local mysql server version is exactly the same as on CI?

**Comment by dimitar3web** [comment]
I have the same problem since i updated mysql from 8.0.21 -> 8.0.22. I am pretty sure that my queries are alright cause i didnt have any issues before version upgrade. I`ve got ubintu (20.04) which I updated yesterday and after installing the update this error started. I tested the queries on older version (before yesterdays update) and it seems to work without any problem. Any advice?

**Comment by perry-mitchell** [comment]
Ok, that was a good recommendation @sidorares - I was not using the same version locally. I've updated my local to MySQL 8.0.22 and now it fails on many queries:

```
VError: Failed executing query: "
    SELECT
        m.chat_id,
        MAX(m.sent) AS sent,
        c.channel,
        c.is_completed
    FROM message AS m
    INNER JOIN chat AS c ON c.id = m.chat_id
    WHERE
        sent <= ? AND
        c.is_completed = 0
    GROUP BY m.chat_id
    LIMIT ?
" [2020-10-29 10:11:45, 10]: Incorrect arguments to mysqld_stmt_execute
```

_Variables above being `["2020-10-29 10:11:45", 10]`_

**Comment by sidorares** [comment]
@ruiquelhas could you comment on this 8.0.21 -> 8.0.22 incompatibility?

**Comment by ruiquelhas** [comment]
Yeah, there were some major changes with regards to how prepared statements work in the server (type inferences and whatnot), and unfortunately some specific queries might break. I'll look at this specific example as well. Thanks for the mention @sidorares.

**Comment by ruiquelhas** [comment]
@perry-mitchell what's the column datatype of `chat_id`? Just so I can re-create the exact same scenario.

**Comment by perry-mitchell** [comment]
@ruiquelhas `chat_id` is a `string`, 26 chars.

Confirming that `8.0.21` works for me, and `8.0.22` presents these prepare statement errors.

**Comment by ruiquelhas** [comment]
> @ruiquelhas `chat_id` is a `string`, 26 chars. The values being inserted in that first query are `["01ensmg6m4dea0gh7gsjgaa5gb", 50, 0]`.
> 
> Confirming that `8.0.21` works for me, and `8.0.22` presents these prepare statement errors.

@perry-mitchell I mean on the table column itself. The MySQL column datatype. Which one of [these](https://dev.mysql.com/doc/refman/8.0/en/string-types.html)?

**Comment by perry-mitchell** [comment]
@ruiquelhas `varchar(30)` sorry..

**Comment by bkarlson** [comment]
Just stumbled upon the same problem.  A statement works fine when using `query`, but fails with `execute`:
```
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '? ORDER BY video_id DESC LIMIT ?' at line 1
```

**Comment by bkarlson** [comment]
as a matter of fact, something's weird is on mysql side, working query cannot be prepared: 

```
mysql> PREPARE stmt SELECT video_id FROM videos ORDER BY video_id DESC LIMIT 10;
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'SELECT video_id FROM video_43 ORDER BY video_id DESC LIMIT 10' at line 1


mysql> SELECT video_id FROM videos ORDER BY video_id DESC LIMIT 10;
+-----------+
| video_id  |
+-----------+
[...]
+-----------+
10 rows in set (0.00 sec)
```

**Comment by sidorares** [comment]
@bkarlson try this:

```
mysql> PREPARE stmt1 FROM 'SELECT video_id FROM videos ORDER BY video_id DESC LIMIT 1';
```

**Comment by bkarlson** [comment]
well okay, it was lame act on my side with mysql, yet this statement works with `query` but not with `execute`

```js
const sqlVideos = `SELECT video_id FROM videos ORDER BY video_id DESC LIMIT ?`; 
pool.query(sqlVideosToProcess, [batchSize], async (err, rows) => {..

**Comment by sidorares** [comment]
@bkarlson probably not relevant to the topic, but why async callback?

**Comment by sidorares** [comment]
what error with execute? `You have an error in your SQL syntax` ?

**Comment by bkarlson** [comment]
> @bkarlson probably not relevant to the topic, but why async callback?

I'm just refactoring old `mysql` code to `mysql2` with promises, and stumbled upon this issue. Now wondering whether the rest of my queries would work...

**Comment by bkarlson** [comment]
> what error with execute? `You have an error in your SQL syntax` ?

yes

**Comment by ruiquelhas** [comment]
@perry-mitchell what about the datatype of the `sent` column?

**Comment by ruiquelhas** [comment]
@sidorares from a preliminary analysis, I'm not able to reproduce this issue with the `mysql` CLI or other wire protocol implementations with prepared statement support. Again, this seems to be related to the changes in how prepared statements work with regards to type inference and whatnot. As described in the 8.0.22 server release notes.

> Important Change: A prepared statement is now prepared only once, when executing PREPARE, rather than once each time it is executed. In addition, a statement inside a stored procedure is also now prepared only once, when the stored procedure is first executed. This change enhances performance of such statements, since it avoids the added cost of repeated preparation and rollback of preparation structures, the latter being the source of several bugs.

From what I can tell, one of the problems is that when encoding the [`COM_STMT_EXECUTE`](https://dev.mysql.com/doc/dev/mysql-server/8.0.22/page_protocol_com_stmt_execute.html) this driver is mapping all JavaScript `number` values to `MYSQL_TYPE_DOUBLE` and ignoring the type hint available in the  [`COM_STMT_PREPARE Response`](https://dev.mysql.com/doc/dev/mysql-server/8.0.22/page_protocol_com_stmt_prepare.html#sect_protocol_com_stmt_prepare_response).

In this specific case, if we force the driver to encode the value using a `MYSQL_TYPE_LONGLONG` type (which is the one suggested by the server after the `prepare` stage), it seems to work fine.

In any case, I'm still trying to figure out the entire thing. In the meantime, we can take this "offline" and discuss how can this be addressed from the client POV, because the server will own these changes.

**Comment by perry-mitchell** [comment]
> what about the datatype of the sent column?
@ruiquelhas It's a `timestamp`

**Comment by sidorares** [comment]
> Important Change: A prepared statement is now prepared only once, when executing PREPARE, rather than once each time it is executed.

@ruiquelhas can you clarify this?

That is also current behaviour or mysql2 driver: it sends COM_PREPARE only once for the first `.execute()` call and later if query is the same statement id is re used. I read server changelog the same way: when you do `PREPARE` command, after parsing it server uses body of the prepare argument and caches result ( previously each new PREPARE would generate new statement id ) - is that correct?

**Comment by sidorares** [comment]
>   mapping all JavaScript number values to MYSQL_TYPE_DOUBLE and ignoring the type hint available in the COM_STMT_PREPARE Response.

yes. Initially this driver was using dtring type for all parameters relying on server to do all the translation to actual expected types, and right now types are inferred from JS parameters ( and not on based on what we know server expects as a parameter ) - added in #353 and #705

also ref 
https://github.com/sidorares/node-mysql2/pull/516#issuecomment-459656963
( I'm sure I discussed "we need to use types from prepare response to serialize parameters" somewhere before but can't find it )

**Comment by ruiquelhas** [comment]
> > Important Change: A prepared statement is now prepared only once, when executing PREPARE, rather than once each time it is executed.
> 
> @ruiquelhas can you clarify this?
> 
> That is also current behaviour or mysql2 driver: it sends COM_PREPARE only once for the first `.execute()` call and later if query is the same statement id is re used. I read server changelog the same way: when you do `PREPARE` command, after parsing it server uses body of the prepare argument and caches result ( previously each new PREPARE would generate new statement id ) - is that correct?

Yeah, the client flow is/was fine. That just mentions the change that happened in the server, which internally was always preparing statements once for each execution. That isn't the case anymore, and the statements are now prepared effectively once (only when `PREPARE` is called i.e. when [`COM_STMT_PREPARE`](https://dev.mysql.com/doc/dev/mysql-server/8.0.22/page_protocol_com_stmt_prepare.htm) is sent). This caused some changes in the way dynamic parameters used in prepared statements are resolved (in particular when it comes to derive their type). Up until now, you could get away with sending different parameter types in the [`COM_STMT_EXECUTE`](https://dev.mysql.com/doc/dev/mysql-server/8.0.22/page_protocol_com_stmt_execute.html), and the statement would basically be re-prepared using that type. This isn't the case now, and even though I haven't explored it in full, I guess, at least, `COM_STMT_EXECUTE` will have to use the types hinted by the [`COM_STMT_PREPARE` Response](https://dev.mysql.com/doc/dev/mysql-server/8.0.22/page_protocol_com_stmt_prepare.html#sect_protocol_com_stmt_prepare_response).

If you are interested, the full write-up of those server changes is available [here](https://dev.mysql.com/worklog/task/?id=9384).

**Comment by dalalmj** [comment]
Any update to this? Facing same error on 8.0.22. Works with query, fails with execute (works properly on 8.0.14)

**Comment by sidorares** [comment]
@dalalmj no update on my side, reading @ruiquelhas comment I guess we need to make sure that types used for serialising parameters are exactly those returned by COM_STMT_PREPARE response ( right now we use dynamically whatever is parameters - number / string / buffer etc ) - might be wrong, need to double check

**Comment by ruiquelhas** [comment]
@dalalmj if it happens on 8.0.19 then it's probably not related to this specific issue. The changes I mentioned were only introduced by the MySQL server in 8.0.22.

**Comment by dalalmj** [comment]
@ruiquelhas, my mistake, I tried installing 8.0.19, but now see that apt-get always installs latest 8.0.22.

**Comment by dalalmj** [comment]
@sidorares, just FYI, instead of passing javascript number type, if value is passed as "string" (even though column in int), it works!

**Comment by YangJ0605** [comment]
mysql => 8.0.22 
mysql2  => 2.2.5

 const statement = `
      SELECT 
        moment.id as id, 
        moment.content as content, 
        moment.createAt createTime, 
        moment.updateAt updataTime, 
        JSON_OBJECT('id', users.id, 'username', users.username) author
      FROM moment LEFT JOIN users 
      ON moment.user_id = users.id 
      LIMIT ? OFFSET ?;`

connection.execute(statement, [size + "", page + ""])

replace number with characters

**Comment by damianobarbati** [comment]
So we can't use node-mysql2 + prepared statements on mysql 8.0.22, is this correct? :stumble:

@YangJ0605 did you actually apply some kind of monkey patch or did you rewrite all of your queries?

**Comment by maxghafori** [comment]
> mysql => 8.0.22
> mysql2 => 2.2.5
> 
> const statement = ` SELECT moment.id as id, moment.content as content, moment.createAt createTime, moment.updateAt updataTime, JSON_OBJECT('id', users.id, 'username', users.username) author FROM moment LEFT JOIN users ON moment.user_id = users.id LIMIT ? OFFSET ?;`
> 
> connection.execute(statement, [size + "", page + ""])
> 
> replace number with characters

await conn.execute(query, [skip.toString(), pageSize.toString()]); 
work for me, thanks

**Comment by marnixhoh** [comment]
Hi, I ran into this issue too after upgrading mysql to `8.0.23` . @YangJ0605 's solution works, but it is pretty suboptimal to always have to convert numbers to strings when executing queries. This problem does not appear when using mysql `8.0.21` ...

@sidorares Is there a fix for this on the roadmap? Thanks :)

**Comment by AnnAngela** [comment]
I just switched my cloud MySQL database server provider, and faced this same problem.

My code runs on `mysql2@2.2.5` + `mysql-client 8.0.25-0ubuntu0.20.04.1`, and the new provider only has `mysql server 8.0.18 - Source distribution`, and I got the problem.

(But I DID NOT face this problem with `mysql server 8.0.22 - Source distribution` which providing from the previous provider)

The problem occured while running `connection.execute` with json:

```js
await connection.execute("INSERT INTO `__sth__` (`id`, `time`, `__json__`) VALUES (NULL, ?, ?);", [new Date().toISOString(), ["__some_json__"]]);
```

and my workaround is using `JSON.stringify`:

```js
await connection.execute("INSERT INTO `__sth__` (`id`, `time`, `__json__`) VALUES (NULL, ?, ?);", [new Date().toISOString(), JSON.stringify(["__some_json__"])]);
```

But this workaround is annoying and I hope there wiil be a solution without any workaround.

**Comment by ccwu** [comment]
This seems to be still be present in 8.0.24 which I recently moved to when I switched providers. It was working on a an older mySQL (of which the version I have to check). A version of @YangJ0605 where I .toString() parameters works and I have done an interim build. Not sure how the prepared statements work, but my gut tells me doing such is a risk for injection. So @YangJ0605's solution may be safer (a little messy when reading code) 

Is there a sense of fix timeline or a target branch we can follow to be notified when merged.

**Comment by solsson** [comment]
This issue is present with MariaDB 10.5.10 as well. I have been unable to find which MariaDB release that introduced the corresponding change to prepared statements.

I tried @vlasky's [interim fix](https://github.com/vlasky/node-mysql2/commit/0357a637649d03b6c051f11fc317aca87d4cf4f9) but it's insufficient in my case. Like @AnnAngela we're passing JSON values.

**Comment by wen-kai** [comment]
replacing our mysql2 references with @vlasky's [interim fix ](https://github.com/vlasky/node-mysql2/commit/0357a637649d03b6c051f11fc317aca87d4cf4f9) was the quickest solution to avoid touching all prepared statement references/arguments in our DB layer.

looking forward to reverting back to the original package when this breaking change gets fixed 🙏

**Comment by marnixhoh** [comment]
I just noticed that this error only occurs for me in the `LIMIT` and `OFFSET` clauses. I thought that these would expect integers, but they apparently do not.

At first I thought all integers would have to be cast to strings, but this turns out to NOT be the case. Again only the `LIMIT` and `OFFSET` clauses. Hope this helps someone else realize that fixing this across a code base is not a huge task.

**Comment by vlasky** [comment]
I have discovered that my interim fix has issues, at least when tested with Percona Server 8.0.23, Percona XtraDB Cluster 8.0.23 and presumably those same official MySQL versions.

Having looked at the general query log, it is clear that the server frequently unnecessarily re-preparing statements. This causes a performance hit and a constant increase in prepared statement handles, as shown by status variable `Prepared_stmt_count`.

It seems that the proper solution needs to be implemented, in which node-mysql2 respects the the type hint provided in the `COM_STMT_PREPARE` Response and converts data type of the parameters accordingly.

**Comment by pintarj** [comment]
As @ruiquelhas has stated all the numbers are passed by the driver as `DOUBLE` types. I know, that JavaScript sucks at dealing with integers, but there is a range of integers that can be safely represented using JavaScript's `number`.

My proposal is to pass those _safe integers_ as integers (therefore `LONGLONG`) and not as doubles. So the current code (`lib/packets/execute.js`) that now is:

```javascript
case 'number':
  type = Types.DOUBLE;
  length = 8;
  writer = Packet.prototype.writeDouble;
  break;
```
would become something like:
```javascript
case 'number':
  if (Number.isSafeInteger(value)) {
    type = Types.LONGLONG;
    length = 8;
    writer = Packet.prototype.writeInt64; // not implemented yet
  } else {
    type = Types.DOUBLE;
    length = 8;
    writer = Packet.prototype.writeDouble;
  }
  break;
```

This would solve this issue (I've tested locally) and maybe prevent many other ones.
Am I missing something? What do you think?

**Comment by abdallaoui-dev** [comment]
I think I found the solution:
// the problem
```
const limit: number = 10 
pool.execute("select * from table limit ?", [limit]) 
```
// error  incorrect arguments to mysqld_stmt_execute
// testing it on workbench
```
prepare st from "select * from table limit ?";
set @limit = 1
execute st using @limit;
```
// works find the problem appears when you do this @limit = '1'

// I think there is some casting problem in mysql2 or something

// the solution I found
```
const limit: string = '10'
pool.execute("select * from table limit ?", [limit])
```

// the reverse of what you should not do in mysql workbench!!

**Comment by Motaking05** [comment]
Hello 
Can anyone help me with this problem? :

[         script:npwd] [NPWD] [player] [error]: Failed to store phone number in database
[         script:npwd] [NPWD] [player] [error]: UPDATE users SET phone_number = 107-354-7665 WHERE identifier =

**Comment by alisson-acioli** [comment]
Hello, is this problem still persisting? I am passing this now on 08/2023

**Comment by sidorares** [comment]
@alisson-acioli yes, to a degree. You can work around it by casting your data to a more compatible type ( for example, pass number as a string ). We plan to add api to set mysql type of a parameter explicitly

**Comment by mikiU2022** [comment]
this problems persist... it's dec/2023.....

**Comment by sidorares** [comment]
@mikiU2022 its still November on my calendar, but thanks for the ping

**Comment by BlockifyTechnologies** [comment]
const sql = `SELECT * FROM DB.Users WHERE uid > ? ORDER BY uid LIMIT ?`;
      const values = [0, 50];

      try {
        const [results] = await connection.execute(sql, values);
        console.log("SQL Result: ", results);
      } catch (error) {
        console.error("Error executing SQL query:", error);
      }
      
      Why would a query as simple as this give me the error of incorrect arguments ?

**Comment by sidorares** [comment]
@BlockifyTechnologies short explanation: currently argument type is inferred from JS type ( you can see mapping [here](https://github.com/sidorares/node-mysql2/blob/ee43891f1f0247e74a681bf284144962900e7fa7/lib/packets/execute.js#L21-L74) ). Previously this worked fine as the server was able to convert to type actually expected by the statement, but after version 8.0.22 this behaviour changed, see https://github.com/sidorares/node-mysql2/issues/1239#issuecomment-718827355

Workaround for you right now: force it to be sent as string, `const values = ['0', '50'];`. In the future we'll add ability to explicitly set parameter type, the api would be something like this: `const values = [mysql.types.LONGLONG(0), mysql.types.LONGLONG(50)];` - that way 0 and 50 are sent as LONGLONG instead of default DOUBLE. Also we plan to potentially change default type to be the one returned from `prepare` call, but this can be unreliable ( `execute('SELECT ? as data')` would have a type, likely LONG, set in a response but in reality its "unknown type" )

**Comment by BlockifyTechnologies** [comment]
@sidorares 
`const values = [mysql.types.LONGLONG(0), mysql.types.LONGLONG(50)];` this seems like the perfect path to take. Hope this won't take too long! Thanks

**Comment by perry-mitchell** [comment]
We wrote a query wrapper in house to do this automatically.. and haven't had to think about it since. This particular problem can be abstracted away somewhat easily :)

**Comment by sidorares** [comment]
@perry-mitchell please share it!

**Comment by perry-mitchell** [comment]
I'm still in the process of convincing management to release the code. Trust me, if it were solely my decision I'd have responded with a link to it. I'll update here if something changes.

**Comment by HsinHeng** [comment]
Does "mysqld_stmt_execute" possible occur in database failover/auto-scaling/maintenance like [this](https://stackoverflow.com/questions/56946707/aws-aurora-auto-scaling-causes-incorrect-arguments-to-mysqld-stmt-execute)?

In my case, "mysqld_stmt_execute" is suddenly occupied after pod run several hours. I restart my POD and it seen been resolved. 
By the way, I use AWS aurora and it's maintenance yesterday. Did anyone meet this issue on database failover/auto-scaling/maintenance?

**Comment by fires3as0n** [comment]
I am sorry, but 4 years have passed since this issue was raised, there is MySQL 9 out there, I'm using the latest version of node-mysql2 library and still have to apply [this solution by damianobarbati](https://github.com/sidorares/node-mysql2/issues/1239#issuecomment-766867699) in every project. 

If this is not going to be fixed any  time in the future, am thinking about just cloning the repo and disabling [this case statement](https://github.com/vlasky/node-mysql2/commit/0357a637649d03b6c051f11fc317aca87d4cf4f9)
As a temporary solution, to avoid patching the execute in server side code, but I wonder, won't it break anything?

The library itself is great, no push, I understand that this is a minor problem and appreciate your time for the open source. Thank you.

**Comment by sidorares** [comment]
hey @fires3as0n thanks for a friendly nudge
If you have a capacity for a proper solution I can try to guide you.

Initial step I see is to allow to manually specify the type. For example, we'll provide a value+type containers, and when you pass a value using that container the data type and serialisation format will match to that of the parameter.

example:

```js
// not sure about naming, say we have StatementParameter exported with DOUBLE/LONG etc fields on them

connection.execute(`SELECT video_id FROM videos ORDER BY video_id DESC LIMIT ?`, StatementParameter.LONG(1))

```

execute command would be able to see type hint and use LONG instead of incorrect DOUBLE

**Comment by vlasky** [comment]
> I'm still in the process of convincing management to release the code. Trust me, if it were solely my decision I'd have responded with a link to it. I'll update here if something changes.
> 
> EDIT: Process is looking good, we might consider a release in the near future. Mind you the code is actually quite simple, so I don't think it's anything ground breaking. We're mostly just casting numbers => string in the parameters when detected. The library does provide improved pooling logic we had to write for AWS RDS instances (auto-stale connections), so maybe something else is beneficial there.
> 
> EDIT 2: My company agreed for me to open source the repo. I'll have it up in the coming days.

@perry-mitchell where can I find your repo with the node-mysql2 query wrapper code?

**Comment by anshvert** [comment]
@Sohamnimbalkar07 This Suprisingly Worked !.

**Comment by danielsharvey** [comment]
> hey [@fires3as0n](https://github.com/fires3as0n) thanks for a friendly nudge If you have a capacity for a proper solution I can try to guide you.
> 
> Initial step I see is to allow to manually specify the type. For example, we'll provide a value+type containers, and when you pass a value using that container the data type and serialisation format will match to that of the parameter.
> 
> example:
> 
> // not sure about naming, say we have StatementParameter exported with DOUBLE/LONG etc fields on them
> 
> connection.execute(`SELECT video_id FROM videos ORDER BY video_id DESC LIMIT ?`, StatementParameter.LONG(1))
> execute command would be able to see type hint and use LONG instead of incorrect DOUBLE

@sidorares I'm looking at this. My concept is to accept `Number`'s and `Long`s with the MySQL type annotated as follows:

```ts
Object.defineProperty(value, Symbol.for('mysql2:StatementParameterType'), {
   enumerable: false,
   value: Types.LONG
});
```

The annotation could be added by a helper function similar to your suggestion `StatementParameter.LONG(1)`.

Let me know your thoughts.

**Comment by danielsharvey** [comment]
> execute command would be able to see type hint and use LONG instead of incorrect DOUBLE

Of note, a mechanism that also currently works is to specify limit and offset parameter values as `bigint`'s.

e.g. `1n` or `BigInt(1)`

These are not incorrectly encoded as DOUBLES but fall through to a default encoding as strings, which works.

Ideally, the Prepared Statement encoding would be updated to encode `bigint`'s as LONGLONG (int64).

See https://github.com/sidorares/node-mysql2/blob/68519f04ea458a45195b0774bb5d4c91d1dd0ab1/lib/packets/execute.js#L63-L64

**Comment by ashleybartlett** [comment]
We have run into this issue recently too, but given how we are using the library as an abstraction to talk to a database directly.

Given we don't have control over the incoming queries, if [the proposed solution of specifying the type was used](https://github.com/sidorares/node-mysql2/issues/1239#issuecomment-2241488554) we would need to ask the users of our service to know to do this, which is then an interesting side problem.

I'm wondering why the [proposal to check for if a Number `isInteger` and passing longlong](https://github.com/sidorares/node-mysql2/issues/1239#issuecomment-929981923) instead doesn't work? This seems like an intuitive approach to use as a short term solution. The only caveat here seems to be that it classifies `3.0` as an integer. With MySQL if someone passes through a `3.0` does that need to behave differently to `3`?

I see in your [PR you are using the response from prepare to do this](https://github.com/sidorares/node-mysql2/pull/1407), this seems like a good fix, but I can imagine this would take longer to get into a ready state. Would it be an option, even behind a optional flag, to do isInteger parsing to get something into the library sooner?
