### ISSUE TITLE
Cannot insert multiple rows using one execution statement

### ISSUE THREAD

**Issue by stevetsim** [sidorares/node-mysql2#1246]
MySQL Server Version: 8.0.22
Node.js Version: 14.15.0

My Code:
```javascript
    const sql = 'INSERT INTO bookings(id,b,c,d,e,f) VALUES ?'
    const params = [
      [ '1', 'b', 'c', 'd', 'e', 'f' ],
      [ '2', 'b', 'c', 'd', 'e', 'f' ],
      [ '3', 'b', 'c', 'd', 'e', 'f']
    ]
    pool.execute(sql, [params], (error, results, fields) => {
      if (error) {
        return callback(error)
      }
      return callback(null, results)
    })

```

Here is the error message:
```
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '?' at line 1
    at Packet.asError (/Backend/node_modules/mysql2/lib/packets/packet.js:712:17)
    at Prepare.execute (/Backend/node_modules/mysql2/lib/commands/command.js:28:26)
    at PoolConnection.handlePacket (/Backend/node_modules/mysql2/lib/connection.js:425:32)
    at PacketParser.onPacket (/Backend/node_modules/mysql2/lib/connection.js:75:12)
    at PacketParser.executeStart (/Backend/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.<anonymous> (/Backend/node_modules/mysql2/lib/connection.js:82:25)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:284:9)
    at Socket.Readable.push (_stream_readable.js:223:10) {
  code: 'ER_PARSE_ERROR',
  errno: 1064,
  sqlState: '42000',
  sqlMessage: "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '?' at line 1"
}
```

**Comment by sidorares** [comment]
this is what error says - your statement is likely incorrect, try for example in mysql cli `PREPARE stmt from 'INSERT INTO bookings(id,b,c,d,e,f) VALUES ?'`

what you can have ( manually or dynamically construction parts of the query ) is something like this:

```js
const sql = 'INSERT INTO bookings(id,b,c,d,e,f) VALUES (?,?,?,?),(?,?,?,?),(?,?,?,?)(?,?,?,?)'
    const params = [
       '1', 'b', 'c', 'd', 'e', 'f',
       '2', 'b', 'c', 'd', 'e', 'f',
       '3', 'b', 'c', 'd', 'e', 'f'
    ]
//...
```

**Comment by sidorares** [comment]
@stevetsim see #1244 and linked issued
