### ISSUE TITLE
createServer crashing on `show variables` query

### ISSUE THREAD

**Issue by chromonav** [sidorares/node-mysql2#1252]
#### Problem:
When you run the query: `show variables` the server crashes with the following error:
```
Warning: got packets out of order. Expected 7 but received 0

/Users/office/Desktop/Stuff/sumo-proxy/node_modules/mysql2/lib/connection.js:91
        this._protocolError = new Error(
                              ^
Error: Connection lost: The server closed the connection.
    at Socket.<anonymous> (/node_modules/mysql2/lib/connection.js:91:31)
    at Socket.emit (events.js:315:20)
    at Socket.EventEmitter.emit (domain.js:483:12)
    at TCP.<anonymous> (net.js:674:12)
```
#### Following is the SQL proxy implemented for the purpose of logging:
```typescript
const mysql = require("mysql2");
const fixtures = require("./mysql_std.json");
const server = mysql.createServer();
const AuthUtil = require("./authUtils");
server.listen(3307);
let id = 0;

let i = 0;
server.on("connection", (conn: any) => {
  console.log("connection");

  conn.serverHandshake({
    protocolVersion: 10,
    serverVersion: "5.6.10",
    incomingId: i++,
    statusFlags: 2,
    characterSet: 8,
    capabilityFlags: 0xffffff, // everything
    authCallback: (params: any, callback: any) => {
      console.log(params);

      const user = params.user;

      console.info("Authenticating user " + user + ".");

      const pw = "Pass@1234";
      if (!pw || typeof pw !== "string") {
        console.warn("Invalid username or password for user " + user + ".");
        return callback(null, {
          message: "Invalid username or password.",
          code: 1045,
        });
      }

      const doubleSha = AuthUtil.doubleSha1(pw);
      const isValid = AuthUtil.verifyToken(
        params.authPluginData1,
        params.authPluginData2,
        params.authToken,
        doubleSha
      );

      if (isValid) {
        console.log("User " + user + " authenticated.");
        callback(null);
      } else {
        console.warn("Invalid username or password for user " + user + ".");
        callback(null, {
          message: "Invalid username or password.",
          code: 1045,
        });
      }

      conn.sequenceId = 0;
    },
  });

  conn.on("field_list", (table: any, fields: any) => {
    console.log("field list:", table, fields);
    conn.writeEof();
  });

  const remote = mysql.createConnection({
    user: "root",
    database: "mysql",
    host: "127.0.0.1",
    password: "Pass@1234",
  });

  conn.on("query", function (sql: any) {
    console.log("query", sql.toLowerCase());
    conn.sequenceId = 1;

    remote.query(sql, (err: any, result: any, columns: any) => {
      console.log("result", result, "columns", columns);
      if (Array.isArray(result)) {
        conn.writeColumns(columns);
        conn.writeTextRow(result);
        conn.writeEof();
      } else {
        console.log("result", result);
        conn.writeOk(result);
      }
    });
  });

  conn.on("end", remote.end.bind(remote));
  conn.on("quit", () => {
    conn.end();
  });
});

```

**Comment by chromonav** [comment]
TablePlus Configuration: 
![image](https://user-images.githubusercontent.com/5052568/100243038-76682c00-2f5b-11eb-8ae5-6234cd0508b8.png)

**Comment by sidorares** [comment]
try to add ` conn.on("error", ` handler, it's called when client hard ends connection ( without sending `COM_QUIT` command )

**Comment by chromonav** [comment]
Adding `conn.on("error",` does not kill the server, but the application does not get the correct response.
Following error occurs:
![image](https://user-images.githubusercontent.com/5052568/100418295-89d4dd80-30a8-11eb-93ca-e9ea36229d27.png)

**Comment by arei** [comment]
I have found that you need to zero the sequence id after every request/response with create server.  Here's an example of how my query handler looks:

```
incoming.on('query', async query => {
	incoming.stream.pause();

	Log.debug('Querying \'' + query + '\'');
	try {
		const [rows, fields] = await outgoing.promise().query(query);
				
		if (Array.isArray(rows)) {
			Log.debug('Query \'' + query + '\'', fields.length + ' columns, ' + rows.length + ' rows.');
			incoming.writeTextResult(rows, fields);
		} else {
			Log.debug('Query \'' + query + '\'', rows.affectedRows + ' Updated Rows, ' + rows.insertId + ' Inserted Rows.');
			incoming.writeOk(rows);
		}
			
		// dont forget to zero the sequenceId after each.
		incoming.sequenceId = 0;
		incoming.stream.resume();
	} catch (ex) {
		Log.debug('Error in Query \'' + query + '\'', ex);
	}
});
```

Notice the `incoming.sequenceId = 0;` at the bottom of that.

**Comment by chromonav** [comment]
@arei thanks for your response, I will try and get back to you.
