### ISSUE TITLE
ECONNRESET

### ISSUE THREAD

**Issue by kevinmartin** [sidorares/node-mysql2#128]
I get these errors sometimes. Randomly.

```
    Error: read ECONNRESET 
        at exports._errnoException (util.js:742:11) 
        at TCP.onread (net.js:535:26)
```

and 

```
    Error: write ECONNRESET 
        at exports._errnoException (util.js:742:11) 
        at Object.afterWrite (net.js:749:14) 
```

I read somewhere that this also happens on `node-mysql`, but that it could be fixed by using pool. I began using pool, but it still happens.

Suggestions?

**Comment by jsbinette** [comment]
I get this error too but only when I use koa-proxy which depends on co-request.  When I hit the post directly on the (VPN) server, I don't have the problem.
```
Error: read ECONNRESET
      at exports._errnoException (util.js:742:11)
      at TCP.onread (net.js:535:26)
```
The code I'm using is very simple

```
router.post('/api/Produit/:method',  proxy({
  host: "http://192.168.XXX.X"
}))
```

**Comment by sidorares** [comment]
@jsbinette - is that new connection can't be established to mysql server or existing drops? Do you have local mysql server localhost:3306 ? Which version of node-mysql2 are you using?

**Comment by jsbinette** [comment]
@sidorares Sorry turns out it doesn't apply.   In my case, koa-better-body interfered somehow with the post when it went thru the proxy.

**Comment by farzher** [comment]
getting this sometimes randomly. simple test server, nothing complex happening on it.

```
{ Error: read ECONNRESET
    at PromisePool.query (./node_modules/mysql2/promise.js:323:22)
    at Object.select (./lib/db.js:36:44)
    at <anonymous>
  message: 'read ECONNRESET',
  code: 'ECONNRESET',
  errno: 'ECONNRESET',
  sqlState: undefined,
  sqlMessage: undefined }

**Comment by sidorares** [comment]
@farzher could be anything - server idle timeout, network issues etc

**Comment by farzher** [comment]
@sidorares you don't seem surprised that this causes random errors on production servers.
shouldn't the library do some kind of error catching retries before throwing an error?
or is everyone supposed to write custom wrapper code to do that themselves? (i missed the memo)
or is computer software just supposed to have some errors?

**Comment by sidorares** [comment]
@farzher this is a low level driver and retries out of the scope. It's not clear from your report if you can catch and process error in your code or it's something that your code can't handle ( if latter, it definitely need to be fixed )

The "best practise" usually is to never use individual connections directly and use connection pool ( even if one connection is enough from perf point of view ). But even with pool you absolutely must be able to handle errors from production code and make a decision what to do ( retry / log / report to user )

**Comment by jsbinette** [comment]
For one I agree that this driver should have a ‘keep alive’ option.  It’s hard to debug and there are no ‘using’ keyword like c# that makes it easy o handle in JavaScript 




Thursday, January 10, 2019, 6:42 PM -0500 from notifications@github.com  <notifications@github.com>:

**Comment by sidorares** [comment]
@jsbinette you can always use pool instead of single connection for that

connection here is "immutable" in that sense. If it dies you create new one instead of ressurrecting internal state (re-connecting tcp / re-doing hanshake etc )

**Comment by sidorares** [comment]
> lazy people like me are reminded to do proper error handling.

error handling is always required with any library. Built in retries just make it less frequent/visible ( you still have to handle case when number of attempts is over limit )

In theory we might have it easier for pool users to have automatic retries, for example have a function you pass to config that can decide "retry or not" based on failed query.

**Comment by farzher** [comment]
i guess i didn't mean error handling, error.. retrying? idk it's not a concept i thought about.

if `db.query()` gives an error, i assume the database is broken or something and handle that as gracefully as i can. what i didn't realize is that sometimes those errors are fixable simply by retrying!

so you're telling me i'm supposed to look at the error message you return, figure out which ones are retryable, and retry? that's the part i'm lazy about, i assumed you'd take care of that because why should i have to.

**Comment by sidorares** [comment]
The biggest problem is the driver doesn't know what's save to retyr ( aka "idempotent" ). Say you do "please delete row with oldest updatedAt" and you get network error. At the moment you see error you don't even know if row was already deleted, so recovery from error is completely app logic specific

**Comment by farzher** [comment]
makes sense. i was just running a select though, you could always auto retry that.

you're saying most of the time if the connection is messed up before you try to execute the query, you'll auto retry to get a working connection? but this ECONNRESET error i got happened at an unlucky time where you weren't sure if it executed?

**Comment by sidorares** [comment]
driver sets `fatal` flag on error, if it's not set it means you can still use connection and make another query, if set - you need to recycle it and create new one ( pool does this for you ) - https://github.com/sidorares/node-mysql2/blob/efec9d5cfc3496bb254f72d5a8d7258d797c2e3e/lib/connection.js#L146

**Comment by farzher** [comment]
for anyone getting this error randomly. i guess you're supposed to write this wrapper around `pool.query` (or whatever call you're using). stops the problem for me.

```javascript
function query_with_retries(sql, params, retries_left=1) {
  try {
    return pool.query(sql, params)
  } catch(err) {
    if(retries_left >= 1 && err.code === 'ECONNRESET') {
      console.error({msg:'query_with_retries retrying!', retries_left, err})
      return query_with_retries(sql, params, retries_left-1)
    } else {
      throw err
    }
  }
}
```

**Comment by benbotto** [comment]
I'm sorry to wake the dead here, but I'm struggling to fix this in my code as well.  It has caught me by surprise after deploying to production, which isn't the ideal time to encounter the error.

MySQL has a `wait_timeout` which is 8 hours by default.  If no queries run against a connection in that 8-hour time frame, MySQL evidently terminates the connection.  Is my understanding correct in that this library's connection pool does not handle those terminations and blindly attempts to reuse the terminated connections?  Is it not possible for the library to establishing new connections when the server closes idle ones?  I see farzher's code snippet (and thanks for that!), but is there a more keep-alive type solution that can be used as a workaround?  I've seen some people using a `SELECT 1`-on-an-interval approach, but I don't understand how that will keep all of the connections in a pool alive.

Thanks for the support.

**Comment by ytejas1701** [comment]
Very late to the discussion, but @benbotto could you please tell me how you solved this issue finally? I wasn't able to find any proper solutions on the internet.
