### ISSUE TITLE
Process doesn't not exit / connection.destroy throws unexpected "write after end" exception

### ISSUE THREAD

**Issue by bluenote10** [sidorares/node-mysql2#1282]
A very basic example like this never terminates:

```js
const mysql = require("mysql2");

function main() {
  let connection = mysql.createConnection({
    host: "172.17.0.2",
    port: 3306,
    user: "root",
    password: "some-password",
  });
  connection.connect();
  console.log("Reached end of main.");
}

main();
```

My expectation was that this should be fixable by adding a `connection.destroy()` at the end of the `main` function. However that crashes with:

```
Reached end of main.
Error [ERR_STREAM_WRITE_AFTER_END]: write after end
    at Socket.Writable.write (_stream_writable.js:292:11)
    at Connection.write (/home/user/project_root/node_modules/mysql2/lib/connection.js:230:32)
    at Connection.writePacket (/home/user/project_root/node_modules/mysql2/lib/connection.js:279:12)
    at ClientHandshake.sendCredentials (/home/user/project_root/node_modules/mysql2/lib/commands/client_handshake.js:64:16)
    at ClientHandshake.handshakeInit (/home/user/project_root/node_modules/mysql2/lib/commands/client_handshake.js:137:12)
    at ClientHandshake.execute (/home/user/project_root/node_modules/mysql2/lib/commands/command.js:39:22)
    at Connection.handlePacket (/home/user/project_root/node_modules/mysql2/lib/connection.js:425:32)
    at PacketParser.onPacket (/home/user/project_root/node_modules/mysql2/lib/connection.js:75:12)
    at PacketParser.executeStart (/home/user/project_root/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.<anonymous> (/home/user/project_root/node_modules/mysql2/lib/connection.js:82:25)
```

I know that I can enforce termination via a hard `process.exit()` but I wanted to find out how to properly cleanup all resources.

**Comment by sidorares** [comment]
`connection.destroy()` immediately closes the socket, but in your example that happened just before driver was about to send handshake response back to the server. Some options for you:

1) add error handler to a connection (this is always recommended anyway) : `connection.on('error', err => { ... })`. Not sure if that would help to catch the crash you see, if not worth fixing on a driver side

2) use `connection.end()` instead, unlike `connection.destroy()` it sends COM_QUIT command and waits for the server to close connection

**Comment by bluenote10** [comment]
:+1: thanks for the hints!

Perhaps it makes sense add something like that to the examples in the readme?

I mainly opened the issue, because simply copy/pasting the first example leads to a stuck program, and a new user has to start investigating how to properly solve that. I started searching other issues, came across mentions of [`connection.close()`](https://github.com/sidorares/node-mysql2/issues/767#issuecomment-380620296) (which are the natural thing I also tried first, but they no longer seem to exist), and `connection.destroy()` was just the next best thing my auto completion had offered.

**Comment by awwright** [comment]
I just came here to ask how to close a connection, and closing a _pool_ of connections.

I would like to see this described in the documentation.
