### ISSUE TITLE
(node:12454) UnhandledPromiseRejectionWarning: Error: Encoding not recognized

### ISSUE THREAD

**Issue by qishuo** [sidorares/node-mysql2#1333]
(node:12454) UnhandledPromiseRejectionWarning: Error: Encoding not recognized: 'undefined' (searched as: 'undefined')
    at Object.getCodec (/Users/x/xx/node_modules/mysql2/node_modules/iconv-lite/lib/index.js:106:23)
    at Object.getEncoder (/Users/x/xx/node_modules/mysql2/node_modules/iconv-lite/lib/index.js:117:23)
    at Object.exports.encode (/Users/x/xx/node_modules/mysql2/lib/parsers/string.js:23:25)
    at Query.toPacket (/Users/x/xx/node_modules/mysql2/lib/packets/query.js:16:30)
    at Query.start (/Users/x/xx/node_modules/mysql2/lib/commands/query.js:55:38)
    at Query.execute (/Users/x/xx/node_modules/mysql2/lib/commands/command.js:39:22)
    at Connection.handlePacket (/Users/x/xx/node_modules/mysql2/lib/connection.js:408:32)
    at Connection.addCommand (/Users/x/xx/node_modules/mysql2/lib/connection.js:430:12)
    at Connection.query (/Users/x/xx/node_modules/mysql2/lib/connection.js:493:17)

**Comment by vivi2015** [comment]
check mysql character
![企业微信截图_16238978147374](https://user-images.githubusercontent.com/10387963/122327097-e7a31700-cf5f-11eb-808a-fbed6a002270.png)

**Comment by vivi2015** [comment]
check mysql character
![企业微信截图_16238978147374](https://user-images.githubusercontent.com/10387963/122327097-e7a31700-cf5f-11eb-808a-fbed6a002270.png)
mysql2 do not support utf8mb3
![image](https://user-images.githubusercontent.com/10387963/122327318-3f418280-cf60-11eb-928e-16f5394b5410.png)

**Comment by sidorares** [comment]
closing this one, #1398 tracks same issue

**Comment by sidorares** [comment]
hm, the [docs say](https://dev.mysql.com/doc/refman/8.0/en/charset-unicode-utf8mb3.html) that utf8mb3 is an alias for "utf8" encoding, which for historical reasons is acually a "cesu-8" encoding ( see  https://github.com/sidorares/node-mysql2/pull/374#issuecomment-241728060 )

@dougwilson do you have an experience with `utf8mb3` in mysql? Is it actually `CESU-8` under the hood?

**Comment by dougwilson** [comment]
Yea, `utfmb3` is just an alias for `utf8` (which is `CESU-8`). It was added when `utf8mb4` was in order to, I guess, have aliases for utf8 that specify the number of bytes. TL;DR `utf8` mysql encoding is simply an alias to `utf8mb3` (https://dev.mysql.com/doc/refman/8.0/en/charset-unicode-utf8.html).
