### ISSUE TITLE
Handle server closed the connection

### ISSUE THREAD

**Issue by andershagebakken** [sidorares/node-mysql2#150]
Hello. I am using mysql2 and I am using a connection pool. Is there anyway I can deal with this issue:

```javascript
events.js:72
        throw er; // Unhandled 'error' event

Error: Connection lost: The server closed the connection.
    at Socket.<anonymous> (/root/digsig/node_modules/mysql2/lib/connection.js:106:15)
    at Socket.emit (events.js:117:20)
    at _stream_readable.js:943:16
    at process._tickCallback (node.js:419:13)
```

Thanks in advance

**Comment by sidorares** [comment]
you need to attach 'error' handler to a connection object:

```js
connection.on('error', function() {
  // whenever something unexpected happen, this function is calles
}
```

note that "error" event is special in node. If event is emitted and you don't have handler attached an exception is thrown
