### ISSUE TITLE
Random ETIMEDOUT errors when using the new AWS Graviton processors

### ISSUE THREAD

**Issue by rsshilli** [sidorares/node-mysql2#1516]
I have a number of Lambdas that run just fine with MySQL 2. I recently switched from using Intel (`x86_64` architecture) to the new AWS Graviton Lambda architecture (`arm64`) and now I randomly see 1 in 4 requests fail because this package (or possibly Sequelize) fails to connect to the MySQL database. 

Yes, I know there are no native bindings in this package. And yes, I've verified there are no other processes running on the MySQL DB (using `show processlist`) while this package times out. 

Here's the stack trace that I'm seeing:
```
⚠ ERROR:
    ERROR :: connect ETIMEDOUT
    :: Name: SequelizeConnectionError
    :: Stack Trace:
    SequelizeConnectionError: connect ETIMEDOUT
    at /opt/nodejs/node_modules/sequelize/lib/dialects/mysql/connection-manager.js:133:19
    at clsBind (/opt/nodejs/node_modules/cls-hooked/context.js:172:17)
    at tryCatcher (/opt/nodejs/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/opt/nodejs/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/opt/nodejs/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/opt/nodejs/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/opt/nodejs/node_modules/bluebird/js/release/promise.js:725:18)
    at _drainQueueStep (/opt/nodejs/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/opt/nodejs/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/opt/nodejs/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/opt/nodejs/node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (internal/timers.js:464:21)
    at process.topLevelDomainCallback (domain.js:152:15)
    at process.callbackTrampoline (internal/async_hooks.js:128:24)
```

Feel free to close this ticket. It's a Hail Mary just in case somebody has seen this before or can think of why the connection would be unreliable on an ARM architecture as opposed to Intel.

**Comment by rsshilli** [comment]
Well, huh. Upgrading from MySQL2 version `1.7.0` to `2.3.3` seemed to fix this problem. I can't explain why that is, but I'm happy. Yay!

**Comment by sidorares** [comment]
hm, interesting. 

This is what might contributed to fix: https://github.com/sidorares/node-mysql2/blob/dadef383098b0823a90e07fbec18639bd612adfb/lib/connection.js#L57

To me comment above the linked line is not valid anymore, initially `setKeepAlive()` was only used when `enableKeepAlive` flag is set but I think now it's on by default. See some context in #683
