### ISSUE TITLE
Open handles potentially keeping Jest from exiting

### ISSUE THREAD

**Issue by patolax** [sidorares/node-mysql2#1575]
Any idea why jest is not exiting. It shows following as the reason. 

39 | async function execute(sql): Promise<ResultSetHeader> {
    > 40 |   const [results, fields] = await pool.execute(sql);
         |                                        ^
      41 |   return (results as ResultSetHeader);
      42 | }
      43 |

      at new Connection (node_modules/mysql2/lib/connection.js:45:27)
      at new PoolConnection (node_modules/mysql2/lib/pool_connection.js:7:5)
      at Pool.getConnection (node_modules/mysql2/lib/pool.js:51:20)
      at Pool.execute (node_modules/mysql2/lib/pool.js:167:10)
      at node_modules/mysql2/promise.js:370:18
      at PromisePool.execute (node_modules/mysql2/promise.js:365:12)
      at Object.execute (src/db.ts:40:40)
      at src/db.ts:1042:39
      at Object.<anonymous>.__awaiter (src/db.ts:985:10)
      at Object.execute (src/db.ts:1131:10)
      at execute (test.functions.ts:4:26)
      at test.functions.ts:1040:40
      at Object.<anonymous>.__awaiter (test.functions.ts:983:10)
      at initializeTestDatabase (test.functions.ts:1061:10)
      at Object.<anonymous> (src/db_service.spec.ts:13:25)
      at TestScheduler.scheduleTests (node_modules/@jest/core/build/TestScheduler.js:317:13)
      at runJest (node_modules/@jest/core/build/runJest.js:407:19)
      at _run10000 (node_modules/@jest/core/build/cli/index.js:338:7)
      at runCLI (node_modules/@jest/core/build/cli/index.js:190:3)

**My code**

```
`import { ResultSetHeader, RowDataPacket } from 'mysql2'

require('dotenv-flow').config();

const DB_HOST = process.env.DB_HOST;
const DB_USER = process.env.DB_USER;
const DB_PWD = process.env.DB_PWD;
const DB_NAME = process.env.DB_NAME;

function connection() {
  try {
    const mysql = require('mysql2');

    const pool = mysql.createPool({
      host: DB_HOST,
      user: DB_USER,
      password: DB_PWD,
      port: '3306',
      database: DB_NAME,
      timezone: 'Z',
      connectionLimit: 10,
      waitForConnections: true,
      queueLimit: 0,
    });
    const promisePool = pool.promise();

    return promisePool;
  } catch (error) {
    return console.log(`Could not connect - ${error}`);
  }
}

const pool = connection();
async function query(sql): Promise<RowDataPacket[]> {
  const [results, fields] = await pool.query(sql);
  return results as RowDataPacket[];
}

async function execute(sql): Promise<ResultSetHeader> {
  const [results, fields] = await pool.execute(sql);
  return (results as ResultSetHeader);
}

module.exports = {
  connection: async () => pool.getConnection(),
  query,
  execute
};`
```

**Comment by sidorares** [comment]
you probably need to call `await pool.end()` somewhere in the `afterAll` teardown
