### ISSUE TITLE
Statement unprepare crash

### ISSUE THREAD

**Issue by csimi** [sidorares/node-mysql2#160]
I'm getting the following crashes for around 5% of requests with higher concurrency:

```
TypeError: Cannot call method 'execute' of undefined
    at PoolConnection.Connection.handlePacket (/opt/api-devel/node_modules/mysql2/lib/connection.js:297:28)
    at PacketParser.onPacket (/opt/api-devel/node_modules/mysql2/lib/connection.js:83:65)
    at PacketParser.executeStart (/opt/api-devel/node_modules/mysql2/lib/packet_parser.js:39:12)
    at Socket.<anonymous> (/opt/api-devel/node_modules/mysql2/lib/connection.js:95:31)
    at Socket.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:748:14)
    at Socket.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:410:10)
    at emitReadable (_stream_readable.js:406:5)
    at readableAddChunk (_stream_readable.js:168:9)
    at Socket.Readable.push (_stream_readable.js:130:10)
    at TCP.onread (net.js:528:21)
```

For some reason I can't reproduce it on my local machine but it happens on the development servers which are connected to a Percona cluster.
Basically I'm creating a prepared statement for a query that uses an IN clause, and since these are not very cacheable I'd like to immediately close them (in the callback). That's when the crashes happen.
Tried using execute/unprepare and prepare/execute/close but both seem to have the same issue.

I thought this might be due to unpreparing a statement before it gets executed by a different request, but shouldn't the statements be separate especially in the prepare/execute/close case?

**Comment by sidorares** [comment]
interesting. This might be related to #113 but might be a bug in the client code.

It looks like sometimes there is a reply to "statement close" command ( error reply packet? ) Would be really helpful if you could make a debug log and post few pages of logs before crash.

If it's actually bad server behaviour client has to handle it properly - emit "error" event and close connection, but I'd like to figure out the reason first.

I'll try to see what happens when you try to unprepare non-existing statement id ( unprepare does not report successful result back at al, I'd expect it not to report error as welll )

**Comment by sidorares** [comment]
no, manually setting statement id to wrong value before `unprepare()` or `stmt.close()` does not result in error packet

**Comment by sidorares** [comment]
it would be good to investigate the reason, but at least you can handle the error now in connection 'error' event handler - please try v0.15.4
