### ISSUE TITLE
TypeError: Cannot call method 'apply' of undefined

### ISSUE THREAD

**Issue by kevinhikaruevans** [sidorares/node-mysql2#161]
This error seems to be happening on all of my queries. Doesn't seem to be affecting anything though since it seems to work fine...

````
{ [TypeError: Cannot call method 'apply' of undefined]
  domain:
   { domain: null,
     _events: { error: [Function: onError] },
     _maxListeners: 10,
     members: [ [Object], [Object] ] },
  domainThrown: true }
TypeError: Cannot call method 'apply' of undefined
    at Query.<anonymous> (/opt/web/api/node_modules/mysql2/lib/pool.js:133:10)
    at Query.b [as onResult] (domain.js:183:18)
    at /opt/web/api/node_modules/mysql2/lib/commands/query.js:56:14
    at process._tickDomainCallback (node.js:459:13)
````

I'm creating my queries with this:
````
var pool    = mysql.createPool({
  host:               '10.0.0.10',
  user:               '....',
  password:           '....',
  database:           'o3i_test',
  timezone:           'America/Los_Angeles', // shouldn't be used because dateStrings -> true
  dateStrings:        true,
  multipleStatements: true // change later
});
````

Then just calling `pool.query()`

**Comment by kevinhikaruevans** [comment]
Oh, I figured it out.

Was calling `pool.query` without passing in a function.
