### ISSUE TITLE
Weird  'RangeError: out of range index' error

### ISSUE THREAD

**Issue by hossam-fares** [sidorares/node-mysql2#169]
I was trying to execute this query as a prepared statement

```sql
SELECT
    IF(billing.id_location IS NOT NULL, TRUE, FALSE) AS is_billing_location,
    shipping.address1 AS shipping_address1,
    shipping.id_location AS shipping_id_location,
    IF(shipping.id_location IS NOT NULL, TRUE, FALSE) AS shipping_is_location
FROM item
LEFT JOIN order on order.id = item.id
LEFT JOIN address shipping ON order.id_shipping = shipping.id
LEFT JOIN address billing ON so.id_billing = billing.id

WHERE order.id_customer = 123

GROUP BY item.id;
```

but I got that error message:

```shell
Debug: internal, implementation, error 
     RangeError: out of range index
    at RangeError (native)
     at Packet.readLengthCodedString (/src/node_modules/mysql2-promise/node_modules/mysql2/lib/packets/packet.js:271:22)
     at new BinaryRow (evalmachine.<anonymous>:10:40)
     at Execute.Query.row (/src/node_modules/mysql2-promise/node_modules/mysql2/lib/commands/query.js:194:13)
     at Execute.Command.execute (/src/node_modules/mysql2-promise/node_modules/mysql2/lib/commands/command.js:34:20)
     at PoolConnection.Connection.handlePacket (/src/node_modules/mysql2-promise/node_modules/mysql2/lib/connection.js:310:28)
     at PacketParser.onPacket (/src/node_modules/mysql2-promise/node_modules/mysql2/lib/connection.js:83:65)
     at PacketParser.executeStart (/src/node_modules/mysql2-promise/node_modules/mysql2/lib/packet_parser.js:39:12)
     at Socket.<anonymous> (/src/node_modules/mysql2-promise/node_modules/mysql2/lib/connection.js:95:31)
     at Socket.emit (events.js:107:17)
     at readableAddChunk (_stream_readable.js:163:16)
     at Socket.Readable.push (_stream_readable.js:126:10)
     at TCP.onread (net.js:538:20)

```

I run the sql statement on sql client and it was executed without any problems.

**Comment by sidorares** [comment]
could you run it with debug: true connection option? I'd like to see generated row parser (paste all log if there is no sensitive data)

**Comment by hossam-fares** [comment]
Here you go:

```shell
 Add command: Connection
 2 undefined ==> Connection#handshakeInit(0,,91)
  raw: 0a352e362e31392d307562756e7475302e31342e30342e3100b5040000723652792d71736f00fff70802007f801500000000000000000000522b7c5573616d21597e2e68006d7973716c5f6e61746976655f70617373776f726400
 Server hello packet: capability flags:-2139097089=(long password, found rows, long flag, connect with db, no schema, compress, odbc, local files, ignore space, protocol 41, interactive, ignore sigpipe, transactions, reserved, secure connection, multi statements, multi results, ps multi results, plugin auth, remember options)
 Sending handshake packet: flags:193487=(long password, found rows, long flag, connect with db, odbc, local files, ignore space, protocol 41, ignore sigpipe, transactions, reserved, secure connection, multi results)
 2 1205 <== Connection#handshakeInit(1,,76)
 2 1205 ==> Connection#handshakeResult(2,maybeOK,7)
  raw: 00000002000000
 Add command: prepare
 2 1205 <== prepare#start(0,,60)
 2 1205 ==> prepare#prepareHeader(1,maybeOK,12)
  raw: 000100000001000100000000
 2 1205 ==> prepare#readParameter(2,,23)
  raw: 03646566000000013f000c3f0000000000fd8000000000
 2 1205 ==> prepare#parametersEOF(3,EOF,5)
  raw: fe00000200
 2 1205 ==> prepare#readField(4,,79)
  raw: 036465660d6e616d7368695f6465765f61650b73616c65735f6f726465720b73616c65735f6f726465720b666b5f637573746f6d65720b666b5f637573746f6d65720c3f000a000000032840000000
 2 1205 ==> prepare#fieldsEOF(5,EOF,5)
  raw: fe00000200
 Add command: executeStatement
 2 1205 <== executeStatement#start(0,,30)
 2 1205 ==> executeStatement#resultsetHeader(1,,1)
  raw: 01
         Resultset header received, expecting 1 column definition packets
 2 1205 ==> executeStatement#readField(2,,79)
  raw: 036465660d6e616d7368695f6465765f61650b73616c65735f6f726465720b73616c65735f6f726465720b666b5f637573746f6d65720b666b5f637573746f6d65720c3f000a000000032840000000
 2 1205 ==> executeStatement#fieldsEOF(3,EOF,5)
  raw: fe00000200
 Compiled binary protocol row parser:
 (function(){ return function BinaryRow(packet) {
   var statusByte = packet.readInt8();
   var nullBitmaskByte0 = packet.readInt8();
   // "fk_customer": LONG
   if (nullBitmaskByte0 & 4)
     this["fk_customer"] = null;
   else
     this["fk_customer"] = packet.readInt32();
 }; })()
 2 1205 ==> executeStatement#row(4,maybeOK,6)
  raw: 00002de10700
 2 1205 ==> executeStatement#row(5,EOF,5)
  raw: fe00000200
 Add command: prepare
 2 1205 <== prepare#start(0,,679)
 2 1205 ==> prepare#prepareHeader(1,maybeOK,12)
  raw: 000200000004000000000000
 2 1205 ==> prepare#readField(2,,48)
  raw: 036465660000001a62696c6c696e675f69735f7069636b75705f6c6f636174696f6e000c3f0001000000088100000000
 2 1205 ==> prepare#readField(3,,87)
  raw: 036465660d6e616d7368695f6465765f6165087368697070696e671373616c65735f6f726465725f61646472657373117368697070696e675f61646472657373310861646472657373310c2100fd020000fd0010000000
 2 1205 ==> prepare#readField(4,,107)
  raw: 036465660d6e616d7368695f6465765f6165087368697070696e671373616c65735f6f726465725f616464726573731b7368697070696e675f666b5f7069636b75705f6c6f636174696f6e12666b5f7069636b75705f6c6f636174696f6e0c3f000a000000030000000000
 2 1205 ==> prepare#readField(5,,48)
  raw: 036465660000001a62696c6c696e675f69735f7069636b75705f6c6f636174696f6e000c3f0001000000088100000000
 2 1205 ==> prepare#fieldsEOF(6,EOF,5)
  raw: fe00000200
 Add command: executeStatement
 2 1205 <== executeStatement#start(0,,14)
 2 1205 ==> executeStatement#resultsetHeader(1,,1)
  raw: 04
         Resultset header received, expecting 4 column definition packets
 2 1205 ==> executeStatement#readField(2,,48)
  raw: 036465660000001a62696c6c696e675f69735f7069636b75705f6c6f636174696f6e000c3f0001000000030100000000
 2 1205 ==> executeStatement#readField(3,,87)
  raw: 036465660d6e616d7368695f6465765f6165087368697070696e671373616c65735f6f726465725f61646472657373117368697070696e675f61646472657373310861646472657373310c2100fd020000fd0010000000
 2 1205 ==> executeStatement#readField(4,,107)
  raw: 036465660d6e616d7368695f6465765f6165087368697070696e671373616c65735f6f726465725f616464726573731b7368697070696e675f666b5f7069636b75705f6c6f636174696f6e12666b5f7069636b75705f6c6f636174696f6e0c3f000a000000030000000000
 2 1205 ==> executeStatement#readField(5,,48)
  raw: 036465660000001a62696c6c696e675f69735f7069636b75705f6c6f636174696f6e000c3f0001000000030100000000
 2 1205 ==> executeStatement#fieldsEOF(6,EOF,5)
  raw: fe00000200
 Compiled binary protocol row parser:
 (function(){ return function BinaryRow(packet) {
   var statusByte = packet.readInt8();
   var nullBitmaskByte0 = packet.readInt8();
   // "billing_is_pickup_location": LONGLONG
   this["billing_is_pickup_location"] = packet.readSInt64();
   // "shipping_address1": VAR_STRING
   if (nullBitmaskByte0 & 8)
     this["shipping_address1"] = null;
   else
     this["shipping_address1"] = packet.readLengthCodedString();
   // "shipping_fk_pickup_location": LONG
   if (nullBitmaskByte0 & 16)
     this["shipping_fk_pickup_location"] = null;
   else
     this["shipping_fk_pickup_location"] = packet.readSInt32();
   // "billing_is_pickup_location": LONGLONG
   this["billing_is_pickup_location"] = packet.readSInt64();
 }; })()
 2 1205 ==> executeStatement#row(7,maybeOK,34)
  raw: 0010010000001754657374204176656e756520426c64673a34383137333601000000
 2 1205 ==> executeStatement#row(8,maybeOK,34)
  raw: 0010000000001754657374204176656e756520426c64673a35353830333200000000
 2 1205 ==> executeStatement#row(9,maybeOK,34)
  raw: 0010000000001754657374204176656e756520426c64673a36303239373200000000
 2 1205 ==> executeStatement#row(10,maybeOK,34)
  raw: 0010000000001754657374204176656e756520426c64673a36303239373200000000
 2 1205 ==> executeStatement#row(11,maybeOK,38)
  raw: 0000000000001754657374204176656e756520426c64673a3635323034324100000000000000
 2 1205 ==> executeStatement#row(12,maybeOK,38)
  raw: 0000000000001754657374204176656e756520426c64673a3635323034324100000000000000
 2 1205 ==> executeStatement#row(13,maybeOK,38)
  raw: 0000000000001754657374204176656e756520426c64673a3635323034324100000000000000
 Debug: internal, implementation, error
     RangeError: Uncaught error: out of range index
     at RangeError (native)
     at Packet.readLengthCodedString (/src/node_modules/mysql2-promise/node_modules/mysql2/lib/packets/packet.js:271:22)
     at new BinaryRow (evalmachine.<anonymous>:10:40)
     at Execute.Query.row (/src/node_modules/mysql2-promise/node_modules/mysql2/lib/commands/query.js:194:13)
     at Execute.Command.execute (/src/node_modules/mysql2-promise/node_modules/mysql2/lib/commands/command.js:34:20)
     at PoolConnection.Connection.handlePacket (/src/node_modules/mysql2-promise/node_modules/mysql2/lib/connection.js:310:28)
     at PacketParser.onPacket (/src/node_modules/mysql2-promise/node_modules/mysql2/lib/connection.js:83:65)
     at PacketParser.executeStart (/src/node_modules/mysql2-promise/node_modules/mysql2/lib/packet_parser.js:39:12)
     at Socket.<anonymous> (/src/node_modules/mysql2-promise/node_modules/mysql2/lib/connection.js:95:31)
     at Socket.emit (events.js:107:17)
     at readableAddChunk (_stream_readable.js:163:16)
     at Socket.Readable.push (_stream_readable.js:126:10)
     at TCP.onread (net.js:538:20)

```

**Comment by sidorares** [comment]
this is weird, when I run your data manually step by step I get different parser:

```js
var Packet = require('mysql2/lib/packets/packet.js');
var Packets = require('mysql2/lib/packets/index.js');

function parse(s) {
  var raw = new Buffer(s, 'hex');
  var p = new Packet(0, raw, 0, raw.end);
  return new SAParser(p);
}

var fields = [];

function parseC(s) {
  var raw = new Buffer(s, 'hex');
  var p = new Packet(0, raw, 0, raw.end);
  debugger
  var c  = new Packets.ColumnDefinition(p);
  fields.push(c);
  return c.inspect();
}

console.log(parseC('036465660000001a62696c6c696e675f69735f7069636b75705f6c6f636174696f6e000c3f0001000000030100000000'));
console.log(parseC('036465660d6e616d7368695f6465765f6165087368697070696e671373616c65735f6f726465725f61646472657373117368697070696e675f61646472657373310861646472657373310c2100fd020000fd0010000000'));
console.log(parseC('036465660d6e616d7368695f6465765f6165087368697070696e671373616c65735f6f726465725f616464726573731b7368697070696e675f666b5f7069636b75705f6c6f636174696f6e12666b5f7069636b75705f6c6f636174696f6e0c3f000a000000030000000000'));
console.log(parseC('036465660000001a62696c6c696e675f69735f7069636b75705f6c6f636174696f6e000c3f0001000000030100000000'));

var compileParser = require('./lib/compile_binary_parser.js')

var p = compileParser(fields, {}, { debug: true });
```

prints
```js
(function(){ return function BinaryRow(packet) {
  var statusByte = packet.readInt8();
  var nullBitmaskByte0 = packet.readInt8();
  // "billing_is_pickup_location": LONG
  this["billing_is_pickup_location"] = packet.readSInt32();
  // "shipping_address1": VAR_STRING
  if (nullBitmaskByte0 & 8)
    this["shipping_address1"] = null;
  else
    this["shipping_address1"] = packet.readLengthCodedString();
  // "shipping_fk_pickup_location": LONG
  if (nullBitmaskByte0 & 16)
    this["shipping_fk_pickup_location"] = null;
  else
    this["shipping_fk_pickup_location"] = packet.readSInt32();
  // "billing_is_pickup_location": LONG
  this["billing_is_pickup_location"] = packet.readSInt32();
}; })()
```

and columns are

```
{ catalog: 'def',
  schema: '',
  name: 'billing_is_pickup_location',
  orgName: '',
  table: '',
  orgTable: '',
  characterSet: 63,
  columnLength: 1,
  columnType: 3,
  flags: 1,
  decimals: 0 }
{ catalog: 'def',
  schema: 'namshi_dev_ae',
  name: 'shipping_address1',
  orgName: 'address1',
  table: 'shipping',
  orgTable: 'sales_order_address',
  characterSet: 33,
  columnLength: 765,
  columnType: 253,
  flags: 4096,
  decimals: 0 }
{ catalog: 'def',
  schema: 'namshi_dev_ae',
  name: 'shipping_fk_pickup_location',
  orgName: 'fk_pickup_location',
  table: 'shipping',
  orgTable: 'sales_order_address',
  characterSet: 63,
  columnLength: 10,
  columnType: 3,
  flags: 0,
  decimals: 0 }
{ catalog: 'def',
  schema: '',
  name: 'billing_is_pickup_location',
  orgName: '',
  table: '',
  orgTable: '',
  characterSet: 63,
  columnLength: 1,
  columnType: 3,
  flags: 1,
  decimals: 0 }
```

Could you show what's result of "SHOW CREATE TABLE" for billing, order, and shipping?

**Comment by sidorares** [comment]
I think I have found a problem.

Field definition is sent two times: one as result to to prepare command and another before execure results. For some reason first is not the same as the second, and we cache and use prepare fields ( if present )

Parser generated from "prepare" data:

```js
(function(){ return function BinaryRow(packet) {
  var statusByte = packet.readInt8();
  var nullBitmaskByte0 = packet.readInt8();
  // "billing_is_pickup_location": LONGLONG
  this["billing_is_pickup_location"] = packet.readSInt64();
  // "shipping_address1": VAR_STRING
  if (nullBitmaskByte0 & 8)
    this["shipping_address1"] = null;
  else
    this["shipping_address1"] = packet.readLengthCodedString();
  // "shipping_fk_pickup_location": LONG
  if (nullBitmaskByte0 & 16)
    this["shipping_fk_pickup_location"] = null;
  else
    this["shipping_fk_pickup_location"] = packet.readSInt32();
  // "billing_is_pickup_location": LONGLONG
  this["billing_is_pickup_location"] = packet.readSInt64();
}; })()
```

And from result fields:

```js
(function(){ return function BinaryRow(packet) {
  var statusByte = packet.readInt8();
  var nullBitmaskByte0 = packet.readInt8();
  // "billing_is_pickup_location": LONG
  this["billing_is_pickup_location"] = packet.readSInt32();
  // "shipping_address1": VAR_STRING
  if (nullBitmaskByte0 & 8)
    this["shipping_address1"] = null;
  else
    this["shipping_address1"] = packet.readLengthCodedString();
  // "shipping_fk_pickup_location": LONG
  if (nullBitmaskByte0 & 16)
    this["shipping_fk_pickup_location"] = null;
  else
    this["shipping_fk_pickup_location"] = packet.readSInt32();
  // "billing_is_pickup_location": LONG
  this["billing_is_pickup_location"] = packet.readSInt32();
}; })()
```

**Comment by sidorares** [comment]
```js
var Packet = require('./lib/packets/packet.js');
var Packets = require('./lib/packets/index.js');


var SAParser = (function(){ return function BinaryRow(packet) {
  var statusByte = packet.readInt8();
  var nullBitmaskByte0 = packet.readInt8();
  // "billing_is_pickup_location": LONG
  this["billing_is_pickup_location"] = packet.readSInt32();
  // "shipping_address1": VAR_STRING
  if (nullBitmaskByte0 & 8)
    this["shipping_address1"] = null;
  else
    this["shipping_address1"] = packet.readLengthCodedString();
  // "shipping_fk_pickup_location": LONG
  if (nullBitmaskByte0 & 16)
    this["shipping_fk_pickup_location"] = null;
  else
    this["shipping_fk_pickup_location"] = packet.readSInt32();
  // "billing_is_pickup_location": LONG
  this["billing_is_pickup_location"] = packet.readSInt32();
}; })()

/*
(function(){ return function BinaryRow(packet) {
   var statusByte = packet.readInt8();
   var nullBitmaskByte0 = packet.readInt8();
   // "billing_is_pickup_location": LONGLONG
   console.log('Null bitmap:', nullBitmaskByte0);
   this["billing_is_pickup_location"] = packet.readSInt64();
   // "shipping_address1": VAR_STRING
   if (nullBitmaskByte0 & 8)
     this["shipping_address1"] = null;
   else
     this["shipping_address1"] = packet.readLengthCodedString();
   // "shipping_fk_pickup_location": LONG
   if (nullBitmaskByte0 & 16)
     this["shipping_fk_pickup_location"] = null;
   else
     this["shipping_fk_pickup_location"] = packet.readSInt32();
   // "billing_is_pickup_location": LONGLONG
   debugger;
   this["billing_is_pickup_location"] = packet.readSInt64();
}; })()
*/

function parse(s) {
  var raw = new Buffer(s, 'hex');
  var p = new Packet(0, raw, 0, raw.end);
  return new SAParser(p);
}

console.log(parse('0010010000001754657374204176656e756520426c64673a34383137333601000000'));
console.log(parse('0010000000001754657374204176656e756520426c64673a35353830333200000000'));
console.log(parse('0010000000001754657374204176656e756520426c64673a36303239373200000000'));
console.log(parse('0010000000001754657374204176656e756520426c64673a36303239373200000000'));
console.log(parse('0000000000001754657374204176656e756520426c64673a3635323034324100000000000000'));
console.log(parse('0000000000001754657374204176656e756520426c64673a3635323034324100000000000000'));
console.log(parse('0000000000001754657374204176656e756520426c64673a3635323034324100000000000000'));
```

prints

```
{ billing_is_pickup_location: 1,
  shipping_address1: 'Test Avenue Bldg:481736',
  shipping_fk_pickup_location: null }
{ billing_is_pickup_location: 0,
  shipping_address1: 'Test Avenue Bldg:558032',
  shipping_fk_pickup_location: null }
{ billing_is_pickup_location: 0,
  shipping_address1: 'Test Avenue Bldg:602972',
  shipping_fk_pickup_location: null }
{ billing_is_pickup_location: 0,
  shipping_address1: 'Test Avenue Bldg:602972',
  shipping_fk_pickup_location: null }
{ billing_is_pickup_location: 0,
  shipping_address1: 'Test Avenue Bldg:652042',
  shipping_fk_pickup_location: 65 }
{ billing_is_pickup_location: 0,
  shipping_address1: 'Test Avenue Bldg:652042',
  shipping_fk_pickup_location: 65 }
{ billing_is_pickup_location: 0,
  shipping_address1: 'Test Avenue Bldg:652042',
  shipping_fk_pickup_location: 65 }
```

**Comment by sidorares** [comment]
if you add `this.statement.columns.length = 0` before [lib/commands/execute.js:L58](https://github.com/sidorares/node-mysql2/blob/master/lib/commands/execute.js#L58) that should force to ignore cached statement fields. Could you try this change and execute query again?

I don't want to completely disable this because it gives noticeable performance improvement ( especially for short results where header data is often bigger than row itself ) but might have no other choice. Would be interesting to contact mysql team and hear from them if that's expected behaviour or known mysql bug

**Comment by sidorares** [comment]
fix published as mysql2@0.15.7 - please try. At the moment decided to completely disable caching of columns.

**Comment by hossam-fares** [comment]
Thats worked for me :+1: 

Thanks @sidorares , really appreciated.

**Comment by sidorares** [comment]
great!
