### ISSUE TITLE
ETIMEDOUT for MySQL Server connection

### ISSUE THREAD

**Issue by dalisoft** [sidorares/node-mysql2#1771]
Fails to connect, even other MySQL Clients works fine (with disable SSL option)

```js
❯ NODE_ENV=development node src/sql/migrations/*.js
Error Error: connect ETIMEDOUT // <-- THIS ERROR
    at Connection._handleTimeoutError (/Users/dalisoft/Desktop/projects/Fudise/itsme-backend/node_modules/mysql2/lib/connection.js:189:17)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7) {
  errorno: 'ETIMEDOUT',
  code: 'ETIMEDOUT',
  syscall: 'connect',
  fatal: true
}
file:///Users/dalisoft/Desktop/projects/Fudise/itsme-backend/src/sql/migrations/admin.js:25
      throw new Error('Migration failed');
      ^

Error: Migration failed
    at Query.onResult (file:///Users/dalisoft/Desktop/projects/Fudise/itsme-backend/src/sql/migrations/admin.js:25:13)
    at Connection._notifyError (/Users/dalisoft/Desktop/projects/Fudise/itsme-backend/node_modules/mysql2/lib/connection.js:228:17)
    at Connection._handleFatalError (/Users/dalisoft/Desktop/projects/Fudise/itsme-backend/node_modules/mysql2/lib/connection.js:167:10)
    at Connection._handleNetworkError (/Users/dalisoft/Desktop/projects/Fudise/itsme-backend/node_modules/mysql2/lib/connection.js:180:10)
    at Connection._handleTimeoutError (/Users/dalisoft/Desktop/projects/Fudise/itsme-backend/node_modules/mysql2/lib/connection.js:193:10)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
itsme-backend on  master [$!] via 🐳 desktop-linux via ⬢ v16.18.1 took 10s 
❯ 
```

## config.js

```js
/* eslint-disable no-console */
import { createConnection } from 'mysql2';

const db = process.env.MYSQL_DATABASE;
const username = process.env.MYSQL_USERNAME;
const password = process.env.MYSQL_PASSWORD;
const host = process.env.MYSQL_HOST;
const port = Number(process.env.MYSQL_PORT || 3306);

const sql = createConnection({
  host,
  user: username,
  password,
  database: db,
  port,
  ssl: { // <-- There does not help
    rejectUnauthorized: false,
    minVersion: 'TLSv1'
  },
  insecureAuth: true // <-- Neither this helps
});

export default sql;
```

**Comment by sidorares** [comment]
can you connect with any other client ( mysql cli / php / etc ) from the same machine using above parameters?

**Comment by dalisoft** [comment]
Datagrip, Sequel Ace works fine from same machine. Only disabled SSL in these apps. As a configured, seems mysql2 does not work this parametr

**Comment by jvalrog** [comment]
Hello, I'm also having this issue while using Mikro-Orm with Mysql driver (that uses mysql2).

The version of mysql2 is 2.3.3.

My config is this:
```
MikroOrmModule.forRootAsync({
      contextName: BandaanchaGGCCToken,
      inject: [ConfigService],
      useFactory: (config: ConfigService<AppConfig>) => ({
        host: config.get('DB_RADIUS_HOST'),
        port: +config.get('DB_RADIUS_PORT'),
        user: config.get('DB_RADIUS_USER'),
        password: config.get('DB_RADIUS_PASSWORD'),
        dbName: config.get('DB_RADIUS_NAME'),
        type: config.get('DB_RADIUS_ADAPTER'),
        debug: config.get('NODE_ENV') !== 'production',
        forceUtcTimezone: true,
        driverOptions: {
          connectTimeout: 60000,
          acquireTimeout: 60000,
        },
        autoLoadEntities: true,
        registerRequestContext: false,
        findOneOrFailHandler: (entityName: string) =>
          new NotFoundException(`${entityName} not found`),
      }),
    }),
```

Both timeout options apparently don't work since the timeout still happens at 10 seconds.
