### ISSUE TITLE
Nextjs 13 support

### ISSUE THREAD

**Issue by Andrew-Gee** [sidorares/node-mysql2#1779]
When I attempt to use mysql2 in a Nextjs 13 server component I get the following error:

```
TypeError: Cannot read properties of undefined (reading 'isServer')
    at new ConnectionConfig (webpack-internal:///(sc_server)/./node_modules/mysql2/lib/connection_config.js:72:33)
    at new PoolConfig (webpack-internal:///(sc_server)/./node_modules/mysql2/lib/pool_config.js:8:33)
    at exports.createPool (webpack-internal:///(sc_server)/./node_modules/mysql2/index.js:18:17)
    at Object.createPool (webpack-internal:///(sc_server)/./node_modules/mysql2/promise.js:341:27)
    at eval (webpack-internal:///(sc_server)/./server/helpers/datahandler.js:7:67)
    at (sc_server)/./server/helpers/datahandler.js (d:\Projects\GsfApp2\.next\server\app\partfinder\page.js:10873:1)
    at __webpack_require__ (d:\Projects\GsfApp2\.next\server\webpack-runtime.js:33:42)
    at eval (webpack-internal:///(sc_server)/./app/partfinder/page.js:7:85)
    at (sc_server)/./app/partfinder/page.js (d:\Projects\GsfApp2\.next\server\app\partfinder\page.js:9642:1)
    at Function.__webpack_require__ (D:\Projects\GsfApp2\.next\server\webpack-runtime.js:33:42) {type: 'TypeError', page: '/partfinder', stack: 'TypeError: Cannot read properties of undefine…sfApp2\.next\server\webpack-runtime.js:33:42)', message: 'Cannot read properties of undefined (reading 'isServer')'}
```

**Comment by Andrew-Gee** [comment]
Nevermind, it was because during build, webpack didn't have a `.env` file to work with. This can be closed.
