### ISSUE TITLE
Query callback is never called (using pool and stream)

### ISSUE THREAD

**Issue by equiet** [sidorares/node-mysql2#182]
Hi,

I am using a pool with a stream option and occasionally (~5% of the time) `connectionPool.query` does not call the callback.

Here's the code:
```js
var nr = require('newrelic');

var express = require('express'),
    app = express(),
    path = require('path'),
    mysql = require('mysql2'),
    url = require('url'),
    SocksConnection = require('socksjs'),
    port = process.env.PORT || 8083,
    proxy = url.parse(process.env.QUOTAGUARDSTATIC_URL);

var connectionPool = mysql.createPool({
    connectionLimit: 10,
    host: process.env.MYSQL_HOST,
    user: process.env.MYSQL_USER,
    password: process.env.MYSQL_PASSWORD,
    database: process.env.MYSQL_DATABASE,
    ssl: 'Amazon RDS',
    stream: new SocksConnection({
        host: process.env.MYSQL_HOST,
        port: 3306
    }, {
        host: proxy.hostname,
        port: 1080,
        user: proxy.auth.split(':')[0],
        pass: proxy.auth.split(':')[1]
    })
});

connectionPool.on('enqueue', function() {
    console.log('Waiting for available MySQL connection slot');
});

app.get('/:id.js', function(req, res) {
    var timeoutDetector = setTimeout(function() {
        console.log('DEBUG: This transaction is taking over 40s', req.params.id);
    }, 40000);

    connectionPool.query('SELECT blabla FROM bla WHERE id = ? AND blabla IS NOT NULL', [req.params.id], nr.createTracer('db:query', function(err, results) {
        clearTimeout(timeoutDetector);

        if (err) {
            console.log(err);
            return;
        }

        res.send('');
    }));
});

app.listen(port);
```

According to New Relic tracer the query never takes more than 100ms. But the timeout detector regularly notifies me the request is taking over 40s (I guess it's safe to assume that callback will never be called at this point).

Sometimes I get this error and 40 seconds later I always get notified the transaction is taking too long (sometimes I don't get this error but still get a notification): 
```
(node) warning: possible EventEmitter memory leak detected. 11 end listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
at addListener (events.js:179:15)
at Readable.on (_stream_readable.js:671:33)
at PoolConnection.Connection (/app/node_modules/mysql2/lib/connection.js:99:15)
at new PoolConnection (/app/node_modules/mysql2/lib/pool_connection.js:10:14)
at Pool.getConnection (/app/node_modules/mysql2/lib/pool.js:39:18)
at Pool.query (/app/node_modules/mysql2/lib/pool.js:128:8)
at /app/server.js:61:20 <-- Where connectionPool.query() is
at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:82:5)
at next (/app/node_modules/express/lib/router/route.js:110:13)
at Route.dispatch (/app/node_modules/express/lib/router/route.js:91:3)
```

One more interesting fact: If I decrease the connectionLimit to 1 I no longer get timeouts or errors.

Any idea what might be causing the issue? Any help would be appreciated.

Thanks

**Comment by PatrikGallik** [comment]
+1

**Comment by sidorares** [comment]
somehow missed that. I'll try to reproduce

**Comment by sidorares** [comment]
@PatrikGallik are you using custom stream as well?
@equiet - note that you can't use stream instance with pool, you need to pass a function which returns stream. Can you change it to a `function() { return new SocksConnection(...) }` ? This might be the cause
