### ISSUE TITLE
Getting a message "Add command: ClientHandshake" & application not working.

### ISSUE THREAD

**Issue by SoummoSinghoRoy** [sidorares/node-mysql2#1827]
**Error is**
```
Add command: ClientHandshake
 raw: 0a382e302e3332002b00000057046926611d0c0b00ffffff0200ffdf15000000000000000000004f2d500b591c611d380968640063616368696e675f736861325f70617373776f726400
Trace
    at PoolConnection.handlePacket (E:\Learn-JS-React\NODE-EXPRESS-JS\Employee-Management-System\node_modules\mysql2\lib\connection.js:458:17)
    at PacketParser.onPacket (E:\Learn-JS-React\NODE-EXPRESS-JS\Employee-Management-System\node_modules\mysql2\lib\connection.js:94:12)
    at PacketParser.executeStart (E:\Learn-JS-React\NODE-EXPRESS-JS\Employee-Management-System\node_modules\mysql2\lib\packet_parser.js:75:16)
    at Socket.<anonymous> (E:\Learn-JS-React\NODE-EXPRESS-JS\Employee-Management-System\node_modules\mysql2\lib\connection.js:101:25)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Readable.push (node:internal/streams/readable:234:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
1 undefined ==> ClientHandshake#unknown name(0,,78)
Server hello packet: capability flags:3758096383=(long password, found rows, long flag, connect with db, no schema, compress, odbc, local files, ignore space, protocol 41, interactive, ssl, ignore sigpipe, transactions, reserved, secure connection, multi statements, multi results, ps multi results, plugin auth, connect attrs, plugin auth lenenc client data, can handle expired passwords, session track, deprecate eof, ssl verify server cert, remember options, multi factor authentication)
Sending handshake packet: flags:279638991=(long password, found rows, long flag, connect with db, odbc, local files, ignore space, protocol 41, ignore sigpipe, transactions, reserved, secure connection, multi results, plugin auth, plugin auth lenenc client data, session track, multi factor authentication)
1 43 <== ClientHandshake#unknown name(1,,111)
1 43 <== 6b000001cff3aa1000000000e00000000000000000000000000000000000000000000000726f6f7400146f662023322f83f58c15e8e24270967c0684b96b656d706c6f7965652d6d616e6167656d656e742d73797374656d006d7973716c5f6e61746976655f70617373776f726400
 raw: fe63616368696e675f736861325f70617373776f72640057046926611d0c0b4f2d500b591c611d3809686400
Trace
    at PoolConnection.handlePacket (E:\Learn-JS-React\NODE-EXPRESS-JS\Employee-Management-System\node_modules\mysql2\lib\connection.js:458:17)
    at PacketParser.onPacket (E:\Learn-JS-React\NODE-EXPRESS-JS\Employee-Management-System\node_modules\mysql2\lib\connection.js:94:12)
    at PacketParser.executeStart (E:\Learn-JS-React\NODE-EXPRESS-JS\Employee-Management-System\node_modules\mysql2\lib\packet_parser.js:75:16)
    at Socket.<anonymous> (E:\Learn-JS-React\NODE-EXPRESS-JS\Employee-Management-System\node_modules\mysql2\lib\connection.js:101:25)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Readable.push (node:internal/streams/readable:234:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
1 43 ==> ClientHandshake#unknown name(2,,48)
1 43 <== ClientHandshake#unknown name(3,,36)
1 43 <== 20000003242064504cd3da5ecf8ed4f60ccd04db31cf3ef79c3caffc6861098da670e191
 raw: 010326000005
Trace
    at PoolConnection.handlePacket (E:\Learn-JS-React\NODE-EXPRESS-JS\Employee-Management-System\node_modules\mysql2\lib\connection.js:458:17)
    at PacketParser.onPacket (E:\Learn-JS-React\NODE-EXPRESS-JS\Employee-Management-System\node_modules\mysql2\lib\connection.js:94:12)
    at PacketParser.executeStart (E:\Learn-JS-React\NODE-EXPRESS-JS\Employee-Management-System\node_modules\mysql2\lib\packet_parser.js:75:16)
    at Socket.<anonymous> (E:\Learn-JS-React\NODE-EXPRESS-JS\Employee-Management-System\node_modules\mysql2\lib\connection.js:101:25)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Readable.push (node:internal/streams/readable:234:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
1 43 ==> ClientHandshake#unknown name(4,,6)
 raw: 00000002400000001d011b1a656d706c6f7965652d6d616e6167656d656e742d73797374656d
Trace
    at PoolConnection.handlePacket (E:\Learn-JS-React\NODE-EXPRESS-JS\Employee-Management-System\node_modules\mysql2\lib\connection.js:458:17)
    at PacketParser.onPacket (E:\Learn-JS-React\NODE-EXPRESS-JS\Employee-Management-System\node_modules\mysql2\lib\connection.js:94:12)
    at PacketParser.executeStart (E:\Learn-JS-React\NODE-EXPRESS-JS\Employee-Management-System\node_modules\mysql2\lib\packet_parser.js:75:16)
    at Socket.<anonymous> (E:\Learn-JS-React\NODE-EXPRESS-JS\Employee-Management-System\node_modules\mysql2\lib\connection.js:101:25)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Readable.push (node:internal/streams/readable:234:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
1 43 ==> ClientHandshake#unknown name(5,maybeOK,42)
Add command: Query
        Sending query command: CREATE TABLE IF NOT EXISTS `sessions` (
  `session_id` varchar(128) COLLATE utf8mb4_bin NOT NULL,
  `expires` int(11) unsigned NOT NULL,
  `data` mediumtext COLLATE utf8mb4_bin,
  PRIMARY KEY (`session_id`)
) ENGINE=InnoDB

1 43 <== Query#unknown name(0,,228)
1 43 <== e000000003435245415445205441424c45204946204e4f5420455849535453206073657373696f6e736020280a20206073657373696f6e5f6964602076617263686172283132382920434f4c4c41544520757466386d62345f62696e204e4f54204e554c4c2c0a202060657870697265736020696e742831312920756e7369676e6564204e4f54204e554c4c2c0a2020606461746160206d656469756d7465787420434f4c4c41544520757466386d62345f62696e2c0a20205052494d415259204b455920286073657373696f6e5f696460290a2920454e47494e453d496e6e6f44420a
Executing (default): SELECT 1+1 AS result
Executing (default): SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_TYPE = 'BASE TABLE' AND TABLE_NAME = 'User' AND TABLE_SCHEMA = 'employee-management-system' Database connected succesfully
Executing (default): SHOW INDEX FROM `User`
Executing (default): SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_TYPE = 'BASE TABLE' AND TABLE_NAME = 'Author_Organization' AND TABLE_SCHEMA = 'employee-management-system'
Executing (default): SHOW INDEX FROM `Author_Organization`
Executing (default): SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_TYPE = 'BASE TABLE' AND TABLE_NAME = 'Department' AND TABLE_SCHEMA = 'employee-management-system'
Executing (default): SHOW INDEX FROM `Department`
Executing (default): SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_TYPE = 'BASE TABLE' AND TABLE_NAME = 'Employee' AND TABLE_SCHEMA = 'employee-management-system'
Executing (default): SHOW INDEX FROM `Employee`
 raw: 00000002000200
Trace
    at PoolConnection.handlePacket (E:\Learn-JS-React\NODE-EXPRESS-JS\Employee-Management-System\node_modules\mysql2\lib\connection.js:458:17)
    at PacketParser.onPacket (E:\Learn-JS-React\NODE-EXPRESS-JS\Employee-Management-System\node_modules\mysql2\lib\connection.js:94:12)
    at PacketParser.executeStart (E:\Learn-JS-React\NODE-EXPRESS-JS\Employee-Management-System\node_modules\mysql2\lib\packet_parser.js:75:16)
    at Socket.<anonymous> (E:\Learn-JS-React\NODE-EXPRESS-JS\Employee-Management-System\node_modules\mysql2\lib\connection.js:101:25)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Readable.push (node:internal/streams/readable:234:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
1 43 ==> Query#unknown name(1,maybeOK,11)
        Resultset header received, expecting 0 column definition packets
Establish db connection
Server is running successfully on port: 4000
```
Behind the scene user, department, sessions, author model/table created but application not responding. 

configuration code :

```
const session = require('express-session');
const MySQLStore = require('express-mysql-session')(session);
const mysql2 = require('mysql2/promise');

const options = {
	host: config.get('db_host'),
	port: config.get('db_port'),
	user: config.get('db_user'),
	password: config.get('db_password'),
	database: config.get('db'),
  debug: true
};

const connection = mysql2.createPool(options);
const sessionStore = new MySQLStore({}, connection, (err) => {
  if(err) {
    console.log(err);
  }
})
```
```
session({
    secret: config.get('secret'),
    resave: false,
    saveUninitialized: false,
    store: sessionStore,
  }),
```
What's wrong happened actually & what's the solution?

**Comment by sidorares** [comment]
logs look ok to me
can you elaborate on `application not working`? Is your server still accepting http connections / printing logs? What is not working - no response from http request or something else?

**Comment by SoummoSinghoRoy** [comment]
Application not responding when i'm trying to start application & getting this message in the log. Application can't handle any get, post request. Actually all middlewares working from a separate file in my application. When i pause middleware portion, application responding. Shall i share middleware file code with you?

**Comment by SoummoSinghoRoy** [comment]
Thanks for your responding. Application working !
