### ISSUE TITLE
Bug / Feedback: `host:localhost` causes `mysql2` to use `socketPath`

### ISSUE THREAD

**Issue by cliffordfajardo** [sidorares/node-mysql2#1840]
### Background Context
I was setting up `mysql2` for the first time and trying to connect to the mysql server installed on my mac.
I had trouble connecting to the database and getting a `ECONNREFUSED` error.

### What is the Issue / Challenge?
1. When using `host:localhost`, it appears that it using `localhost` as the host value causes `mysql2` to think we want to connect to our mysql database via unix sockets, instead of TCP/IP & this isn't clear to the user

2. If we use `host:'127.0.0.1'` mysql2 package assumes we want to use TCP/IP

### Using `host: 'localhost'`
```ts
import mysql from 'mysql2/promise'

const connection = await mysql.createConnection({
    host: 'localhost',
    user: 'root',
    password: 'password',
    port: 3306,
    database: 'mydatabase',
    // socketPath: '/tmp/mysql.sock' ❌ without this uncommented, we will get an error
});

const results = await connection.query('SELECT * FROM users')
console.log(`results`, results[0])
connection.end();
```
will cause the following error:

```
Error: connect ECONNREFUSED ::1:3306
    at Object.createConnection (/Users/cfajardo/Downloads/sdi-infra-fe/sdi-infra-fe/node_modules/mysql2/promise.js:252:31)
    at file:///Users/cfajardo/Downloads/sdi-infra-fe/sdi-infra-fe/scripts/setup-mysql.mjs:4:32
    at ModuleJob.run (node:internal/modules/esm/module_job:198:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:409:24)
    at async loadESM (node:internal/process/esm_loader:85:5)
    at async handleMainPromise (node:internal/modules/run_main:61:12) {
  code: 'ECONNREFUSED',
  errno: -61,
  sqlState: undefined
}
```

however, if we enabled `socketPath` it will work. 

### Using `host: '127.0.0.1',` works fine
```ts
import mysql from 'mysql2/promise'

const connection = await mysql.createConnection({
    host: '127.0.0.1',
    user: 'root',
    password: 'password',
    port: 3306,
    database: 'mydatabase',
});

const results = await connection.query('SELECT * FROM users')
console.log(`results`, results[0])
connection.end();
```

### References
- [Connect to MySQL with unix sockets﻿](https://www.jetbrains.com/help/datagrip/how-to-connect-to-mysql-with-unix-sockets.html)

**Comment by sidorares** [comment]
might be related: https://github.com/sidorares/node-mysql2/issues/1668#issuecomment-1312853352

**Comment by sidorares** [comment]
> if I didn't pass socketPath to createClient, why did mysql2 assume I wanted to use socketPath?

@cliffordfajardo what makes you think it tries to use socketPath?

What likely happens: 
- your mysql server only listens on ipv4 interface
- `localhost:3306` is resolved to `::1:3306`, and there is no server at this ip address/port
- your server also listens on a unix domain socket, connection to a socket path works as expected

What can be improved:

- we might error ( or just warn) if there is a mix of host + port + socketPath. Currently socketPath takes a precedence is specified, then host/port ( but they default to `localhost:3306` )
- maybe try to guess from the error `connect ECONNREFUSED ::1:3306` a possible solution ( "check your server is actually listening on ipv6 if this is what you want to connect, or change host to '127.0.0.1' if you want to use ipv4" ) and suggest it in the error message
