### ISSUE TITLE
Sporadically getting EventEmitter memory leak warning when using LOAD INFILE with stream

### ISSUE THREAD

**Issue by abellina** [sidorares/node-mysql2#186]
I am calling connection.query ({sql: sql, infileStreamFactory: function (){ return stream; }}) many times over the life of a connection. Each time, stream is a different object. However, I see that the warning is happening when _streamLocalInfile in query.js is attaching an event listener to connection.stream. 

Perhaps there should be calls to removeListener on the connection.stream object once the localStream has ended?

Thanks

Alessandro

(node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at Socket.addListener (events.js:160:15)
    at Query._streamLocalInfile (node_modules/mysql2/lib/commands/query.js:122:21)
    at Query.resultsetHeader (node_modules/mysql2/lib/commands/query.js:99:10)
    at Query.Command.execute (node_modules/mysql2/lib/commands/command.js:34:20)
    at Connection.handlePacket (node_modules/mysql2/lib/connection.js:310:28)
    at PacketParser.onPacket (node_modules/mysql2/lib/connection.js:83:65)
    at PacketParser.executeStart (node_modules/mysql2/lib/packet_parser.js:39:12)
    at Socket.<anonymous> (node_modules/mysql2/lib/connection.js:95:31)
    at Socket.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:764:14)

**Comment by sidorares** [comment]
Interesting. Would it be possible to reduce to a minimal test I could reproduce on my side?
