### ISSUE TITLE
named placeholders can cause exception

### ISSUE THREAD

**Issue by abellina** [sidorares/node-mysql2#187]
Hello

I am getting an issue where named placeholder resolution can cause exceptions, say if you use a column that doesn't exist in the table (misspelled). However, regular query calls with ? placeholders usually return errors as a parameter in the .query callback.

Any reason to favor exceptions in the named placeholder case?

Thanks

Alessandro

**Comment by sidorares** [comment]
Hi! No reason, I'd prefer to have similar error flow. Placeholder resolution needs to be wrapped in try/catch. ( Feel free to submit PR, this is relatively easy to fix )

**Comment by cheshirecatalyst** [comment]
This issue would be related to this error I get on prepared statements with named placeholders correct:
```
TypeError: Cannot read property 'toString' of undefined
    at Execute.toPacket (/Users/emris/hq/AvailabilityToOffer/development/calculate-offer/node_modules/hqmysql/node_modules/mysql2/lib/packets/execute.js:44:39)
    at Execute.start (/Users/emris/hq/AvailabilityToOffer/development/calculate-offer/node_modules/hqmysql/node_modules/mysql2/lib/commands/execute.js:44:40)
    at Execute.Command.execute (/Users/emris/hq/AvailabilityToOffer/development/calculate-offer/node_modules/hqmysql/node_modules/mysql2/lib/commands/command.js:34:20)
    at PoolConnection.Connection.handlePacket (/Users/emris/hq/AvailabilityToOffer/development/calculate-offer/node_modules/hqmysql/node_modules/mysql2/lib/connection.js:310:28)
    at PoolConnection.Connection.addCommand (/Users/emris/hq/AvailabilityToOffer/development/calculate-offer/node_modules/hqmysql/node_modules/mysql2/lib/connection.js:326:10)
    at Prepare.executeStatement [as onResult] (/Users/emris/hq/AvailabilityToOffer/development/calculate-offer/node_modules/hqmysql/node_modules/mysql2/lib/connection.js:492:18)
    at /Users/emris/hq/AvailabilityToOffer/development/calculate-offer/node_modules/hqmysql/node_modules/mysql2/lib/commands/prepare.js:98:12
    at doNTCallback0 (node.js:408:9)
    at process._tickCallback (node.js:337:13)
```

Which is a very unhelpful error ^_^ as there is no way to trace it back to which query is causing it
