### ISSUE TITLE
"Error: Unkonown Error" connecting to a MariaDB Galera cluster

### ISSUE THREAD

**Issue by dylanvdbrink** [sidorares/node-mysql2#1880]
Hi,

We're using mysql2 indirectly by using TypeORM in our NestJS project. When connecting to our company's managed MariaDB Galera cluster we are seeing the following error: `Error: Unkonown Error`. Which I remembered because of the spelling mistake and was also seeing in some Web technology based database tooling (e.g. Beekeeper Studio).

Seeing the stacktrace and the dependencies of both TypeORM and Beekeeper Studio I saw that it's using the node-mysql2 package. So I put the following code in a javascript file and tested that out:

```javascript
const mysql = require('mysql2');

const connection = mysql.createConnection({
  host: 'REDACTED',
  user: 'REDACTED',
  password: 'REDACTED',
  database: 'REDACTED',
  port: REDACTED,
  debug: true,
  trace: true
});

connection.query(
  'SELECT VERSION() AS `version`',
  function(err, results, fields) {
    console.log(err);
    console.log(results);
    console.log(fields);
  }
);
```

And this simple example is already returning the same error:

```bash
➜  mysql2-test node index.js

Add command: ClientHandshake
Add command: Query
 raw: 0a352e302e37372d6e7300dda50300373b2767376f326a008da20802000000000000000000000000000027637b276469662f6178616a00
Trace
    at Connection.handlePacket (REDACTED/mysql2-test/node_modules/mysql2/lib/connection.js:446:17)
    at PacketParser.onPacket (REDACTED/mysql2-test/node_modules/mysql2/lib/connection.js:94:12)
    at PacketParser.executeStart (REDACTED/mysql2-test/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.<anonymous> (REDACTED/mysql2-test/node_modules/mysql2/lib/connection.js:101:25)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Readable.push (node:internal/streams/readable:234:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
0 undefined ==> ClientHandshake#unknown name(0,,59)
Server hello packet: capability flags:41613=(long password, long flag, connect with db, local files, protocol 41, transactions, secure connection)
Sending handshake packet: flags:12252111=(long password, found rows, long flag, connect with db, odbc, local files, ignore space, protocol 41, ignore sigpipe, transactions, reserved, secure connection, multi results, plugin auth, connect attrs, plugin auth lenenc client data, session track)
0 239069 <== ClientHandshake#unknown name(1,,149)
0 239069 <== 91000001cff3ba0000000000e000000000000000000000000000000000000000000000005254494d5f54455354310014d88c6049b0ee7a6b7853994fa8ac1282a464d2a54d5943525434303154006d7973716c5f6e61746976655f70617373776f726400300c5f636c69656e745f6e616d650c4e6f64652d4d7953514c2d320f5f636c69656e745f76657273696f6e05332e322e30
 raw: ff5104234859303030556e6b6f6e6f776e204572726f7200
Trace
    at Connection.handlePacket (REDACTED/mysql2-test/node_modules/mysql2/lib/connection.js:446:17)
    at PacketParser.onPacket (REDACTED/mysql2-test/node_modules/mysql2/lib/connection.js:94:12)
    at PacketParser.executeStart (REDACTED/mysql2-test/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.<anonymous> (REDACTED/mysql2-test/node_modules/mysql2/lib/connection.js:101:25)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Readable.push (node:internal/streams/readable:234:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
0 239069 ==> ClientHandshake#unknown name(2,Error,28)
Error: Unkonown Error
    at Packet.asError (REDACTED/mysql2-test/node_modules/mysql2/lib/packets/packet.js:728:17)
    at ClientHandshake.execute (REDACTED/mysql2-test/node_modules/mysql2/lib/commands/command.js:29:26)
    at Connection.handlePacket (REDACTED/mysql2-test/node_modules/mysql2/lib/connection.js:489:32)
    at PacketParser.onPacket (REDACTED/mysql2-test/node_modules/mysql2/lib/connection.js:94:12)
    at PacketParser.executeStart (REDACTED/mysql2-test/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.<anonymous> (REDACTED/mysql2-test/node_modules/mysql2/lib/connection.js:101:25)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Readable.push (node:internal/streams/readable:234:10) {
  code: 'ER_UNKNOWN_ERROR',
  errno: 1105,
  sqlState: 'HY000',
  sqlMessage: 'Unkonown Error\x00',
  sql: undefined
}
```

So the problem is most likely the database/server but I am having a hard time figuring out what pointers I can pass through to our database team as to what they need to change/fix.

------

## Environment
Server version: 10.5.19-MariaDB
mysql2 version: 3.2.0
Node version: 18.13.0

**Comment by sidorares** [comment]
hm, looks like the error is actually coming from the server so not sure how can I help on a driver side. Do you have access to server logs?

**Comment by dylanvdbrink** [comment]
Yeah seems to me that the server is sending some packet as part of the handshake that the client does not understand or something?

No direct access, but I will ask for the logs and report back, thanks for your quick reply!

**Comment by sidorares** [comment]
> is sending some packet as part of the handshake that the client does not understand or something?
There might be some problem with the handshake, but the last packet is literally error packet, not something that the client can't parse

https://dev.mysql.com/doc/dev/mysql-server/latest/page_protocol_basic_err_packet.html

The raw data is `ff5104234859303030556e6b6f6e6f776e204572726f7200`

ff - "it's an error packet"
5104 - 2 bytes of the error code
0x23 - "#" symbol, marker of the SQL state
4859303030 - "HY000", sql state
556e6b6f6e6f776e204572726f7200 - "Unkonown Error" - human readable error message.

Maybe worth searching MariaDB or Galera code for that Unkonown Error" string

**Comment by dylanvdbrink** [comment]
We've tried to directly connect to one of the nodes behind the loadbalancer and that does work so the problem is most likely that. I will close this. Thanks for the help and pointers!
