### ISSUE TITLE
caught TypeError: Buffer.allocUnsafe is not a function  

### ISSUE THREAD

**Issue by Evgvakh** [sidorares/node-mysql2#2006]
Pls help!

Having a problem with dependency with Buffer while using webpack 5>.

Any ideas?

**Comment by sidorares** [comment]
can you make a simple repro? We used to have a https://www.npmjs.com/package/safe-buffer shim but since all supported node versions have `Buffer.allocUnsafe` now the shim is no longer in use

**Comment by Evgvakh** [comment]
Even upgraded a node till latest... No result. A simple line `import mysql from 'mysql2'` gives an error:

caught TypeError: Buffer.allocUnsafe is not a function
    at eval (query.js:14:50)
    at ./node_modules/mysql2/lib/commands/query.js (bundle.c0e3b059e582ac666af1.js:1744:1)
    at __webpack_require__ (bundle.c0e3b059e582ac666af1.js:4281:33)
    at fn (bundle.c0e3b059e582ac666af1.js:4492:21)
    at eval (webpack://sf_oopapp/./node_modules/mysql2/lib/commands/index.js?:5:15)
    at ./node_modules/mysql2/lib/commands/index.js (bundle.c0e3b059e582ac666af1.js:1711:1)
    at __webpack_require__ (bundle.c0e3b059e582ac666af1.js:4281:33)
    at fn (bundle.c0e3b059e582ac666af1.js:4492:21)
    at eval (webpack://sf_oopapp/./node_modules/mysql2/lib/connection.js?:30:18)
    at ./node_modules/mysql2/lib/connection.js (bundle.c0e3b059e582ac666af1.js:1799:1)

Once installed mysql2 had a problems with polyfills. Added it to webpack as errors hints told. 

```
resolve: {
    fallback: {
      crypto: require.resolve("crypto-browserify"),
      stream: require.resolve("stream-browserify"),
      util: require.resolve("util/"),
      buffer: require.resolve("buffer/"),
      process: require.resolve("process/browser"),
      url: require.resolve("url/"),
      timers: require.resolve("timers-browserify"),
      zlib: require.resolve("browserify-zlib"),
      assert: require.resolve("assert/"),
    },
  },
```

Had this problem also with process, solved with:

```
new webpack.ProvidePlugin({
      process: "process/browser",      
}),
```
