### ISSUE TITLE
URGENT -- Error: Can't add new command when connection is in closed state 

### ISSUE THREAD

**Issue by TadasV1** [sidorares/node-mysql2#2152]
I keep getting this message everyday and need to restart server to get rid of it.

ERROR message:
```
Error: Can't add new command when connection is in closed state
  at PromisePoolConnection.rollback (/workspace/node_modules/mysql2/promise.js:154:22)
  at default (file:///workspace/build/server/chunks/3-631dc144.js:71:18)
  at runMicrotasks (<anonymous>)
  at processTicksAndRejections (node:internal/process/task_queues:96:5)
  at async handle_action_json_request (file:///workspace/build/server/index.js:1673:18)
  at async resolve (file:///workspace/build/server/index.js:3887:24)
  at async Object.handle (file:///workspace/build/server/chunks/hooks.server-9f81dc2e.js:27:12)
  at async respond (file:///workspace/build/server/index.js:3773:22)
  at async Array.ssr (file:///workspace/build/handler.js:1221:3) {
code: undefined,
errno: undefined,
sql: undefined,
sqlState: undefined,
sqlMessage: undefined
```

//pool.js
```
import mysql  from 'mysql2'

// Create the connection pool. The pool-specific settings are the defaults
const pool = await mysql.createPool({
  host: 'localhost',
  user: 'root',
  database: 'test',
  waitForConnections: true,
  connectionLimit: 10,
  maxIdle: 10, // max idle connections, the default value is the same as `connectionLimit`
  idleTimeout: 60000, // idle connections timeout, in milliseconds, the default value 60000
  });
```

//foobar.js
```
...
const [rows] = await pool.query('SELECT * FROM sales')
return rows;
```

//connection.js
```
import { pool } from './pool.js'

const connection = await pool.getConnection();

export {
  connection 
}
```

connections used for transactions - connection.beginTransaction() etc

**Comment by TadasV1** [comment]
It appears I missed these:
queueLimit: 0,
enableKeepAlive: true,
keepAliveInitialDelay: 0

Error occurs when mysql closes connection due to wait_timeout. And you need these configs to keep it alive.
