### ISSUE TITLE
mysql2/promise not working 

### ISSUE THREAD

**Issue by harryinnotech** [sidorares/node-mysql2#2202]
I followed a tutorial on YouTube to set up my Windows computer for web development, everything was working fine but when it came to connecting my app.js file to MySQL  database it did not work but instead giving me SyntaxError: Unexpected token ; , please help. bellow is the code.

const mysql = require('mysql2/promise');

// create a new MySQL connection
const connection = mysql.createConnection({
  host: 'localhost',
  port: 3306,
  user: 'root',
  password: 'example',
  database: 'pets'
});
// connect to the MySQL database
connection.connect((error) => {
  if (error) {
    console.error('Error connecting to MySQL database:', error);
  } else {
    console.log('Connected to MySQL database!');
  }
});

// close the MySQL connection
connection.end();

➜  third-project node app.js
/home/harry/harryinnotech/third-project/node_modules/lru-cache/dist/cjs/index.js:51
    heap;
        ^

SyntaxError: Unexpected token ;
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/harry/harryinnotech/third-project/node_modules/lru-cache/dist/cjs/index-cjs.js:5:36)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
➜  third-project

**Comment by wellwelwel** [comment]
Hi @harryinnotech, when you use the `mysql2/promise`, you have to change from callbacks to promise-based. It should be something like:

```js
const mysql = require('mysql2/promise');

// create a new MySQL connection
const connection = await mysql.createConnection({
  host: 'localhost',
  port: 3306,
  user: 'root',
  password: 'example',
  database: 'pets',
});

try {
  // connect to the MySQL database
  await connection.connect();
  console.log('Connected to MySQL database!');
} catch (error) {
  console.error('Error connecting to MySQL database:', error);
}

// close the MySQL connection
connection.end();

```
