### ISSUE TITLE
exception on client disconnect

### ISSUE THREAD

**Issue by pilosof** [sidorares/node-mysql2#232]
when implementing a server and the client disconnects I get: 

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: Connection lost: The server closed the connection.
    at Socket.<anonymous> (/node_modules/mysql2/lib/connection.js:107:15)
    at Socket.EventEmitter.emit (events.js:117:20)
    at _stream_readable.js:910:16
    at process._tickCallback (node.js:415:13)

**Comment by sidorares** [comment]
Hi,

yes, You need to add something like this:

```
// server code
conn.on('error', function(err) {
   // do something - if you keep track of all connections mark it as disconnected, remove from list, deallocate resources associated with connection etc etc
});

// rest of server code ...
conn.on('query', function(query) {
    conn.writeColumns([{
      catalog: 'def',
      schema: 'test',
      table: 'test_table',
      orgTable: 'test_table',
      name: 'beta',
      orgName: 'beta',
      characterSet: 33,
      columnLength: 384,
      columnType: 253,
      flags: 0,
      decimals: 0
    }]);
    conn.writeTextRow(['test тест テスト փորձարկում পরীক্ষা kiểm tra ']);
    conn.writeTextRow(['ტესტი પરીક્ષણ  מבחן פּרובירן اختبار परीक्षण']);
    conn.writeEof();
    conn.close();
  });

```

Server-side connection is same object as client-side connection, and because of [this](https://github.com/sidorares/node-mysql2/blob/master/lib/connection.js#L150-L167) code and because 'error' event is special for EventEmitter if no handler exist it causes exception.

I probably need to update examples/documentation

**Comment by pilosof** [comment]
Thanks! another thing try selecting unset variable:
select @bla;

buffer.js:434
      throw new TypeError('Unknown encoding: ' + encoding);
            ^
TypeError: Unknown encoding: 10
    at Buffer.toString (buffer.js:434:13)
    at mysql2/lib/packets/text_row.js:23:19
    at Array.forEach (native)
    at Function.TextRow.toPacket (mysql2/lib/packets/text_row.js:21:10)
    at Connection.writeTextRow (mysql2/lib/connection.js:623:36)
    at mysql2/lib/connection.js:634:16
    at Array.forEach (native)
    at Connection.writeTextResult (mysql2/lib/connection.js:629:8)

**Comment by pilosof** [comment]
also:
proxying query:SET NAMES utf8
Unknown command: 27

**Comment by sidorares** [comment]
27 is `SET_OPTION` command - https://github.com/sidorares/node-mysql2/blob/master/lib/constants/commands.js#L29

**Comment by sidorares** [comment]
you are right, need to fix NULL string serialisation ( one byte, `0xfb` )

**Comment by sidorares** [comment]
de-serialization: https://github.com/sidorares/node-mysql2/blob/master/lib/packets/packet.js#L265-L272
