### ISSUE TITLE
How to resolve "mysql Proxy Warning - Syntax Forbidden prepare"?

### ISSUE THREAD

**Issue by Q5EbA7Vdyw84efER** [sidorares/node-mysql2#2536]
I'm using Nextjs framework, and wrote my code as a function as below

```js
const con = await getConnection()
try {
  await con.execute(`UPDATE tool set category_id=?,name=?,description=?,url=?,draw_content=? where id=?`, [category_id, name, description, url, draw_content, id])
} catch (error) {
  throw error
}
```

Everything is OK in test environment, but in our company's production MYSQL environment, it didn't work and output such log error

_Error: Proxy Warning - Syntax Forbidden Prepare:UPDATE tool set category_id=?,name=?,description=?,url=?,draw_content=? where id=?
    at u.execute (/.next/server/chunks/572.js:10:55409)
    at g (/.next/server/chunks/764.js:1:7427)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:16:406
    at async rm (/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:15:6342)
    at async rq (/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:18:1249)
    at async doRender (/node_modules/next/dist/server/base-server.js:1376:30)
    at async cacheEntry.responseCache.get.routeKind (/node_modules/next/dist/server/base-server.js:1537:28)
    at async NextNodeServer.renderToResponseWithComponentsImpl (/node_modules/next/dist/server/base-server.js:1445:28)
    at async NextNodeServer.renderPageComponent (/node_modules/next/dist/server/base-server.js:1842:24) {
  code: 'ER_UNKNOWN_ERROR',
  errno: 1105,
  sql: 'UPDATE tool set category_id=?,name=?,description=?,url=?,draw_content=? where id=?',
  sqlState: '07000',
  sqlMessage: 'Proxy Warning - Syntax Forbidden Prepare:UPDATE tool set category_id=?,name=?,description=?,url=?,draw_content=? where id=?'_

<img width="749" alt="_17114587486581" src="https://github.com/sidorares/node-mysql2/assets/529252/b77c7ae8-a6b1-4c51-adc6-8a3669c94f33">

**Comment by wellwelwel** [comment]
Closing due to:

- #2538
