### ISSUE TITLE
Read ECONNRESET after a few minutes idle

### ISSUE THREAD

**Issue by lijyze** [sidorares/node-mysql2#2794]
It happens every first time my app interactive with database after a few minutes idle.
I downgrade `mysql2` to version `v3.3.1`, it seems work well.
So I want to know if I need some additional config when use `v3.10.1`

Here is error log

```
QueryFailedError: read ECONNRESET
    at Query.onResult (F:\workspace\project\server\src\driver\mysql\MysqlQueryRunner.ts:246:33)
    at PoolConnection._notifyError (F:\workspace\project\server\node_modules\mysql2\lib\connection.js:228:21) 
    at PoolConnection._handleFatalError (F:\workspace\project\server\node_modules\mysql2\lib\connection.js:183:10)
    at PoolConnection._handleNetworkError (F:\workspace\project\server\node_modules\mysql2\lib\connection.js:196:10)
    at Socket.emit (node:events:519:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at processTicksAndRejections (node:internal/process/task_queues:82:21) {
  query: 'SELECT `Admin`.`id` AS `Admin_id`, `Admin`.`adminName` AS `Admin_adminName`, `Admin`.`password` AS `Admin_password` FROM `admin` `Admin` WHERE ((`Admin`.`adminName` = ?)) LIMIT 1',
  parameters: [ 'lijyze' ],
  driverError: Error: read ECONNRESET
      at TCP.onStreamRead (node:internal/stream_base_commons:218:20) {
    errno: -4077,
    code: 'ECONNRESET',
    syscall: 'read',
    fatal: true
  },
  errno: -4077,
  code: 'ECONNRESET',
  syscall: 'read',
  fatal: true
}
```

I have read #2599 but still feel confused.
Any help would be appreciate！

**Comment by lijyze** [comment]
Seems `keepAliveInitialDelay` cause this error, I have to pass a param to this config, and if I pass a small number, like `keepAliveInitialDelay: 1`, I also encounter this error. set it to `10000` seems work well.

Any explain about this?

**Comment by kachurun** [comment]
I've got the same problem after updating from v2 to v3.11.0. It appears exactly 1 hour after the Node.js server starts.

**Comment by wikkard** [comment]
I have the same problem have tried lots of solutions. destroying the connections, creating a new pool after several failures, testing connections before using them and destroying them if they are bad. But still after around 30 mins of inactivity the pool will return bad connections. I have resorted to a cronjob to constantly trigger activity on my server so I can try to avoid it, but this is a major headache. Is there any good solution? (using RDS, node 22.

**Comment by sharifzadesina** [comment]
Same problem.
