### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by shramabablukumar** [sidorares/node-mysql2#2961]
C:\Users\sharm\Desktop\SQL\index.js:13
      if (error) throw error;
                 ^

Error: Duplicate entry '123' for key 'user.PRIMARY'
    at Packet.asError (C:\Users\sharm\Desktop\SQL\node_modules\mysql2\lib\packets\packet.js:738:17)
    at Query.execute (C:\Users\sharm\Desktop\SQL\node_modules\mysql2\lib\commands\command.js:29:26)
    at Connection.handlePacket (C:\Users\sharm\Desktop\SQL\node_modules\mysql2\lib\connection.js:481:34)
    at PacketParser.onPacket (C:\Users\sharm\Desktop\SQL\node_modules\mysql2\lib\connection.js:97:12)
    at PacketParser.executeStart (C:\Users\sharm\Desktop\SQL\node_modules\mysql2\lib\packet_parser.js:75:16)
    at Socket.<anonymous> (C:\Users\sharm\Desktop\SQL\node_modules\mysql2\lib\connection.js:104:25)
    at Socket.emit (node:events:519:28)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
    at Readable.push (node:internal/streams/readable:390:5) {
  code: 'ER_DUP_ENTRY',
  errno: 1062,
  sqlState: '23000',
  sqlMessage: "Duplicate entry '123' for key 'user.PRIMARY'",
  sql: "INSERT INTO user (id, username, email, password) VALUES ('123', '123_username', 'sharma@gmail.com', 'abc')",
  fatal: true
}

Node.js v20.16.0
PS C:\Users\sharm\Desktop\SQL>

**Comment by shramabablukumar** [comment]
how to slove this error

**Comment by rkgupta12** [comment]
looks like the insert statement is tryig to add a row with same value in id again and this is primary key to its not possible.

**Comment by wellwelwel** [comment]
Hi, @shramabablukumar.

When writing to a column that uses `PRIMARY KEY` or `UNIQUE`, you need to ensure unique data or [update it if the column already exists](https://dev.mysql.com/doc/refman/8.4/en/insert-on-duplicate.html) 🙋🏻‍♂️
