### ISSUE TITLE
Error stack trace when connecting

### ISSUE THREAD

**Issue by andreassolberg** [sidorares/node-mysql2#333]
Testing with `1.0.0-rc.6`. Throwing the error below.

```
TypeError: Cannot set property parent of [object Object] which has only a getter
    at Function.Packet.MockBuffer (/Users/andreas/wc/kube/appengine/node_modules/mysql2/lib/packets/packet.js:687:13)
    at HandshakeResponse.toPacket (/Users/andreas/wc/kube/appengine/node_modules/mysql2/lib/packets/handshake_response.js:125:41)
    at ClientHandshake.sendCredentials (/Users/andreas/wc/kube/appengine/node_modules/mysql2/lib/commands/client_handshake.js:51:44)
    at ClientHandshake.handshakeInit (/Users/andreas/wc/kube/appengine/node_modules/mysql2/lib/commands/client_handshake.js:113:10)
    at ClientHandshake.Command.execute (/Users/andreas/wc/kube/appengine/node_modules/mysql2/lib/commands/command.js:38:20)
    at PoolConnection.Connection.handlePacket (/Users/andreas/wc/kube/appengine/node_modules/mysql2/lib/connection.js:263:28)
    at PacketParser.onPacket (/Users/andreas/wc/kube/appengine/node_modules/mysql2/lib/connection.js:95:66)
    at PacketParser.executeStart (/Users/andreas/wc/kube/appengine/node_modules/mysql2/lib/packet_parser.js:44:12)
    at Socket.<anonymous> (/Users/andreas/wc/kube/appengine/node_modules/mysql2/lib/connection.js:97:29)
    at emitOne (events.js:77:13)
```

When reverted to  `1.0.0-rc.5` I got an error  (no exception track trace) about no access. Turned out I did not provide a password.

**Comment by sidorares** [comment]
thanks @andreassolberg 

what's node version you are using? I can't reproduce issue my test matrix, but hope that https://github.com/sidorares/node-mysql2/commit/3b279f66521d17f87bf5761d5a67165bd799c4f4 might fix the problem

**Comment by sidorares** [comment]
would yo be able to try tip of https://github.com/sidorares/node-mysql2/tree/issue-333 branch?
