### ISSUE TITLE
notify all commands in the queue when connection is forcibly closed

### ISSUE THREAD

**Issue by sidorares** [sidorares/node-mysql2#378]
I think [here](https://github.com/sidorares/node-mysql2/blob/b2010f99180d8b49eb7e9c2b6aeb8cb441362835/lib/pool_connection.js#L17-L21)

We need to iterate connection queue first and call callback with error ( using `Connection.prototype._notifyError` )

**Comment by lillem4n** [comment]
Maybe related, I am researching a way to gracefully handle connection lost events in my application:

stack=[
	Error: Connection lost: The server closed the connection.,
		at Socket.<anonymous> (/foo/bar/node_modules/larvitdbmigration/node_modules/mysql2/lib/connection.js:96:35),
		at emitNone (events.js:72:20),     
		at Socket.emit (events.js:166:7),     
		at endReadableNT (_stream_readable.js:913:12),     
		at nextTickCallbackWith2Args (node.js:442:9),     
		at process._tickDomainCallback (node.js:397:17)
]

Right now I'll have to wrap the whole mysql2 business in a try/catch and that does not feel good. I still have to come up with a good automated test to trigger this.
