### ISSUE TITLE
Error in connecting to a proxy address for a Heroku add-on

### ISSUE THREAD

**Issue by mm-wang** [sidorares/node-mysql2#414]
Hello,

I am looking to try to connect to a SQL database via a Heroku app, but the database restricts IP addresses, and due to the nature of Heroku's reliance on an EC2 instance with changing IP addresses, I need to use a proxy. I looked through the comments on [this issue](https://github.com/mysqljs/mysql/issues/725) in mysql, and I used the configuration in one of the last comments. I'm repeating it here, but it was originally posted by @pierrickchabi 2 years ago:

```
var mysql2 = require('mysql2');
var url = require("url");
var SocksConnection = require('socksjs');

var mysql_server_options = {
  host: 'database.ho.st',
  port: 3306
};

var socks_options = {
  host: 'proxy.ho.st',
  port: 1080,
  user: 'proxy_username',
  pass: 'proxy_password'
};

var socksConn = new SocksConnection(mysql_server_options, socks_options);

var mysql_options =  {
  database: 'db_name',
  user: 'db_username',
  password: 'secret',
  stream: socksConn
}

var mysqlConn = mysql2.createConnection(mysql_options);

mysqlConn.query('SELECT 1+1 as test1;', function(err, rows, fields) {
  if (err) throw err;

  console.log('Result: ', rows);

  socksConn.dispose();
  mysqlConn.end();
});
```

However, the error I get is: 
```
TypeError: this.stream.destroy is not a function
at Connection._handleTimeoutError (/app/node_mudules/mysql2/lib/connection.js:164:17)
at tryOnTimeout (timers.js:224:198:5)
at Timer.listOnTimeout (timers.js:198:5)
...
```

I am not sure what the issue is, but it seems as if the connection is timing out. Any thoughts or help you can provide?

**Comment by sidorares** [comment]
Looks like a side effect of #396

Can you try with really big `connectTimeout` value @mm-wang ?

@sushantdhiman - I think we should not use `this.stream.destroy()` - we need only assume DuplexStream interface for `connection.stream` ( maybe have special case for Net.Stream if it helps to cleanup immediately at this point )

**Comment by mm-wang** [comment]
With a big connectTimeout, I get an ECONNREFUSED error like so:

```
2016-09-26T14:51:21.466380+00:00 app[web.1]: ERROR:  { [Error: connect ECONNREFU
SED i.p.add.ress:3306]
2016-09-26T14:51:21.466382+00:00 app[web.1]:   code: 'ECONNREFUSED',
2016-09-26T14:51:21.466383+00:00 app[web.1]:   errno: 'ECONNREFUSED',
2016-09-26T14:51:21.466384+00:00 app[web.1]:   syscall: 'connect',
2016-09-26T14:51:21.466384+00:00 app[web.1]:   address: 'i.p.add.ress',
2016-09-26T14:51:21.466385+00:00 app[web.1]:   port: 3306,
2016-09-26T14:51:21.466386+00:00 app[web.1]:   fatal: true }

2016-09-26T14:51:49.916645+00:00 app[web.1]: ERROR:  { [Error: Cannot enqueue Qu
ery after fatal error.] code: 'PROTOCOL_ENQUEUE_AFTER_FATAL_ERROR', fatal: false
 }
```

**Comment by mm-wang** [comment]
With a connectTimeout of 100,000 ms, I get:

```
Error: Connection lost: The server closed the connection.
at null.<anonymous>(/app/node_modules/mysql2/lib/connection.js:104:35
at emitNone (events.js:85:20)
at emit (events.js:179:7)
at endRedableNT (_stream_readable.js:913:12)
at _combinedTickCallback (internal/process/next_tick.js:74:11)
at process._tickDomainCallback (internal/process/next_tick.js:122:9)
Process exited with status 1
State changed from up to crashed
```

**Comment by sidorares** [comment]
Could you try to set `debug` flag to true and post logs @mm-wang?
I'm not sure if the problem is in mysql client side ( not proceeding to commands if the underlying stream is non-native tcp? ) or it's the credentials configured incorrectly on server  for user/pass/db/ip used

**Comment by mm-wang** [comment]
The log is below, slightly anonymized.

```
2016-09-27T14:17:49.383049+00:00 app[web.1]:   stream:
2016-09-27T14:17:49.383049+00:00 app[web.1]:    Duplex {
2016-09-27T14:17:49.383050+00:00 app[web.1]:      _readableState:
2016-09-27T14:17:49.383050+00:00 app[web.1]:       ReadableState {
2016-09-27T14:17:49.383051+00:00 app[web.1]:         objectMode: false,
2016-09-27T14:17:49.383051+00:00 app[web.1]:         highWaterMark: 16384,
2016-09-27T14:17:49.383052+00:00 app[web.1]:         buffer: [],
2016-09-27T14:17:49.383052+00:00 app[web.1]:         length: 0,
2016-09-27T14:17:49.383053+00:00 app[web.1]:         pipes: null,
2016-09-27T14:17:49.383053+00:00 app[web.1]:         pipesCount: 0,
2016-09-27T14:17:49.383054+00:00 app[web.1]:         flowing: true,
2016-09-27T14:17:49.383055+00:00 app[web.1]:         ended: false,
2016-09-27T14:17:49.383055+00:00 app[web.1]:         endEmitted: false,
2016-09-27T14:17:49.383056+00:00 app[web.1]:         reading: false,
2016-09-27T14:17:49.383063+00:00 app[web.1]:         sync: true,
2016-09-27T14:17:49.383063+00:00 app[web.1]:         needReadable: false,
2016-09-27T14:17:49.383064+00:00 app[web.1]:         emittedReadable: false,
2016-09-27T14:17:49.383064+00:00 app[web.1]:         readableListening: false,
2016-09-27T14:17:49.383065+00:00 app[web.1]:         resumeScheduled: true,
2016-09-27T14:17:49.383066+00:00 app[web.1]:         defaultEncoding: 'utf8',
2016-09-27T14:17:49.383066+00:00 app[web.1]:         ranOut: false,
2016-09-27T14:17:49.383067+00:00 app[web.1]:         awaitDrain: 0,
2016-09-27T14:17:49.383067+00:00 app[web.1]:         readingMore: false,
2016-09-27T14:17:49.383068+00:00 app[web.1]:         decoder: null,
2016-09-27T14:17:49.383068+00:00 app[web.1]:         encoding: null },
2016-09-27T14:17:49.383069+00:00 app[web.1]:      readable: true,
2016-09-27T14:17:49.383069+00:00 app[web.1]:      domain: null,
2016-09-27T14:17:49.383070+00:00 app[web.1]:      _events: { end: [Object], erro
r: [Object], data: [Function] },
2016-09-27T14:17:49.383070+00:00 app[web.1]:      _eventsCount: 3,
2016-09-27T14:17:49.383071+00:00 app[web.1]:      _maxListeners: undefined,
2016-09-27T14:17:49.383071+00:00 app[web.1]:      _writableState:
2016-09-27T14:17:49.383072+00:00 app[web.1]:       WritableState {
2016-09-27T14:17:49.383072+00:00 app[web.1]:         objectMode: false,
2016-09-27T14:17:49.383073+00:00 app[web.1]:         highWaterMark: 16384,
2016-09-27T14:17:49.383073+00:00 app[web.1]:         needDrain: false,
2016-09-27T14:17:49.383074+00:00 app[web.1]:         ending: false,
2016-09-27T14:17:49.383074+00:00 app[web.1]:         ended: false,
2016-09-27T14:17:49.383075+00:00 app[web.1]:         finished: false,
2016-09-27T14:17:49.383075+00:00 app[web.1]:         decodeStrings: true,
2016-09-27T14:17:49.383076+00:00 app[web.1]:         defaultEncoding: 'utf8',
2016-09-27T14:17:49.383076+00:00 app[web.1]:         length: 0,
2016-09-27T14:17:49.383077+00:00 app[web.1]:         writing: false,
2016-09-27T14:17:49.383077+00:00 app[web.1]:         corked: 0,
2016-09-27T14:17:49.383078+00:00 app[web.1]:         sync: true,
2016-09-27T14:17:49.383078+00:00 app[web.1]:         bufferProcessing: false,
2016-09-27T14:17:49.383079+00:00 app[web.1]:         onwrite: [Function],
2016-09-27T14:17:49.383079+00:00 app[web.1]:         writecb: null,
2016-09-27T14:17:49.383080+00:00 app[web.1]:         writelen: 0,
2016-09-27T14:17:49.383080+00:00 app[web.1]:         bufferedRequest: null,
2016-09-27T14:17:49.383081+00:00 app[web.1]:         lastBufferedRequest: null,
2016-09-27T14:17:49.383081+00:00 app[web.1]:         pendingcb: 0,
2016-09-27T14:17:49.383082+00:00 app[web.1]:         prefinished: false,
2016-09-27T14:17:49.383082+00:00 app[web.1]:         errorEmitted: false,
2016-09-27T14:17:49.383083+00:00 app[web.1]:         bufferedRequestCount: 0,
2016-09-27T14:17:49.383083+00:00 app[web.1]:         corkedRequestsFree: [Object
] },
2016-09-27T14:17:49.383084+00:00 app[web.1]:      writable: true,
2016-09-27T14:17:49.383084+00:00 app[web.1]:      allowHalfOpen: true,
2016-09-27T14:17:49.383085+00:00 app[web.1]:      remote_options: { host: 'ho.st.ip.add', port: 3306 },
2016-09-27T14:17:49.383086+00:00 app[web.1]:      _socksSetup: false,
2016-09-27T14:17:49.383086+00:00 app[web.1]:      socksAddress: null,
2016-09-27T14:17:49.383087+00:00 app[web.1]:      socksPort: null,
2016-09-27T14:17:49.383087+00:00 app[web.1]:      socksSocket:
2016-09-27T14:17:49.383088+00:00 app[web.1]:       Socket {
2016-09-27T14:17:49.383088+00:00 app[web.1]:         _connecting: true,
2016-09-27T14:17:49.383089+00:00 app[web.1]:         _hadError: false,
2016-09-27T14:17:49.383089+00:00 app[web.1]:         _handle: [Object],
2016-09-27T14:17:49.383090+00:00 app[web.1]:         _parent: null,
2016-09-27T14:17:49.383091+00:00 app[web.1]:         _host: 'us-region-static-01.q
uotaguard.com',
2016-09-27T14:17:49.383091+00:00 app[web.1]:         _readableState: [Object],
2016-09-27T14:17:49.383092+00:00 app[web.1]:         readable: false,
2016-09-27T14:17:49.383092+00:00 app[web.1]:         domain: null,
2016-09-27T14:17:49.383093+00:00 app[web.1]:         _events: [Object],
2016-09-27T14:17:49.383093+00:00 app[web.1]:         _eventsCount: 6,
2016-09-27T14:17:49.383094+00:00 app[web.1]:         _maxListeners: undefined,
2016-09-27T14:17:49.383094+00:00 app[web.1]:         _writableState: [Object],
2016-09-27T14:17:49.383095+00:00 app[web.1]:         writable: true,
2016-09-27T14:17:49.383095+00:00 app[web.1]:         allowHalfOpen: false,
2016-09-27T14:17:49.383096+00:00 app[web.1]:         destroyed: false,
2016-09-27T14:17:49.383096+00:00 app[web.1]:         _bytesDispatched: 0,
2016-09-27T14:17:49.383097+00:00 app[web.1]:         _sockname: null,
2016-09-27T14:17:49.383097+00:00 app[web.1]:         _pendingData: null,
2016-09-27T14:17:49.383098+00:00 app[web.1]:         _pendingEncoding: '',
2016-09-27T14:17:49.383098+00:00 app[web.1]:         server: null,
2016-09-27T14:17:49.383099+00:00 app[web.1]:         _server: null,
2016-09-27T14:17:49.383099+00:00 app[web.1]:         read: [Function],
2016-09-27T14:17:49.383100+00:00 app[web.1]:         _consuming: true },
2016-09-27T14:17:49.383100+00:00 app[web.1]:      outSocket:
2016-09-27T14:17:49.383101+00:00 app[web.1]:       Socket {
2016-09-27T14:17:49.383101+00:00 app[web.1]:         _connecting: true,
2016-09-27T14:17:49.383102+00:00 app[web.1]:         _hadError: false,
2016-09-27T14:17:49.383102+00:00 app[web.1]:         _handle: [Object],
2016-09-27T14:17:49.383103+00:00 app[web.1]:         _parent: null,
2016-09-27T14:17:49.383103+00:00 app[web.1]:         _host: 'us-region-static-01.q
uotaguard.com',
2016-09-27T14:17:49.383104+00:00 app[web.1]:         _readableState: [Object],
2016-09-27T14:17:49.383104+00:00 app[web.1]:         readable: false,
2016-09-27T14:17:49.383105+00:00 app[web.1]:         domain: null,
2016-09-27T14:17:49.383105+00:00 app[web.1]:         _events: [Object],
2016-09-27T14:17:49.383112+00:00 app[web.1]:         _eventsCount: 6,
2016-09-27T14:17:49.383113+00:00 app[web.1]:         _maxListeners: undefined,
2016-09-27T14:17:49.383117+00:00 app[web.1]:         _writableState: [Object],
2016-09-27T14:17:49.383118+00:00 app[web.1]:         writable: true,
2016-09-27T14:17:49.383119+00:00 app[web.1]:         allowHalfOpen: false,
2016-09-27T14:17:49.383119+00:00 app[web.1]:         destroyed: false,
2016-09-27T14:17:49.383120+00:00 app[web.1]:         _bytesDispatched: 0,
2016-09-27T14:17:49.383120+00:00 app[web.1]:         _sockname: null,
2016-09-27T14:17:49.383121+00:00 app[web.1]:         _pendingData: null,
2016-09-27T14:17:49.383121+00:00 app[web.1]:         _pendingEncoding: '',
2016-09-27T14:17:49.383121+00:00 app[web.1]:         server: null,
2016-09-27T14:17:49.383122+00:00 app[web.1]:         _server: null,
2016-09-27T14:17:49.383122+00:00 app[web.1]:         read: [Function],
2016-09-27T14:17:49.383123+00:00 app[web.1]:         _consuming: true } },
2016-09-27T14:17:49.383124+00:00 app[web.1]:   _internalId: 0,
2016-09-27T14:17:49.383124+00:00 app[web.1]:   _commands: { [String: ''] _capaci
ty: 16, _length: 0, _front: 0 },
2016-09-27T14:17:49.383125+00:00 app[web.1]:   _command:
2016-09-27T14:17:49.383125+00:00 app[web.1]:    ClientHandshake {
2016-09-27T14:17:49.383126+00:00 app[web.1]:      handshake: null,
2016-09-27T14:17:49.383126+00:00 app[web.1]:      clientFlags: 193487,
2016-09-27T14:17:49.383126+00:00 app[web.1]:      domain: null,
2016-09-27T14:17:49.383127+00:00 app[web.1]:      _events: { end: [Function], er
ror: [Function] },
2016-09-27T14:17:49.383127+00:00 app[web.1]:      _eventsCount: 2,
2016-09-27T14:17:49.383128+00:00 app[web.1]:      _maxListeners: undefined,
2016-09-27T14:17:49.383128+00:00 app[web.1]:      next: [Function],
2016-09-27T14:17:49.383129+00:00 app[web.1]:      _commandName: 'Connection' },
2016-09-27T14:17:49.383130+00:00 app[web.1]:   _paused: false,
2016-09-27T14:17:49.383130+00:00 app[web.1]:   _paused_packets: { [String: ''] _
capacity: 16, _length: 0, _front: 0 },
2016-09-27T14:17:49.383131+00:00 app[web.1]:   _statements:
2016-09-27T14:17:49.383131+00:00 app[web.1]:    LRUCache {
2016-09-27T14:17:49.383132+00:00 app[web.1]:      max: 16000
2016-09-27T14:17:49.383132+00:00 app[web.1]:    },
2016-09-27T14:17:49.383133+00:00 app[web.1]:   textProtocolParsers: {},
2016-09-27T14:17:49.383133+00:00 app[web.1]:   binaryProtocolParsers: {},
2016-09-27T14:17:49.383134+00:00 app[web.1]:   serverCapabilityFlags: 0,
2016-09-27T14:17:49.383134+00:00 app[web.1]:   authorized: false,
2016-09-27T14:17:49.383152+00:00 app[web.1]:   sequenceId: 0,
2016-09-27T14:17:49.383153+00:00 app[web.1]:   threadId: null,
2016-09-27T14:17:49.383153+00:00 app[web.1]:   _handshakePacket: null,
2016-09-27T14:17:49.383154+00:00 app[web.1]:   _fatalError: null,
2016-09-27T14:17:49.383154+00:00 app[web.1]:   _protocolError: null,
2016-09-27T14:17:49.383155+00:00 app[web.1]:   _outOfOrderPackets: [],
2016-09-27T14:17:49.383155+00:00 app[web.1]:   packetParser:
2016-09-27T14:17:49.383156+00:00 app[web.1]:    PacketParser {
2016-09-27T14:17:49.383156+00:00 app[web.1]:      buffer: [],
2016-09-27T14:17:49.383157+00:00 app[web.1]:      bufferLength: 0,
2016-09-27T14:17:49.383157+00:00 app[web.1]:      packetHeaderLength: 4,
2016-09-27T14:17:49.383158+00:00 app[web.1]:      headerLen: 0,
2016-09-27T14:17:49.383158+00:00 app[web.1]:      length: 0,
2016-09-27T14:17:49.383158+00:00 app[web.1]:      onPacket: [Function],
2016-09-27T14:17:49.383159+00:00 app[web.1]:      execute: [Function: executeSta
rt] },
2016-09-27T14:17:49.383160+00:00 app[web.1]:   serverEncoding: 'utf8',
2016-09-27T14:17:49.383160+00:00 app[web.1]:   connectTimeout:
2016-09-27T14:17:49.383160+00:00 app[web.1]:    Timeout {
2016-09-27T14:17:49.383165+00:00 app[web.1]:      _called: false,
2016-09-27T14:17:49.383165+00:00 app[web.1]:      _idleTimeout: 100000,
2016-09-27T14:17:49.383166+00:00 app[web.1]:      _idlePrev:
2016-09-27T14:17:49.383166+00:00 app[web.1]:       TimersList {
2016-09-27T14:17:49.383167+00:00 app[web.1]:         _idleNext: [Circular],
2016-09-27T14:17:49.383167+00:00 app[web.1]:         _idlePrev: [Circular],
2016-09-27T14:17:49.383168+00:00 app[web.1]:         _timer: [Object],
2016-09-27T14:17:49.383168+00:00 app[web.1]:         _unrefed: false,
2016-09-27T14:17:49.383169+00:00 app[web.1]:         msecs: 100000 },
2016-09-27T14:17:49.383169+00:00 app[web.1]:      _idleNext:
2016-09-27T14:17:49.383170+00:00 app[web.1]:       TimersList {
2016-09-27T14:17:49.383170+00:00 app[web.1]:         _idleNext: [Circular],
2016-09-27T14:17:49.383171+00:00 app[web.1]:         _idlePrev: [Circular],
2016-09-27T14:17:49.383171+00:00 app[web.1]:         _timer: [Object],
2016-09-27T14:17:49.383172+00:00 app[web.1]:         _unrefed: false,
2016-09-27T14:17:49.383173+00:00 app[web.1]:         msecs: 100000 },
2016-09-27T14:17:49.383173+00:00 app[web.1]:      _idleStart: 1402,
2016-09-27T14:17:49.383174+00:00 app[web.1]:      _onTimeout: [Function: bound ]
,
2016-09-27T14:17:49.383175+00:00 app[web.1]:      _repeat: null } }

2016-09-27T14:17:49.511926+00:00 app[web.1]: Server started on port #####
2016-09-27T14:17:49.846741+00:00 app[web.1]:  raw: 0a352e372e31312d676f6f676c652
d6c6f6700bd89010038302272731d0b1700ffff210200ffc115000000000000000000006a747e323
15a39692513344b006d7973716c5f6e61746976655f70617373776f726400
2016-09-27T14:17:49.847929+00:00 app[web.1]: Trace
2016-09-27T14:17:49.847931+00:00 app[web.1]:     at Connection.handlePacket (/ap
p/node_modules/mysql2/lib/connection.js:349:15)
2016-09-27T14:17:49.847932+00:00 app[web.1]:     at PacketParser.onPacket (/app/
node_modules/mysql2/lib/connection.js:87:66)
2016-09-27T14:17:49.847933+00:00 app[web.1]:     at PacketParser.executeStart (/
app/node_modules/mysql2/lib/packet_parser.js:45:12)
2016-09-27T14:17:49.847934+00:00 app[web.1]:     at null.<anonymous> (/app/node_
modules/mysql2/lib/connection.js:94:29)
2016-09-27T14:17:49.847935+00:00 app[web.1]:     at emitOne (events.js:90:13)
2016-09-27T14:17:49.847936+00:00 app[web.1]:     at emit (events.js:182:7)
2016-09-27T14:17:49.847937+00:00 app[web.1]:     at readableAddChunk (_stream_re
adable.js:153:18)
2016-09-27T14:17:49.847937+00:00 app[web.1]:     at Readable.push (_stream_reada
ble.js:111:10)
2016-09-27T14:17:49.847938+00:00 app[web.1]:     at Socket.<anonymous> (/app/nod
e_modules/socksjs/socks.js:298:23)
2016-09-27T14:17:49.847939+00:00 app[web.1]:     at emitNone (events.js:80:13)
2016-09-27T14:17:49.847939+00:00 app[web.1]:     at Socket.emit (events.js:179:7
)
2016-09-27T14:17:49.847940+00:00 app[web.1]:     at emitReadable_ (_stream_reada
ble.js:419:10)
2016-09-27T14:17:49.847941+00:00 app[web.1]:     at emitReadable (_stream_readab
le.js:413:7)
2016-09-27T14:17:49.847941+00:00 app[web.1]:     at readableAddChunk (_stream_re
adable.js:164:13)
2016-09-27T14:17:49.847942+00:00 app[web.1]:     at Socket.Readable.push (_strea
m_readable.js:111:10)
2016-09-27T14:17:49.847942+00:00 app[web.1]:     at TCP.onread (net.js:534:20)
2016-09-27T14:17:49.849268+00:00 app[web.1]: 0 undefined ==> Connection#handshak
eInit(0,,89)
2016-09-27T14:17:49.863779+00:00 app[web.1]: Server hello packet: capability fla
gs:3254779903=(long password, found rows, long flag, connect with db, no schema,
 compress, odbc, local files, ignore space, protocol 41, interactive, ssl, ignor
e sigpipe, transactions, reserved, secure connection, multi statements, multi re
sults, ps multi results, plugin auth, connect attrs, plugin auth lenenc client d
ata, can handle expired passwords, session track, deprecate eof, ssl verify serv
er cert, remember options)
2016-09-27T14:17:49.864085+00:00 app[web.1]: Sending handshake packet: flags:193
487=(long password, found rows, long flag, connect with db, odbc, local files, i
gnore space, protocol 41, ignore sigpipe, transactions, reserved, secure connect
ion, multi results)
2016-09-27T14:17:49.868557+00:00 app[web.1]: 0 100797 <== Connection#handshakeIn
it(1,,68)
2016-09-27T14:17:49.868655+00:00 app[web.1]: 0 100797 <== 40000001cff30200000000
00e00000000000000000000000000000000000000000000000707974686f6e6170700014a9cae6db
cc9fb84e41b42944151be71f68fc69a000
2016-09-27T14:17:49.890213+00:00 app[web.1]:  raw: 00000002000000
2016-09-27T14:17:49.890216+00:00 app[web.1]: Trace
2016-09-27T14:17:49.890218+00:00 app[web.1]:     at Connection.handlePacket (/ap
p/node_modules/mysql2/lib/connection.js:349:15)
2016-09-27T14:17:49.890219+00:00 app[web.1]:     at PacketParser.onPacket (/app/
node_modules/mysql2/lib/connection.js:87:66)
2016-09-27T14:17:49.890220+00:00 app[web.1]:     at PacketParser.executeStart (/
app/node_modules/mysql2/lib/packet_parser.js:45:12)
2016-09-27T14:17:49.890221+00:00 app[web.1]:     at null.<anonymous> (/app/node_
modules/mysql2/lib/connection.js:94:29)
2016-09-27T14:17:49.890222+00:00 app[web.1]:     at emitOne (events.js:90:13)
2016-09-27T14:17:49.890223+00:00 app[web.1]:     at emit (events.js:182:7)
2016-09-27T14:17:49.890224+00:00 app[web.1]:     at readableAddChunk (_stream_re
adable.js:153:18)
2016-09-27T14:17:49.890227+00:00 app[web.1]:     at Readable.push (_stream_reada
ble.js:111:10)
2016-09-27T14:17:49.890228+00:00 app[web.1]:     at Socket.<anonymous> (/app/nod
e_modules/socksjs/socks.js:298:23)
2016-09-27T14:17:49.890228+00:00 app[web.1]:     at emitNone (events.js:80:13)
2016-09-27T14:17:49.890229+00:00 app[web.1]:     at Socket.emit (events.js:179:7
)
2016-09-27T14:17:49.890230+00:00 app[web.1]:     at emitReadable_ (_stream_reada
ble.js:419:10)
2016-09-27T14:17:49.890231+00:00 app[web.1]:     at emitReadable (_stream_readab
le.js:413:7)
2016-09-27T14:17:49.890232+00:00 app[web.1]:     at readableAddChunk (_stream_re
adable.js:164:13)
2016-09-27T14:17:49.890233+00:00 app[web.1]:     at Socket.Readable.push (_strea
m_readable.js:111:10)
2016-09-27T14:17:49.890233+00:00 app[web.1]:     at TCP.onread (net.js:534:20)
2016-09-27T14:17:49.890234+00:00 app[web.1]: 0 100797 ==> Connection#handshakeRe
sult(2,maybeOK,11)
2016-09-27T14:17:49.910278+00:00 heroku[web.1]: State changed from starting to u
p
2016-09-27T14:18:49.585874+00:00 app[web.1]: events.js:154
2016-09-27T14:18:49.585888+00:00 app[web.1]:       throw er; // Unhandled 'error
' event
2016-09-27T14:18:49.585889+00:00 app[web.1]:       ^
2016-09-27T14:18:49.585890+00:00 app[web.1]:
2016-09-27T14:18:49.585891+00:00 app[web.1]: Error: Connection lost: The server
closed the connection.
2016-09-27T14:18:49.585892+00:00 app[web.1]:     at null.<anonymous> (/app/node_
modules/mysql2/lib/connection.js:104:35)
2016-09-27T14:18:49.585892+00:00 app[web.1]:     at emitNone (events.js:85:20)
2016-09-27T14:18:49.585893+00:00 app[web.1]:     at emit (events.js:179:7)
2016-09-27T14:18:49.585894+00:00 app[web.1]:     at endReadableNT (_stream_reada
ble.js:913:12)
2016-09-27T14:18:49.585894+00:00 app[web.1]:     at _combinedTickCallback (inter
nal/process/next_tick.js:74:11)
2016-09-27T14:18:49.585895+00:00 app[web.1]:     at process._tickDomainCallback
(internal/process/next_tick.js:122:9)
2016-09-27T14:18:49.653883+00:00 heroku[web.1]: Process exited with status 1
2016-09-27T14:18:49.660388+00:00 heroku[web.1]: State changed from up to crashed

```

**Comment by sidorares** [comment]
Thanks for the log @mm-wang 

I see that initial hello packet from server arrives, then client sends "client hello" ( this is where hashed password etc ) and receives "ok" response from server, but then connection is closed for some reason

Were you able to connect without proxy from non-heroky fixed ip box?

**Comment by mm-wang** [comment]
Yes, I had been developing with that setup. So I believe this has to do with the package.

**Comment by sidorares** [comment]
Another suggestion - try different socks proxy client, for example https://github.com/mscdex/socksv5

**Comment by mm-wang** [comment]
I have set up a different SOCKS proxy client, and I have the socket connecting for sure now. In the log below, it happens where the log prints out ">> Connection successful".

It seems that I am getting an error of access denied, but I know for sure that the username and password that I provide are valid, and that the static IP used is valid.

```
2016-09-28T15:36:23.109788+00:00 app[web.1]: events.js:154
2016-09-28T15:36:23.109791+00:00 app[web.1]:       throw er; // Unhandled 'error
' event
2016-09-28T15:36:23.109791+00:00 app[web.1]:       ^
2016-09-28T15:36:23.109792+00:00 app[web.1]:
2016-09-28T15:36:23.051900+00:00 app[web.1]: >> Connection successful
2016-09-28T15:36:23.109807+00:00 app[web.1]: Error: Access denied for user '[username]'@'static.ip.add.ress' (using password: YES)
2016-09-28T15:36:23.109809+00:00 app[web.1]:     at ClientHandshake.Command.exec
ute (/app/node_modules/mysql2/lib/commands/command.js:28:22)
2016-09-28T15:36:23.109812+00:00 app[web.1]:     at Socket.<anonymous> (/app/nod
e_modules/mysql2/lib/connection.js:94:29)
2016-09-28T15:36:23.109813+00:00 app[web.1]:     at emitOne (events.js:90:13)
2016-09-28T15:36:23.109813+00:00 app[web.1]:     at Socket.emit (events.js:182:7
)
2016-09-28T15:36:23.109810+00:00 app[web.1]:     at Connection.handlePacket (/ap
p/node_modules/mysql2/lib/connection.js:361:28)
2016-09-28T15:36:23.109810+00:00 app[web.1]:     at PacketParser.onPacket (/app/
node_modules/mysql2/lib/connection.js:87:66)
2016-09-28T15:36:23.109808+00:00 app[web.1]:     at Packet.asError (/app/node_mo
dules/mysql2/lib/packets/packet.js:666:13)
2016-09-28T15:36:23.109815+00:00 app[web.1]:     at readableAddChunk (_stream_re
adable.js:153:18)
2016-09-28T15:36:23.109811+00:00 app[web.1]:     at PacketParser.executeStart (/
app/node_modules/mysql2/lib/packet_parser.js:45:12)
2016-09-28T15:36:23.109815+00:00 app[web.1]:     at Socket.Readable.push (_strea
m_readable.js:111:10)
2016-09-28T15:36:23.109816+00:00 app[web.1]:     at TCP.onread (net.js:534:20)
2016-09-28T15:36:23.197653+00:00 heroku[web.1]: State changed from up to crashed

2016-09-28T15:36:23.185423+00:00 heroku[web.1]: Process exited with status 1
2016-09-28T15:36:27.289796+00:00 heroku[router]: at=error code=H10 desc="App cra
shed" method=GET path="/" host=[appname] request_id=11a1e94f-4b55
-43ea-8d40-dbcbbb670a9c fwd="app.ip.add.ress" dyno= connect= service= status=503 b
ytes=
```

**Comment by sushantdhiman** [comment]
Heroku does prevent external IPs to access its databases (Although you have setup some sort of proxy), are you using ClearDB for Heroku ?

Access Denied is pretty clearly mistake in either username, password, hostname or port. Can you connect using MySQL CLI ?

**Comment by sidorares** [comment]
@mm-wang so the "Error: Access denied for user '[username]'@'static.ip.add.ress' (using password: YES)" message is coming from mysql server, you definitely have communication over socks proxy working fine with mysql client - the problem is on user configuration side

@sushantdhiman wdyt about `.destroy()` issue?

**Comment by sushantdhiman** [comment]
@sidorares Do we have to do stream.socket.destroy() ?

**Comment by sidorares** [comment]
I think you added it :) I'm not sure, probably it's not necessary

**Comment by sushantdhiman** [comment]
Usually stream have destroy method, i wanted to clean the connection. But that doesn't appears to be the case. We can simply remove it.

**Comment by sidorares** [comment]
Can't see any mention of destroy here https://nodejs.org/api/stream.html - probably we should remove it

**Comment by mm-wang** [comment]
Seems that error was separate, I still have an ECONNREFUSED 127.0.0.1:3306 error on connect. The socket seems connected, but there is a connection error. I think I'll just have to keep tinkering with this to see what the problem is.

**Comment by mm-wang** [comment]
Okay, I've finally fixed the connection. There was something going on with the socket callback, but I am all set now. Thanks for all the help in troubleshooting and the suggestion of a new socks client!
