### ISSUE TITLE
Error while stress testing

### ISSUE THREAD

**Issue by mudaser-caremerge** [sidorares/node-mysql2#471]
Hi,

I am using lastest version of mysql2 with following sequelize configuration

Node: v.4.4.1
mysql: v5.6.21
sequelize:  v2.0.0-dev9
sequelize: configuration

```
var defaultOptions = {
        "host": default_config.host,
        "port": default_config.port,
        "dialectModulePath": 'mysql2',
        "dialect": "mysql",
        "define": {
            "timestamps": false,
            "freezeTableName": true,
            "syncOnAssociation": false
        },
        "pool": {
            "maxConnections": 10,
            "minConnections": 10,
            "maxIdleTime": 10000,
            "handleDisconnects": true
        },
        "logging": (default_config.logging == undefined ? function(x) { defaultLogger.trace(x); } : default_config.logging),
		"dialectOptions": { multipleStatements: true }
    };
```
after adding some stress + run test cases i am getting following error

```
Error message: write after end
Stack trace: Error: write after end
    at writeAfterEnd (_stream_writable.js:166:12)
    at Socket.Writable.write (_stream_writable.js:211:5)
    at Socket.write (net.js:642:40)
    at Connection.write (/project/node_modules/mysql2/lib/connection.js:224:15)
    at Connection.writePacket (/project/node_modules/mysql2/lib/connection.js:265:10)
    at Quit.start (/project/node_modules/mysql2/lib/commands/quit.js:21:14)
    at Quit.Command.execute (/project/node_modules/mysql2/lib/commands/command.js:39:20)
    at Connection.handlePacket (/project/node_modules/mysql2/lib/connection.js:417:28)
    at Connection.addCommand (/project/node_modules/mysql2/lib/connection.js:440:10)
    at Connection.end (/project/node_modules/mysql2/lib/connection.js:804:22)
    at module.exports.disconnect (/project/node_modules/sequelize/lib/dialects/mysql/connector-manager.js:265:12)
    at Object.pool.Pooling.Pool.destroy (/project/node_modules/sequelize/lib/dialects/mysql/connector-manager.js:137:22)
    at Object.me.destroy (/project/node_modules/sequelize/node_modules/generic-pool/lib/generic-pool.js:149:13)
    at removeIdle (/project/node_modules/sequelize/node_modules/generic-pool/lib/generic-pool.js:178:10)
    at Timer.listOnTimeout (timers.js:92:15)
Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:344:11)
    at ServerResponse.res.setHeader (/project/node_modules/connect/lib/patch.js:134:22)
    at ServerResponse.header (/project/node_modules/express/lib/response.js:719:10)
    at ServerResponse.send (/project/node_modules/express/lib/response.js:164:12)
    at done (/project/node_modules/express/lib/response.js:956:10)
    at View.exports.renderFile [as engine] (/project/node_modules/ejs/lib/ejs.js:318:3)
    at View.render (/project/node_modules/express/lib/view.js:126:8)
    at tryRender (/project/node_modules/express/lib/application.js:639:10)
    at EventEmitter.render (/project/node_modules/express/lib/application.js:591:3)
    at ServerResponse.render (/project/node_modules/express/lib/response.js:960:7)
    at /project/node_modules/express-partials/index.js:82:15
    at View.exports.renderFile [as engine] (/project/node_modules/ejs/lib/ejs.js:318:3)
    at View.render (/project/node_modules/express/lib/view.js:126:8)
    at tryRender (/project/node_modules/express/lib/application.js:639:10)
    at EventEmitter.render (/project/node_modules/express/lib/application.js:591:3)
    at ServerResponse.render (/project/node_modules/express/lib/response.js:960:7)
    at ServerResponse.res.render (/project/node_modules/express-partials/index.js:55:9)
    at Domain.<anonymous> (/project/config/express.js:53:23)
    at emitOne (events.js:77:13)
    at Domain.emit (events.js:169:7)
    at emitError (domain.js:66:24)
    at Domain.errorHandler [as _errorHandler] (domain.js:126:16)
```

**Comment by sidorares** [comment]
hi! What is mysql2 version used? This might been fixed a while ago https://github.com/sidorares/node-mysql2/commit/0e14af0ffab0b21b28111fd82f51a912c5bcbef7#diff-259dec4414a400a6e895f16ff1d0ca3bR211

**Comment by mudaser-caremerge** [comment]
i am using this version `"mysql2": "^1.1.2",`

**Comment by sidorares** [comment]
is there any way this can be reduced to something I can install and reproduce?

**Comment by sushantdhiman** [comment]
`sequelize: v2.0.0-dev9` that is way old version of sequelize, use `v4` which officially supports `node-mysql2`

**Comment by mudaser-caremerge** [comment]
@sushantdhiman its true we are using old version; but read my first message carefully; if i put some load on the server using jmeter after lot of successful calls suddenly i am getting this error; so if current version of mysql2 it is not compatible with the old sequelize then it should not serve all requests?

**Comment by mudaser-caremerge** [comment]
@sidorares let me try to reproduce it in a simple environment

**Comment by sushantdhiman** [comment]
@mudaser-caremerge I did the migration of `mysql` to `mysql2` for sequelize and there was a difference in handling connections and error reporting in both drivers, so its possible some errors are missed while other are appearing because of inherent difference in drivers and how sequelize works with them.

To get more precise result I would suggest try `v4` which handles connection pool for `mysql2` driver.

**Comment by neebz** [comment]
@sushantdhiman thanks for the feedback; 

I am @mudaser-caremerge's colleague.

as much we would love to migrate to v4, unfortunately we have considerable code written in older version of Sequelize and there are many breaking changes since then. 😞 

we'll try to reproduce the issue in simpler environment.

**Comment by sidorares** [comment]
hi @neebz @mudaser-caremerge to me it looks that this issue is still hitting some existing edge case bug which I'm really keen to fix, any help would be appreciated

**Comment by neebz** [comment]
we are on it; thanks for all your work 👍
