### ISSUE TITLE
Any way to get long stack trace using async/await?

### ISSUE THREAD

**Issue by chrisveness** [sidorares/node-mysql2#530]
Andrey, I know this is broader than mysql2, but it came up in that context.

If I have an error thrown when calling `query()`, the stack trace makes no reference to the call site, just to mysql2 code. Do you know if there's any way to achieve a long stack trace that references the original call?

Example:

    const mysql = require('mysql2/promise');
    require('dotenv').config();

    const config = {
        host:     process.env.DB_HOST,
        port:     process.env.DB_PORT,
        user:     process.env.DB_USER,
        password: process.env.DB_PASSWORD,
        database: process.env.DB_DATABASE,
    };

    async function test() {
        try {
            const connection = await mysql.createConnection(config);
            const [rows] = await connection.query('Select * From NonExistantTable');
            return rows;
        } catch (e) {
            throw e;
        }
    }

    test().then(data => console.log(data)).catch(error => console.log(error));
results in error:

    { Error: Table 'db.NonExistantTable' doesn't exist
        at Packet.asError (/.../node_modules/mysql2/lib/packets/packet.js:667:13)
        at Query.Command.execute (/.../node_modules/mysql2/lib/commands/command.js:29:22)
        at Connection.handlePacket (/.../node_modules/mysql2/lib/connection.js:417:28)
        at PacketParser.onPacket (/.../node_modules/mysql2/lib/connection.js:93:16)
        at PacketParser.executeStart (/.../node_modules/mysql2/lib/packet_parser.js:73:14)
        at Socket.<anonymous> (/.../node_modules/mysql2/lib/connection.js:101:29)
        at emitOne (events.js:96:13)
        at Socket.emit (events.js:191:7)
        at readableAddChunk (_stream_readable.js:178:18)
        at Socket.Readable.push (_stream_readable.js:136:10) code: 'ER_NO_SUCH_TABLE', errno: 1146, sqlState: '#42S02' }

with no reference to original call site.

I won't be offended if you simply close, as it is not specific to mysql2, but if you have any advice it would be appreciated.

Thanks, Chris

**Comment by dougwilson** [comment]
The stack should be complete, but from your stack there, it looks like you're really just hitting the default v8 stack limit of 10. Try starting Node.js with `node --stack-trace-limit=1000` and see if the trace is more complete.

**Comment by chrisveness** [comment]
Good suggestion, Doug, but unfortunately I just get an extra `at TCP.onread (net.js:563:20)`: using `--stack-trace-limit=1000` the full stack trace comes out as:

    { Error: Table 'koa-sample-sandbox.NonExistantTable' doesn't exist
        at Packet.asError (/.../node_modules/mysql2/lib/packets/packet.js:667:13)
        at Query.Command.execute (/.../node_modules/mysql2/lib/commands/command.js:29:22)
        at Connection.handlePacket (/.../node_modules/mysql2/lib/connection.js:417:28)
        at PacketParser.onPacket (/.../node_modules/mysql2/lib/connection.js:93:16)
        at PacketParser.executeStart (/.../node_modules/mysql2/lib/packet_parser.js:73:14)
        at Socket.<anonymous> (/.../node_modules/mysql2/lib/connection.js:101:29)
        at emitOne (events.js:96:13)
        at Socket.emit (events.js:191:7)
        at readableAddChunk (_stream_readable.js:178:18)
        at Socket.Readable.push (_stream_readable.js:136:10)
        at TCP.onread (net.js:563:20) code: 'ER_NO_SUCH_TABLE', errno: 1146, sqlState: '#42S02' }

**Comment by sidorares** [comment]
@chrisveness I'm thinking about changing reject to use local Error object. Have a look at connection  and query error handlers: https://gist.github.com/sidorares/f30d9d97cd327714ef04d11ce99b240f#file-promisewrapperlocalerrors-js

```js
const mysql = require('mysql2/promise');

async function main() {
  const c = await mysql.createConnection({ port: 33306, database: 'test', user: 'root' })
  console.log(await c.query('select 1+1'));


  
  console.log(await c.query('select 1+foo'));
}


main()
  .then(() => {
    console.log('done')
  })
  .catch(err => {
    console.log('ERROR!!!')
    console.log(err)
  })
```

`console.log(err)` points now to correct line 9

```
ERROR!!!
{ Error: Unknown column 'foo' in 'field list'
    at PromiseConnection.query (/private/tmp/async_test.js/node_modules/mysql2/promise.js:53:18)
    at main (/private/tmp/async_test.js/qqq.js:9:23)
    at process._tickCallback (internal/process/next_tick.js:109:7)
  message: 'Unknown column \'foo\' in \'field list\'',
  code: 'ER_BAD_FIELD_ERROR',
  errno: 1054,
  sqlState: '#42S22' }
```

Could you try this and let me know what you think? One downside is that creating Error object is a bit costly and for long stack trace we need to do this in advance and this time is wasted if there is no error. IMO it's ok n high level functions such as connect/query/execute. On my machine `new Error` takes about 5*10e-7 seconds time ( 5 sec if in 10000000 iterations loop )

**Comment by chrisveness** [comment]
Using the updated [promise.js](https://gist.github.com/sidorares/f30d9d97cd327714ef04d11ce99b240f#file-promisewrapperlocalerrors-js) from the gist, I get a stack trace for the example above of:

    { Error: Table 'db.NonExistantTable' doesn't exist
        at PromiseConnection.query (/.../node_modules/mysql2/promise.js:52:20)
        at test (/.../trace-test.js:15:45)
        at process._tickCallback (internal/process/next_tick.js:109:7)
      message: 'Table \'db.NonExistantTable\' doesn\'t exist',
      code: 'ER_NO_SUCH_TABLE',
      errno: 1146,
      sqlState: '#42S02' }

Which points directly to the callsite in my code. It seems to me this could be quite beneficial in debugging.

I defer to you on performance considerations, though as you say, it looks as though your changes only affect the top-level `createConnection()`, `query()`, and `execute()` functions (+ transaction functions & some others such as `getConnection()`, `prepare()`, `end()`?) – so I don't suppose the pain is too much? Seems worth it to me.

ps – minutest (`5e-7` sec) gain could be achieved for `createConnection()` by moving the `createConnectionErr` declaration within the `coreConnection.once` error handler?

**Comment by sidorares** [comment]
> ps – minutest (5e-7 sec) gain could be achieved for createConnection() by moving the createConnectionErr declaration within the coreConnection.once error handler?

no, while event emitter itself is synchronous (You'll see 'emit' call directly below 'once') the error is emitted from event loop and you won't see line related to you logic where you call `createConnection`

**Comment by BrighTide** [comment]
If you're using a long stack trace lib like longjohn, they all rely on the async-listener functionality, which async await (as well as Promises, in some weird situations I don't understand) breaks

**Comment by gajus** [comment]
I haven't managed to make longjohn work for this purpose.

Assuming you are debugging a one off issue (as opposed to logging), the best way to see the long stack trace is to enable async stack traces in Chrome dev tools.

<img width="437" alt="screen shot 2017-04-09 at 09 12 11" src="https://cloud.githubusercontent.com/assets/973543/24835840/ab12e23c-1d04-11e7-9219-70ae9d680122.png">

In case of an error, this will give full stack trace.

See https://nodejs.org/api/debugger.html#debugger_v8_inspector_integration_for_node_js for instructions how to debug node with Chrome Devtools.

Alternatively, if you are only interested to see which query is causing the havoc, log the query before it has been executed. I've authored https://github.com/gajus/mightyql just for that use case.

**Comment by Gregoor** [comment]
@sidorares Should this be working for pooled conections as well? All I'm getting for those is:

```
Duplicate entry '861a4a48-dd6f-4103-92e9-ada30f2ca523' for key 'PRIMARY', Error: Duplicate entry '861a4a48-dd6f-4103-92e9-ada30f2ca523' for key 'PRIMARY'
at PromisePool.query (/var/www/voice/node_modules/mysql2/promise.js:323:22)
at Mysql.query (/var/www/voice/server/src/lib/model/db/mysql.ts:83:35)
at <anonymous> at process._tickDomainCallback (internal/process/next_tick.js:229:7)
```
