### ISSUE TITLE
Connection pooling promise "end" function throws exception if a connection is waiting to query

### ISSUE THREAD

**Issue by Paril** [sidorares/node-mysql2#546]
I'm using mysql2/promise; if I attempt to .end() a Pool just after a call to pool.execute (such as during an ungraceful exit or if I'm rebooting a server and a query happens to run during that time), an exception is thrown. My assumption was that it was meant to wait until all of the queries are done before returning execution.

```{ Error: Can't add new command when connection is in closed state
    at PoolConnection.Connection._addCommandClosedState (G:\xampp2\htdocs2\chat3p0\server_node\js\node_modules\mysql2\lib\connection.js:145:13)
    at PoolConnection.execute (G:\xampp2\htdocs2\chat3p0\server_node\js\node_modules\mysql2\lib\connection.js:614:8)
    at G:\xampp2\htdocs2\chat3p0\server_node\js\node_modules\mysql2\lib\pool.js:159:17
    at G:\xampp2\htdocs2\chat3p0\server_node\js\node_modules\mysql2\lib\pool.js:36:14
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9) fatal: true }```

**Comment by sidorares** [comment]
can you show the code around `.execute()`? The error indicates that some command was added after `end()` was called. `.end()` adds COM_QUIT command to the queue and sets the flag 'connection is about to be closed, adding more commands not allowed'. Commands that are before `end` in the queue are still going to be processed

**Comment by Paril** [comment]
Nothing in the stack is part of my code, so it's hard to tell. Since a lot of this asynchronous stuff is done through promises I don't have a very clear idea of where things are going/coming from, but I have a slight hint here.

This specific issue happens if I gracefully try to close the server; on graceful exit, all users are disconnected gracefully and each disconnect is triggering a query that updates a field in the database, but of course it's likely not executed on that tick so it's in the queue. After that's all happened, the pool is then end()ed, but the promises for the query must then be getting called back to and trying to run Execute or something which is throwing the error - that's the only explanation I can come up with at the moment at least.

**Comment by sidorares** [comment]
I'll try to land changes discussed in #530 soon, that might help locating source

**Comment by Paril** [comment]
Cool, thanks! I'll keep an eye on that one. In the mean time I suppose I'll gracefully boot the users, wait like 5 seconds for everything to drain and then end the pool.

**Comment by sidorares** [comment]
there is also `pool.end()` that (I believe) puts `.end()` command to all open connections and at the same time removes them from 'active' list so in theory `_addCommandClosedState` should not happen in that case
