### ISSUE TITLE
"null" as a value can't be used for certain statements

### ISSUE THREAD

**Issue by Paril** [sidorares/node-mysql2#556]
Seems that, somewhere down the line, "toString" is called on all of the arguments of prepared statements, which can't be run on the value of null since it's.. well, null.

```
TypeError: Cannot read property 'toString' of undefined
    at Execute.toPacket (/home/planetmi/chat/node/js/node_modules/mysql2/lib/packets/execute.js:47:39)
    at Execute.start (/home/planetmi/chat/node/js/node_modules/mysql2/lib/commands/execute.js:50:40)
    at Execute.Command.execute (/home/planetmi/chat/node/js/node_modules/mysql2/lib/commands/command.js:39:20)
```

**Comment by sidorares** [comment]
this was started in #480 but unfortunately did not have time yet to review & merge

also related are #493, #353
