### ISSUE TITLE
ETIMEDOUT occuring multiple times in node script then moves on.

### ISSUE THREAD

**Issue by PsyTae** [sidorares/node-mysql2#599]
Here is my DB Connection  

```
var mysql = require('mysql2'), // mysql2

// MYSQL Connection Info:
var db_config = {
	connectionLimit: 10,
	waitForConnections: true,
    host: 'a.server.our.in.the.cloud.us-west-2.rds.amazonaws.com',
    port: '3306',
    user: 'XXXXXXXX',
    password: 'XXXXXXXX',
    database: 'DB'
};
 
var connection = mysql.createPool(db_config);

connection.on('error', function(err){
	console.error('mysql Error', err);
});
```

Literally (half - 1) of my pool connections timeout about 2-5 minutes after starting my script with the error:
```
{ Error: connect ETIMEDOUT
    at PoolConnection.Connection._handleTimeoutError (C:\nodeCode\FTPWatcher\node_modules\mysql2\lib\connection.js:188:13)
    at ontimeout (timers.js:386:14)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5)
  errorno: 'ETIMEDOUT',
  code: 'ETIMEDOUT',
  syscall: 'connect',
  fatal: true }
```
 When I had 100 for my connection pool 49 Errors, When I have 50 connections, 24 Errors, when I did 10, 4 errors.
Did The rest of the pool connect successfully?
What about the queries that initiated the connection from my pool? Did they die to never reach my DB? 

Version of mysql2 I am using
mysql2@1.3.5
node v 6.11.0

**Comment by sidorares** [comment]
Interesting
Can you enable debug? It feels that 2x as much connections actually trying to connect ( or maybe increment connected queue length, idk ), very curious about 49 / 24 / 4 numbers

Do you have correct security group settings ( e.i are you able to connect from the same box using some other client - mysql cli / mysql workbench etc ) ? Is another half able to perform query?

**Comment by PsyTae** [comment]
We are able to connect using heidi sql from the same box with the connection information the same, without any issues.

**Comment by PsyTae** [comment]
Also, the pool re-establishes the connections about 1 minute later and the script continues running as normal and expected after that reconnect.

**Comment by mavrick** [comment]
Could this be related to: https://github.com/sequelize/sequelize/issues/7884

Having connection issues with mysql boxes via sequelize

**Comment by tomcon** [comment]
Have had the same problem over a number of months, happening on rare occasions with the same project(s). It has been intermittent, **no change whatsoever to db cfg**,  sometimes rebooting machine cleared it.

Happened again today, 
```select outbound from zrefcx_grid_ref order by outbound
Add command: ClientHandshake
Error: connect ETIMEDOUT
    at PromisePool.query (d:\apps\C5_Group\node_modules\mysql2\promise.js:330:22)
    at runQuery (d:\apps\C5_Group\csl\server\db\mysql\db.js:33:44)
    at C5Cache.init (d:\apps\C5_Group\_shared\server\cache.js:26:10)
    ...
    at Object.<anonymous> (d:\apps\C5_Group\C5\server\app\c5.js:60:14)
    at Module._compile (internal/modules/cjs/loader.js:1147:30) {
  message: 'connect ETIMEDOUT',
  code: 'ETIMEDOUT',
  errno: undefined,
  sqlState: undefined,
  sqlMessage: undefined
}
```
changed host from localhost to  127.0.0.1 and it was able to connect ok!
*Note that localhost was fine most of the time* just occasionally this error cropped up

**Comment by sidorares** [comment]
> Changed host from localhost to 127.0.0.1 and it was able to connect ok!

could it be some local resolver or system dns issues?
@tomcon could you try to reduce to a simplest node tcp client and see if you have similar issues?

**Comment by tomcon** [comment]
@sidorares ran this code with two settings for host (localhost & 127.0.0.1) using port 1337 on Windows 10
```   
/* ----------------------- SERVER -----------------------*/
let server = net.createServer(function(socket) {
  socket.on('error', function(err) {
    console.log( `SERVER CONSOLE.LOG: onerror ${err}` )
  })

  socket.write('SERVER WRITE: write\r\n');
  socket.pipe(socket);
});
server.listen( port, host );
console.log( `SERVER CONSOLE LOG: tcp server (${host}) listening on port ${port} Echo server\r\n`);

/* ----------------------- CLIENT -----------------------*/
client.connect( port, host, function() {
	console.log('CLIENT CONSOLE LOG: Connected ')
	client.write('CLIENT WRITE: Hello, server! Love, Client.')
})

client.on('data', function(data) {
	console.log( 'CLIENT CONSOLE LOG: Received: ' + data)
	client.destroy() // kill client after server's response
})

client.on('close', function() {
	console.log('CLIENT CONSOLE LOG: Connection closed')
})
```

RESULTS :
1) 127.0.0.1  - 1st attempt on client connect causes a reset, ran client again and all seems ok 
2) localhost  - timed out after 20secs, again causes a reset, ran client again and all seems ok 

```
/*---------------- SERVER -------------------------------
node server-IP.js
SERVER CONSOLE LOG: tcp server (127.0.0.1) listening on port 1337 Echo server
 
SERVER CONSOLE.LOG: onerror Error: read ECONNRESET

------------------ CLIENT -----------------------
node client-IP.js 
CLIENT CONSOLE LOG: Connected
CLIENT CONSOLE LOG: Received: SERVER WRITE: write
 
CLIENT CONSOLE LOG: Connection closed

node client-IP.js
CLIENT CONSOLE LOG: Connected
CLIENT CONSOLE LOG: Received: SERVER WRITE: write
CLIENT WRITE: Hello, server! Love, Client.
CLIENT CONSOLE LOG: Connection closed
 -----------------------------------------------*/
```

**Comment by tomcon** [comment]
@sidorares did 2 tests using localhost and ip for both server and client & localhost version was waiting for 20 secs, interestingly both tests caused a SERVER CONSOLE.LOG: onerror Error: read ECONNRESET in response to the first client.write(). ran client a second time and ok
 
Rebooted and all ok again but I think it might have been related to - surprise, surprise - antivirus software as AVG had a "quiet" update it applied on the reboot too

**Comment by tomcon** [comment]
@sidorares had the problem again to do (nothing to do with AV it seems this time) but changing cfg to 127.0.0.1 from localhost fixed it immediately

**Comment by Hassanjankhan** [comment]
<img width="1091" alt="Screenshot 2023-07-13 at 01 38 02" src="https://github.com/sidorares/node-mysql2/assets/46195972/4e3be8c5-e378-4854-9bfa-b19246f1a2ad">


i am feed up from this , what would be the solution , i use localhost and also id address in the host variable.
any solution

**Comment by sidorares** [comment]
@Hassanjankhan can you try using ip address instead of localhost? The timeout might be caused by some delay in the dns system

**Comment by mfpereira** [comment]
@tomcon Thanks a lot man! 5 years later and the same error still happens! 
I had an entry in my /etc/hosts point to my IP address and ETIMEDOUT ocurred all the time. After changing to use IP address directly it worked like a charm!

**Comment by sidorares** [comment]
looks like for most users the issue is in the dns system configuration, closing this as not directly related to the driver code.
