### ISSUE TITLE
 Cannot read property 'extend' of undefined

### ISSUE THREAD

**Issue by GithubRyze** [sidorares/node-mysql2#666]
F:\NodeJs_project\myapp\node_modules\sequelize\lib\sequelize.js:144
    this.options = Utils._.extend({
                          ^

TypeError: Cannot read property 'extend' of undefined
    at new Sequelize (F:\NodeJs_project\myapp\node_modules\sequelize\lib\sequeli
ze.js:144:27)
    at Object.<anonymous> (F:\NodeJs_project\myapp\db\sequelizeDb.js:3:13)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (F:\NodeJs_project\myapp\controller\user.js:6:11)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (F:\NodeJs_project\myapp\routes\user.js:1:73)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
when require mysql2 then give me above exception? does anyone can tell why? how to fix??please help me

**Comment by sidorares** [comment]
Hi @GithubRyze  ! Which version of sequelize you are using? Latest code in master is a bit different - https://github.com/sequelize/sequelize/blob/34d075e2a5575108a037debcd66e814fd6dd5c4c/lib/sequelize.js#L148

From what I see sequelize project is probably better place to look for help with this

**Comment by GithubRyze** [comment]
thanks!! i have updated the sequelize to 4.22.0 then it is ok now!!

**Comment by GithubRyze** [comment]
thanks!! update to 4.22.0 and it is no this exception now!!
