### ISSUE TITLE
deadlock found when trying to get lock

### ISSUE THREAD

**Issue by terencechow** [sidorares/node-mysql2#690]
I am using `node/mysql` but looking to transition to node/mysql2 for prepared statements. When dropping in `node/mysql2` I get a deadlock found error that I didn't get when using `node/mysql`. I'm not sure why a deadlock would be received from using `mysql2` but not from `node/mysql`?
Any reason why this would fail for node/mysql2 but not mysql?

My code uses promises so I can't figure out why the result would be returned if the lock was not released. My code is like so:

```
import mysql from 'mysql2/promise'
const pool = mysql.createPool({...mysqlConfig})

// and it fails in my tests in my beforeEach calls which runs a cleanDB function:
// note this doesnt fail 100% of the time...only sometimes
export function cleanDb () {
  return pool.query('DELETE FROM table1;')
    .then(() => pool.query('DELETE FROM table2;'))
    .then(() => pool.query('DELETE FROM table3;'))
    .then(() => pool.query('DELETE FROM table4;'))
    .then(() => pool.query('DELETE FROM table5;'))
    .then(() => pool.query('DELETE FROM table6;'))
    .then(() => pool.query('DELETE FROM table7;')) 
    .then(() => pool.query('DELETE FROM table8;'))
    .then(() => pool.query('DELETE FROM table9;'))
    .then(() => pool.query('DELETE FROM table10;'))
    .catch(err => {
      console.log('err', err)
    })
}

```

 
error message:
```
{ Error: Deadlock found when trying to get lock; try restarting transaction
    at PromisePool.query (/Users/terencechow/workspace/my-project/node_modules/mysql2/promise.js:344:20)
    at /Users/terencechow/workspace/my-project/test/utils.js:71:22
    at bound (domain.js:280:14)
    at runBound (domain.js:293:12)
    at tryCatcher (/Users/terencechow/workspace/my-project/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/terencechow/workspace/my-project/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/terencechow/workspace/my-project/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/terencechow/workspace/my-project/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/terencechow/workspace/my-project/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/Users/terencechow/workspace/my-project/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/Users/terencechow/workspace/my-project/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/Users/terencechow/workspace/my-project/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
  message: 'Deadlock found when trying to get lock; try restarting transaction',
  code: 'ER_LOCK_DEADLOCK',
  errno: 1213,
  sqlState: '40001',
  sqlMessage: 'Deadlock found when trying to get lock; try restarting transaction' }
```

**Comment by terencechow** [comment]
Closing, this, looks like the issue was unrelated....
