### ISSUE TITLE
using STR_TO_DATE in prepared INSERT gives "Incorrect parameter count in the call to native function 'STR_TO_DATE'" error

### ISSUE THREAD

**Issue by ktravelet** [sidorares/node-mysql2#708]
I'm really really stuck on this, sorry if it's not related to the driver. 

slightly simplified:
```
const insertSql = 'insert into t1 values(STR_TO_DATE(?, '%c/%e/%Y'))'
const insertBinds = ['9/7/2016']

pool.query(insertSql, insertBinds, (err) => {
    if (err) {
        console.log(err)
    }
})

//Error: Incorrect parameter count in the call to native function 'STR_TO_DATE'
    at Packet.asError (***/node_modules/mysql2/lib/packets/packet.js:713:13)
    at Query.Command.execute (***/node_modules/mysql2/lib/commands/command.js:28:22)
    at PoolConnection.Connection.handlePacket (***/node_modules/mysql2/lib/connection.js:515:28)
    at PacketParser.onPacket (***/node_modules/mysql2/lib/connection.js:94:16)
    at PacketParser.executeStart (***/node_modules/mysql2/lib/packet_parser.js:77:14)
    at Socket.<anonymous> (***/node_modules/mysql2/lib/connection.js:102:29)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at addChunk (_stream_readable.js:266:12)
    at readableAddChunk (_stream_readable.js:253:11)
```

**Comment by sidorares** [comment]
are you sure your code is exactly as in example? Unescaped quotes make syntax error in `'insert into t1 values(STR_TO_DATE(?, '%c/%e/%Y'))'`

This example works fine for me:

```js
const sql = `SELECT STR_TO_DATE(?, '%c/%e/%Y')`;
conn.query(sql, ['9/7/2016'], (err, res) => {
        console.log(res);
});
```

**Comment by ktravelet** [comment]
Sorry about that, I simplified my case and assumed it would be the same.  Here's an actual working simplified case.  I left out the creating of the pool. 

```
async function main() {

    try {
        
        await createDatabase()
        await createTable()
        await insertData()

    } catch (error) {
        
        console.log(error)

    }

    try {
        
        await cleanup()

    } catch (error) {
        
        throw error

    }
    
    process.exit()

}


function createDatabase() {

    const sql = 'create schema if not exists test'

    console.log('creating database')

    return new Promise((resolve, reject) => {

        pool.query(sql, (err) => {

            if (err) {
                
                return reject(err)
    
            }
    
            console.log('database created')
    
            resolve(true)
    
        })

    })

}

function createTable() {

    console.log('creating table')

    const sql = 'create table if not exists test.t1 (TEST_STRING varchar(255), TEST_DATE DATE)'

    return new Promise((resolve, reject) => {

        pool.query(sql, (err) => {

            if (err) {
                
                return reject(err)
    
            }
    
            console.log('table created')
    
            resolve(true)
    
        })
        
    })

}

function insertData() {

    console.log('inserting data')

    const sql = 'insert into test.t1 (TEST_STRING, TEST_DATE) VALUES (?, STR_TO_DATE(?,\'%c/%e/%Y\'))'
    let data = []

    for (let i = 0; i < 10; i++) {

        data.push([String.fromCharCode(65+i), Math.floor((Math.random() * 12) + 1)+'/'+Math.floor((Math.random() * 28) + 1)+'/'+Math.floor(Math.random() * (2050 - 2010) + 2010)])

    }

    return new Promise((resolve, reject) => {

        pool.query(sql, data, (err, results) => {

            if (err) {
                
                return reject(err)
    
            }
    
            console.log('inserted ' + results.affectedRows + ' rows')
    
            resolve(true)
    
        })
        
    })

}

function cleanup() {

    console.log('cleaning up')

    const sql = 'drop schema if exists test'

    return new Promise((resolve, reject) => {

        pool.query(sql, (err) => {

            if (err) {
                
                return reject(err)
    
            }
    
            console.log('cleanup complete')
    
            resolve(true)
    
        })
        
    })

}

main()
```

Output:

> creating database
> database created
> creating table
> table created
> inserting data
> { Error: Incorrect parameter count in the call to native function 'STR_TO_DATE'
>     at Packet.asError (***/node_modules/mysql2/lib/packets/packet.js:713:13)
>     at Query.Command.execute (***/node_modules/mysql2/lib/commands/command.js:28:22)
>     at PoolConnection.Connection.handlePacket (***/node_modules/mysql2/lib/connection.js:515:28)
>     at PacketParser.onPacket (***/node_modules/mysql2/lib/connection.js:94:16)
>     at PacketParser.executeStart (***/node_modules/mysql2/lib/packet_parser.js:77:14)
>     at Socket.<anonymous> (***/node_modules/mysql2/lib/connection.js:102:29)
>     at emitOne (events.js:115:13)
>     at Socket.emit (events.js:210:7)
>     at addChunk (_stream_readable.js:266:12)
>     at readableAddChunk (_stream_readable.js:253:11)
>   code: 'ER_WRONG_PARAMCOUNT_TO_NATIVE_FCT',
>   errno: 1582,
>   sqlState: '42000',
>   sqlMessage: 'Incorrect parameter count in the call to native function \'STR_TO_DATE\'' }
> cleaning up
> cleanup complete

**Comment by sidorares** [comment]
So the sql you trying to execute after substitution looks like this: ` insert into test.t1 (TEST_STRING, TEST_DATE) VALUES ('A', '10/25/2037', STR_TO_DATE('B', '2/14/2040','%c/%e/%Y'))`

The reason is you passed following data as parameter: 
```
 [ [ 'A', '10/25/2037' ],
  [ 'B', '2/14/2040' ],
  [ 'C', '1/18/2012' ],
  [ 'D', '6/16/2046' ],
  [ 'E', '10/2/2039' ],
  [ 'F', '6/10/2016' ],
  [ 'G', '9/9/2045' ],
  [ 'H', '12/24/2031' ],
  [ 'I', '12/13/2021' ],
  [ 'J', '8/1/2021' ] ]
```

For a query `'insert into test.t1 (TEST_STRING, TEST_DATE) VALUES (?, STR_TO_DATE(?,\'%c/%e/%Y\'))'` first element from data array ( `[ 'A', '10/25/2037' ]` ) goes into first placeholder and second element `  [ 'B', '2/14/2040' ]` goes into second placeholder

**Comment by ktravelet** [comment]
ok, I see whats going on.  I'm trying to do a bulk insert here and it looks like for bulk inserts the prepared statement is always `VALUES ?` regardless the number of parameters passed.  This would prevent any kind of manipulation of the data.  Any idea how to get around this?

**Comment by sidorares** [comment]
I assume you are talking about client side placeholder substitution, not prepared statements as in https://dev.mysql.com/doc/apis-php/en/apis-php-mysqli.quickstart.prepared-statements.html

I'd probably use `SqlString.raw()`:

```js

const SqlString = require('sqlstring');
function insertData() {

    console.log('inserting data')

    const sql = 'insert into test.t1 (TEST_STRING, TEST_DATE) VALUES ?'
    let data = []

    for (let i = 0; i < 10; i++) {

        data.push([String.fromCharCode(65+i), 
          SqlString.raw('STR_TO_DATE(' + Math.floor((Math.random() * 12) + 1)+'/'+Math.floor((Math.random() * 28) + 1)+'/'+Math.floor(Math.random() * (2050 - 2010) + 2010) + ',\'%c/%e/%Y\)')
        ])
    }

    return new Promise((resolve, reject) => {

        pool.query(sql, [data], (err, results) => {

            if (err) {
                
                return reject(err)
    
            }
    
            console.log('inserted ' + results.affectedRows + ' rows')
    
            resolve(true)
    
        })
        
    })

}

```
