### ISSUE TITLE
Node exitting without further notice when trying to run query through dead connection

### ISSUE THREAD

**Issue by elhigu** [sidorares/node-mysql2#729]
Hi @sidorares 

I'm again debugging stability issues when running knex with all the different db drivers and when DB connection is cut down every now and then.

I have docker setup for databases and TCP proxy in front of database to be able to cut connections when ever I want to. 

I found out that when I have connection which has been closed in my hand and try to run query through it, process just exits without printing out any exceptions or any information what happened.

Test code / environment are as follows:

mysql2@1.5.2
mysql@2.15.0
node v8.9.0

docker-compose.yml (starts mysql (33306) + toxiproxy (23306))

```yaml
version: '3'

services:
  toxiproxy:
    image: shopify/toxiproxy
    ports:
      - "8474:8474"
      - "23306:23306"
    links:
      - "mysql"

  mysql:
    image: mysql:5.7
    ports:
      - "33306:3306"
    environment:
      - TZ=UTC
      - MYSQL_ROOT_PASSWORD=mysqlrootpassword
```

test.js (for node >= 8) (sorry this is rather long, but most of the stuff is just initializations for proxy etc. beef is in the main() function)

```js
const Bluebird = require('bluebird');
const toxiproxy = require('toxiproxy-node-client');
const toxicli = new toxiproxy.Toxiproxy('http://localhost:8474');
const rp = require('request-promise-native');

// drops old toxicproxy and creates new
async function recreateProxy(serviceName, listenPort, proxyToPort) {
  try {
    await rp.delete({
      url: `${toxicli.host}/proxies/${serviceName}`
    });  
  } catch(err) {
    // there was no proxy by that name... its ok
  }

  const proxy = await toxicli.createProxy({
    name: serviceName,
    listen: `0.0.0.0:${listenPort}`,
    upstream: `${serviceName}:${proxyToPort}`
  });
}

async function insanelyParanoidQuery(con) {
  console.log('sending query');
  const res = await new Promise((resolve,reject) => {
    try {
      con.query('select 1', [],  function(err, rows, fields) {
        if (err) {
          reject(err);
        } else {
          resolve(rows);
        }
      });
    } catch(err) {
      console.log('Huh synchronous exception?! (shouldnt be possible)');
      reject(err);
    }
  });
  console.log(res);
}


async function main() {
  // create proxy from localhost:23306 -> mysqldocker:3306
  await recreateProxy('mysql', 23306, 3306);

  // ------------- setup mysql2 db driver connection
  const mysql2 = require('mysql2'); // with mysql this works...
  const mysql2Con = await mysql2.createConnection({
    host: 'localhost',
    user: 'root',
    password: 'mysqlrootpassword',
    port: 23306
  });

  mysql2Con.on('error', function(err) {
    console.log("I'm dead", err);
  })
  
  console.log('Going to cut connections');

  // cut connection during recreate
  await recreateProxy('mysql', 23306, 3306);

  console.log('Proxy recreated... start waiting');

  // wait forever
  while(true) {
    await Bluebird.delay(1000);
    try {
      await insanelyParanoidQuery(mysql2Con);
    } catch (err) {
      console.log('query failed:', err);
    }
    await recreateProxy('mysql', 23306, 3306);
  }
}

main()
  .then(() => console.log('Process stopped normally'))
  .catch(err => {
    console.log('Process stopped to failure', err);
  })

console.log('Waiting for eventloop to stop...');

process.on('uncaughtException', function (err) {
  console.log('uncaughtException', err);
});

process.on('exit', function () {
  console.log('Did someone call process.exit() or wat? exitCode:', process.exitCode);
});
```

Running (need docker host on your machine) :
```
docker-compose up --no-start
docker-compose start
node test.js
```

outputs:
```
Mikaels-MacBook-Pro-2:stress-test mikaelle$ node test.js 
Waiting for eventloop to stop...
Going to cut connections
I'm dead { Error: Connection lost: The server closed the connection.
    at Socket.<anonymous> (/Users/mikaelle/Projects/Vincit/knex/node_modules/mysql2/lib/connection.js:100:35)
    at emitNone (events.js:111:20)
    at Socket.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1056:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9) fatal: true, code: 'PROTOCOL_CONNECTION_LOST' }
Proxy recreated... start waiting
sending query
Did someone call process.exit() or wat? exitCode: undefined
Mikaels-MacBook-Pro-2:stress-test mikaelle$ 
```

If I run the same code, but with mysql driver it prints out following (query throws an exception, but process does not exit):

```
Mikaels-MacBook-Pro-2:stress-test mikaelle$ node mysql2-fail.js 
Waiting for eventloop to stop...
Going to cut connections
Proxy recreated... start waiting
sending query
[ RowDataPacket { '1': 1 } ]
I'm dead { Error: Connection lost: The server closed the connection.
    at Protocol.end (/Users/mikaelle/Projects/Vincit/knex/node_modules/mysql/lib/protocol/Protocol.js:113:13)
    at Socket.<anonymous> (/Users/mikaelle/Projects/Vincit/knex/node_modules/mysql/lib/Connection.js:109:28)
    at emitNone (events.js:111:20)
    at Socket.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1056:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9) fatal: true, code: 'PROTOCOL_CONNECTION_LOST' }
sending query
query failed: { Error: Cannot enqueue Query after fatal error.
    at Protocol._validateEnqueue (/Users/mikaelle/Projects/Vincit/knex/node_modules/mysql/lib/protocol/Protocol.js:201:16)
    at Protocol._enqueue (/Users/mikaelle/Projects/Vincit/knex/node_modules/mysql/lib/protocol/Protocol.js:139:13)
    at Connection.query (/Users/mikaelle/Projects/Vincit/knex/node_modules/mysql/lib/Connection.js:208:25)
    at Promise (/Users/mikaelle/Projects/Vincit/knex/scripts/stress-test/mysql2-fail.js:27:11)
    at new Promise (<anonymous>)
    at insanelyParanoidQuery (/Users/mikaelle/Projects/Vincit/knex/scripts/stress-test/mysql2-fail.js:25:21)
    at main (/Users/mikaelle/Projects/Vincit/knex/scripts/stress-test/mysql2-fail.js:71:13)
    at <anonymous> code: 'PROTOCOL_ENQUEUE_AFTER_FATAL_ERROR', fatal: false }
sending query
query failed: { Error: Cannot enqueue Query after fatal error.
    at Protocol._validateEnqueue (/Users/mikaelle/Projects/Vincit/knex/node_modules/mysql/lib/protocol/Protocol.js:201:16)
    at Protocol._enqueue (/Users/mikaelle/Projects/Vincit/knex/node_modules/mysql/lib/protocol/Protocol.js:139:13)
    at Connection.query (/Users/mikaelle/Projects/Vincit/knex/node_modules/mysql/lib/Connection.js:208:25)
    at Promise (/Users/mikaelle/Projects/Vincit/knex/scripts/stress-test/mysql2-fail.js:27:11)
    at new Promise (<anonymous>)
    at insanelyParanoidQuery (/Users/mikaelle/Projects/Vincit/knex/scripts/stress-test/mysql2-fail.js:25:21)
    at main (/Users/mikaelle/Projects/Vincit/knex/scripts/stress-test/mysql2-fail.js:71:13)
    at <anonymous> code: 'PROTOCOL_ENQUEUE_AFTER_FATAL_ERROR', fatal: false }
^C
Mikaels-MacBook-Pro-2:stress-test mikaelle$ 
```

**Comment by sidorares** [comment]
thanks for detailed report @elhigu ! Still debugging this, currently suspect socket.write call doing some kind of `writeAfterFin` error but not sure yet why this can cause process to exit

**Comment by elhigu** [comment]
Great! Yup, that kind of process just exit without any error seemed really strange. @sidorares were you able to reproduce the problem with that code? I found out also another problem with mysql2 hanging in some cases, but I'm still trying to write better testcase to show it + get some debug logs of the exact moment when queries hang.

**Comment by sidorares** [comment]
yes, I can reproduce the problem, it's quite strange but I'm sure we'll find root cause ( strange because I'd expect at least crash with unhandled exception if error handlers not properly set and we have silent exit )

**Comment by sidorares** [comment]
@elhigu for some reasone stopped to see this behaviour yesterday. I guess it's some kind of race condition so not very reliable. What's your setup? (I tried on windows 10 + db and proxy inside docker for windows )

**Comment by elhigu** [comment]
I'm on OSX 10.13.1 and running docker with docker.app. I could try to setup container also for running the node. That way also that env will be more stable. I'm still getting the same functionality of app crashing (just tried it out few minutes ago).

**Comment by sidorares** [comment]
I'll try on my mac later today

**Comment by elhigu** [comment]
I cannot reproduce this anymore either. I'll reopen if I'm able to make this happen again.
