### ISSUE TITLE
queue.removeOne is not a function

### ISSUE THREAD

**Issue by danieljuhl** [sidorares/node-mysql2#740]
On our CI I've started to see the below error. I assume there is a flaky network connection to the database itself.

```
TypeError: queue.removeOne is not a function
        at spliceConnection (./node_modules/mysql2/lib/pool.js:222:13)
        at Pool.Object.<anonymous>.Pool._removeConnection (./node_modules/mysql2/lib/pool.js:189:3)
        at PoolConnection.Object.<anonymous>.PoolConnection._removeFromPool (./node_modules/mysql2/lib/pool_connection.js:59:8)
        at PoolConnection.<anonymous> (./node_modules/mysql2/lib/pool_connection.js:22:10)
        at emitOne (events.js:121:20)
        at PoolConnection.emit (events.js:211:7)
        at PoolConnection.Object.<anonymous>.Connection._notifyError (./node_modules/mysql2/lib/connection.js:229:16)
        at PoolConnection.Object.<anonymous>.Connection._handleFatalError (./node_modules/mysql2/lib/connection.js:165:14)
        at PoolConnection.Object.<anonymous>.Connection._handleNetworkError (./node_modules/mysql2/lib/connection.js:170:8)
        at PoolConnection.Object.<anonymous>.Connection._handleTimeoutError (./node_modules/mysql2/lib/connection.js:186:8)
        at ontimeout (timers.js:475:11)
        at tryOnTimeout (timers.js:310:5)
        at Timer.listOnTimeout (timers.js:270:5)
```

**Comment by sidorares** [comment]
interesting. Can you check what version of `denque` you have installed?

**Comment by sidorares** [comment]
removeOne was added relatively recently: https://github.com/invertase/denque/commit/2ec7bb4ba8407bb1a27e9ecb763ba56c3e0728cf

**Comment by sidorares** [comment]
that's very strange, because 1.2.3 has removeOne

**Comment by danieljuhl** [comment]
I was playing around last night with the issue - so it is possible that I have re-installed all my deps. I'll try to see if I can reproduce the issue.

**Comment by danieljuhl** [comment]
Even with the latest versions installed, I just saw this error from our production error logging. I haven't been able to re-pro, but it looks like fresh install isn't enough

**Comment by sidorares** [comment]
sorry @danieljuhl that was still not yet actioned, need to release new version with `denque@1.2.3` as minimum dep version

**Comment by wellwelwel** [comment]
Fixed in d69a95a6 (released in v1.5.3) 🙋🏻‍♂️
