### ISSUE TITLE
Not doing queries and no errors

### ISSUE THREAD

**Issue by SimonBroos** [sidorares/node-mysql2#757]
I followed the first query example and it's not working and not giving any errors. Maybe it's because my database is on a different port than default.

My code
```javascript
const mysql = require('mysql2');

const connection = mysql.createConnection(
    {
    host: 'database host',
    port: '6033',
    user:'clippie',
    password:'clippe password',
    database: 'clippie',
    }
);

connection.query(
    'SELECT * FROM questions',
    function(err, results){
        if(err) throw err;
        console.log('getting questions');
        console.log(results);
});
```
I tested this with mysql package and worked like it should but for what i'm maknig i need prepared statements what mysql not supports.

**Comment by sidorares** [comment]
Can you check that you do have access to 'database host':6033 ? 

```js
net.connect(6033, 'database host').on('connect', () => console.log('connected!'))
```

**Comment by sidorares** [comment]
also try to connect with `debug` flag on:

```js
const mysql = require('mysql2');

const connection = mysql.createConnection(
    {
    debug: true,
    host: 'database host',
    port: '6033',
    user:'clippie',
    password:'clippe password',
    database: 'clippie',
    }
);

connection.query(
    'SELECT * FROM questions',
    function(err, results){
        if(err) throw err;
        console.log('getting questions');
        console.log(results);
});
```

**Comment by SimonBroos** [comment]
I just test my connection and added the `debug` flag

```
Add command: Connection
Add command: query
connected!
 raw: 0a31302e312e32340045cc00002e2e397668282c42002ab22102000f8015000000000000000000004a2d3e31782e772f25665556006d7973716c5f6e61746976655f70617373776f726400
Trace
    at Connection.handlePacket (C:\Users\Simon\Desktop\teamsbotbuilder\node_modules\mysql2\lib\connection.js:472:15)
    at PacketParser.onPacket (C:\Users\Simon\Desktop\teamsbotbuilder\node_modules\mysql2\lib\connection.js:81:16)
    at PacketParser.executeStart (C:\Users\Simon\Desktop\teamsbotbuilder\node_modules\mysql2\lib\packet_parser.js:77:14)
    at Socket.<anonymous> (C:\Users\Simon\Desktop\teamsbotbuilder\node_modules\mysql2\lib\connection.js:89:29)
    at Socket.emit (events.js:160:13)
    at addChunk (_stream_readable.js:269:12)
    at readableAddChunk (_stream_readable.js:256:11)
    at Socket.Readable.push (_stream_readable.js:213:10)
    at TCP.onread (net.js:602:20)
0 undefined ==> Connection#handshakeInit(0,,79)
Server hello packet: capability flags:2148512298=(found rows, connect with db, compress, protocol 41, ignore sigpipe, transactions, secure connection, multi statements, multi results, ps multi results, plugin auth, remember options)
Sending handshake packet: flags:8582095=(long password, found rows, long flag, connect with db, odbc, local files, ignore space, protocol 41, ignore sigpipe, transactions, reserved, secure connection, multi results, session track)
0 52293 <== Connection#handshakeInit(1,,73)
0 52293 <== 45000001cff3820000000000e00000000000000000000000000000000000000000000000636c6970706965001453480d70cbbb23287140afe079d4d4b52da1853c636c697070696500
 raw: 00000000000000
Trace
    at Connection.handlePacket (C:\Users\Simon\Desktop\teamsbotbuilder\node_modules\mysql2\lib\connection.js:472:15)
    at PacketParser.onPacket (C:\Users\Simon\Desktop\teamsbotbuilder\node_modules\mysql2\lib\connection.js:81:16)
    at PacketParser.executeStart (C:\Users\Simon\Desktop\teamsbotbuilder\node_modules\mysql2\lib\packet_parser.js:77:14)
    at Socket.<anonymous> (C:\Users\Simon\Desktop\teamsbotbuilder\node_modules\mysql2\lib\connection.js:89:29)
    at Socket.emit (events.js:160:13)
    at addChunk (_stream_readable.js:269:12)
    at readableAddChunk (_stream_readable.js:256:11)
    at Socket.Readable.push (_stream_readable.js:213:10)
    at TCP.onread (net.js:602:20)
0 52293 ==> Connection#handshakeResult(2,maybeOK,11)
        Sending query command: SELECT * FROM questions
0 52293 <== query#start(0,,28)
0 52293 <== 180000000353454c454354202a2046524f4d207175657374696f6e73
```

And these are the results. Still no errors

**Comment by sidorares** [comment]
So the last line is outgoing "SELECT * FROM questions" command. Normally server respond with OK, then column definition for each column and then rows. Is `180000000353454c454354202a2046524f4d207175657374696f6e73` the last line you see and then nothing after that? You definitely can connect to db and authenticate. What is your server version?

**Comment by SimonBroos** [comment]
yes, `180000000353454c454354202a2046524f4d207175657374696f6e73` is the last line i get
node version: 6.12.3
db: 10.1.31-MariaDB

**Comment by SimonBroos** [comment]
Small update on my problem

When run the exmaple code, the database log get spammed with "SET NAME" command or something like that if i remember right. Until we stop the node server. 

i made a local mariaDB same version as the one i connect with on the server. When i run the example code on localhost it works perfectly fine.

i don't know if any of this info helps.

**Comment by sidorares** [comment]
can you check process id of connection that is doing SET NAMES utf8mb4' query and compare with your connection id ( you can see it as `connection.threadId` after you connect )

**Comment by SimonBroos** [comment]
the process id of the connection that does the `SET NAMES uft8mb4` is 248575
My connection id i get with `connection.threadId` is 19438.

**Comment by sidorares** [comment]
this mean that some other connection is doing this.

**Comment by SimonBroos** [comment]
The SET NAME only starts when i do a query from my program. When i stop my program the SET NAME spam stops aswell. I don't understand why it does that

**Comment by sidorares** [comment]
Can you add console.log somewhere in the driver code to see all commands? Lib/connection.js addCommand ( or maybe change part where debug flag is set and force it to be on)

**Comment by SimonBroos** [comment]
I was not sure what i had to console.log. i logged `this._command` and added `|| true` to the debug.
The results in the console is this

```
Add command: Connection
ClientHandshake {
  handshake: null,
  clientFlags: 8582095,
  domain: null,
  _events: { end: [Function], error: [Function] },
  _eventsCount: 2,
  _maxListeners: undefined,
  next: [Function],
  _commandName: 'Connection' }
```

**Comment by SimonBroos** [comment]
oops, closed by accident

**Comment by sidorares** [comment]
if you don't see Query commands constantly in the log it means it's not this driver doing `SET NAMES` requests

**Comment by SimonBroos** [comment]
I talked with my coworker that manage all the database here. 

He said the `SET NAME uft8mb4`Should only happen once by the database when making connection with the database.
For me it keeps happening very fast in a infinite loop when doing a query.
The process ID of the `SET NAMES` process is the ID of my database process.

If it helps as info we use a proxysql for the database but normally that shouldn't be a problem.
