### ISSUE TITLE
Passing Empty String as Value Directly Throws

### ISSUE THREAD

**Issue by anliting** [sidorares/node-mysql2#761]
Code:

```js
import mysql2 from 'mysql2'
mysql2.createPool({
    host:'localhost',
    user:'anliting',
    password:'',
}).query('select ?','',(err,res)=>{
    console.log(err)
})
```

Expected: No error.

Actual:
```
{ Error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '?' at line 1
    at Packet.asError (/home/anliting/node_modules/mysql2/lib/packets/packet.js:716:13)
    at Query.Command.execute (/home/anliting/node_modules/mysql2/lib/commands/command.js:28:22)
    at PoolConnection.Connection.handlePacket (/home/anliting/node_modules/mysql2/lib/connection.js:502:28)
    at PacketParser.onPacket (/home/anliting/node_modules/mysql2/lib/connection.js:81:16)
    at PacketParser.executeStart (/home/anliting/node_modules/mysql2/lib/packet_parser.js:77:14)
    at Socket.<anonymous> (/home/anliting/node_modules/mysql2/lib/connection.js:89:29)
    at Socket.emit (events.js:180:13)
    at addChunk (_stream_readable.js:274:12)
    at readableAddChunk (_stream_readable.js:261:11)
    at Socket.Readable.push (_stream_readable.js:218:10)
  code: 'ER_PARSE_ERROR',
  errno: 1064,
  sqlState: '42000',
  sqlMessage: 'You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near \'?\' at line 1' }
```

**Comment by SpencerTuft** [comment]
The second parameter in the query function should be an array of values. Try: `import mysql2 from 'mysql2'
mysql2.createPool({
    host:'localhost',
    user:'anliting',
    password:'',
}).query('select ?',[''],(err,res)=>{
    console.log(err)
})`
