### ISSUE TITLE
Throw an error when a connection ends with a RST,ACK packet?

### ISSUE THREAD

**Issue by elemount** [sidorares/node-mysql2#766]
Hi,

I'm using Azure MySQL database.

According to MySQL docs, COM_QUIT command should end with "either a connection close or a OK_Packet".

It can be reproduced when you run this example code against an Azure MySQL instance.
```js
var mysql      = require('mysql2');
var connection = mysql.createConnection({ config });

connection.connect();

connection.query('SELECT 1 + 1 AS solution', function (error, results, fields) {
  if (error) throw error;
  console.log('The solution is: ', results[0].solution);
});

connection.end();
```

Throws `ECONNRESET` error.

Should this library throw an error when a connection end with a RST with the ACK flag set?
Can we detect this?

I see mysqljs already fixed it at commit https://github.com/mysqljs/mysql/commit/9168ced54148721c8872ddab583116f00b4bc4f8 .
But we prefer using mysql2 now and it block me. Could mysql2 fix it either?

**Comment by sidorares** [comment]
probably fix should be here - https://github.com/sidorares/node-mysql2/blob/5c5aa3aed7e772e599dbefdafb04405672901808/lib/connection.js#L123

if already `_closing`, ignore error ( same way `.end()` is expected when this flag set on line 94 )

**Comment by sidorares** [comment]
would you be able to apply this fix and check @elemount ?

**Comment by elemount** [comment]
@sidorares , I'm not sure if it is already in the newest release. 
I can repo it by following steps.
1. Create a folder and cd it.
2. 
```
npm install mysql2
npm install knex
``` 
3. Save this scripts as file `test.js`
```js
const knex = require('knex');

async function run() {
    const db = knex({
        client: 'mysql2',
        connection: {
            user: "elemount@elemount-test",
            password: "Testmysql2",
            host: "elemount-test.mysql.database.azure.com",
            port: 3306,
            database: "test",
        }
    });

    await db.schema.dropTableIfExists('test');
    await db.schema.createTable('test', table => {
        table.increments('id').primary();
        table.integer('key1');
    });
    db.destroy();
}

run();
```
4. `node test.js`

And then I will got 
```
events.js:165
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at TCP.onread (net.js:602:25)
Emitted 'error' event at:
    at Connection._notifyError (D:\Play\repo\node_modules\mysql2\lib\connection.js:229:16)
    at Connection._handleFatalError (D:\Play\repo\node_modules\mysql2\lib\connection.js:165:14)
    at Connection._handleNetworkError (D:\Play\repo\node_modules\mysql2\lib\connection.js:170:8)
    at Socket.emit (events.js:180:13)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at process._tickCallback (internal/process/next_tick.js:178:19)
```

I'm using Node `v9.11.1`.
And mysql2 package is
```js
    "mysql2": {
      "version": "1.5.3",
      "resolved": "https://registry.npmjs.org/mysql2/-/mysql2-1.5.3.tgz",
      "integrity": "sha512-Oov36YQSeciNP9SeqE7je4eWgeGADOorXLmsqhtxOJmPGUOJSNJT0s6/eq1Byy4nhXTRQUvlMHsI4Q/eMEs88Q==",
      "requires": {
        "cardinal": "1.0.0",
        "denque": "1.2.3",
        "generate-function": "2.0.0",
        "iconv-lite": "0.4.21",
        "long": "4.0.0",
        "lru-cache": "4.1.1",
        "named-placeholders": "1.1.1",
        "object-assign": "4.1.1",
        "readable-stream": "2.3.5",
        "safe-buffer": "5.1.1",
        "seq-queue": "0.0.5",
        "sqlstring": "2.3.1"
      }
    },
```

**Comment by elemount** [comment]
The server and password is real. And you can repo it on your machine I believe.

**Comment by sidorares** [comment]
I haven't changed anything yet, just suggested that maybe you can try to make this change

**Comment by sidorares** [comment]
Actually not that error handler, it should be in `_handleNetworkError`

```js
Connection.prototype._handleNetworkError = function(err) {
  if (this._closing) {
    return;
  }
  this._handleFatalError(err);
};
```

https://github.com/sidorares/node-mysql2/blob/5c5aa3aed7e772e599dbefdafb04405672901808/lib/connection.js#L169

**Comment by elemount** [comment]
I used the code in the `_handleNetworkError` and now it works. 
I raised a pull request on it.
