### ISSUE TITLE
Attempt to open two mysqlPools via socketPath fails

### ISSUE THREAD

**Issue by smulder** [sidorares/node-mysql2#781]
When I try to open two mysqlPools as below it fails, error and explanation after:

```
env_settings = {

			mysqlParams: {
				connectionLimit: 1000,
				client: credentials.gCloudMysql.client,
				database: credentials.gCloudMysql.db,
				user: credentials.gCloudMysql.user,
				password: credentials.gCloudMysql.password
			},
			mysqlSlaveParams: {
				connectionLimit: 1000,
				client: credentials.gCloudMysqlSlave.client,
				database: credentials.gCloudMysqlSlave.db,
				user: credentials.gCloudMysqlSlave.user,
				password: credentials.gCloudMysqlSlave.password
			}
		};
		if (process.env.INSTANCE_CONNECTION_NAME) {
			env_settings.mysqlParams.socketPath = '/cloudsql/' + process.env.INSTANCE_CONNECTION_NAME;
		}
		if (process.env.SLAVE_INSTANCE_CONNECTION_NAME) {
			env_settings.mysqlSlaveParams.socketPath = '/cloudsql/' + process.env.SLAVE_INSTANCE_CONNECTION_NAME;
		}
```

```
var mysqlPool = mysql.createPool(env_settings.mysqlParams);
var mysqlReadPool = mysql.createPool(env_settings.mysqlSlaveParams);
```

The fatal (to mysql) error is summed up with this:

```
{ Error: connect ENOENT /cloudsql/[PRIVATE_SOCKET_CONNECTION_STRING_REMOVED] at Object._errnoException (util.js:1022:11) at _exceptionWithHostPort (util.js:1044:20) at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
```

What I am trying to accomplish is a pool which connects to our read-replica and a pool that connects to the master to speed reads up.

Am I doing something obviously wrong? It's almost as though it's running into a port in use thing, but I haven't dug into the mysql2 code deep enough to understand the above error.

**Comment by smulder** [comment]
Hey, I think I got it working, and I guess this will be here for anyone who tries this in the future.

When you want two unix sockets to Google CloudSQL on AppEngine you have to submit them both comment delimited in the app.yaml file like below:

```
beta_settings:
  cloud_sql_instances: 'PRIVATE_CONNECTION_STRING1-MASTER,PRIVATE_CONNECTION_STRING1-REPLICA'
```

Thanks tons for your awesome module and being around to ask questions!
