### ISSUE TITLE
ECONNREFUSED  openshift mysql

### ISSUE THREAD

**Issue by Cariaga** [sidorares/node-mysql2#797]
{ Error: connect ECONNREFUSED 127.0.0.1:3306
--
  | at Object._errnoException (util.js:1022:11)
  | at _exceptionWithHostPort (util.js:1044:20)
  | at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14)
  | code: 'ECONNREFUSED',
  | errno: 'ECONNREFUSED',
  | syscall: 'connect',
  | address: '127.0.0.1',
  | port: 3306,
  | fatal: true }

**Comment by Cariaga** [comment]
Solved it 
get the ip from services tab in openshift cluster ip

```
const connection = mysql.createConnection({
    host     : 'mycluster ip',
    user     : 'user during creation of mysql',
    password : 'password during creation of project',
    port     : process.env.OPENSHIFT_MYSQL_DB_PORT or the 3306,
    database : 'sampledb'
  });
```
