### ISSUE TITLE
SyntaxError: Unexpected identifier with Promise Wrapper

### ISSUE THREAD

**Issue by KonScyence** [sidorares/node-mysql2#828]
Hello, this is the first time I use node.js with mysql. I'm trying to use the promise wrapper, but I can not even get the demo code working ... I've really tried a lot of things, could someone please tell me where do I get plant and explain to me please?

JS Code:
```js
var mysql = require('mysql2/promise');
const bluebird = require('bluebird');

const connection = await mysql.createConnection({host:'localhost', user: 'root', database: 'test', Promise: bluebird});

await connection.query( 'SELECT grade FROM `students` WHERE `name` = ?', ['ken'], function(err, results) {
    console.log(results);
});
```

Error:
```
const connection = await mysql.createConnection({host:'localhost', user: 'root', database: 'test', Promise: bluebird});
                         ^^^^^

SyntaxError: Unexpected identifier
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:599:28)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
```

Regards

**Comment by sidorares** [comment]
you can only `await` inside async function, and in node "main" code is wrapped in normal non-async function, this is the reason you getting syntax error.

There is a lot of context on this topic here - https://github.com/tc39/proposal-top-level-await

**Comment by sidorares** [comment]
try following code:

```js
var mysql = require('mysql2/promise');
const bluebird = require('bluebird');

async function main() {
  const connection = await mysql.createConnection({host:'localhost', user: 'root', database: 'test', Promise: bluebird});
  const results = await connection.query( 'SELECT grade FROM `students` WHERE `name` = ?', ['ken']);
  console.log(results);
}

main().catch(err => {
  console.log('Error!', err); // ^ this is optional, if your async code throws and you don't have error handler you'll get 'UnhandledPromiseRejectionWarning' error
})
```

also you mix async and callback flow - async api does not expect callback parameter and will ignore it ( we should probably try detect this and warn users, you are not the first who tried this )
