### ISSUE TITLE
v1.6.2 throws on getConnection when using createPoolCluster

### ISSUE THREAD

**Issue by watson** [sidorares/node-mysql2#869]
When creating a `cluster` using `mysql.createPoolCluster()` the call to `cluster.getConnection()` throws in 1.6.2. This worked fine in previous versions of mysql2.

Run the following code to reproduce the bug:

```js
const mysql = require('mysql2')

const cluster = mysql.createPoolCluster()

cluster.add({ host: 'localhost', user: 'root', database: 'test' })

// This call throws
cluster.getConnection(function (err, conn) {
  if (err) throw err
  console.log('success!')
})
```

This code will throw the following error:

```
/tmp/node_modules/mysql2/lib/pool_cluster.js:36
    this._selector = new Selector[selector]();
                     ^

TypeError: Selector[selector] is not a constructor
    at new PoolNamespace (/tmp/node_modules/mysql2/lib/pool_cluster.js:36:22)
    at PoolCluster.of (/tmp/node_modules/mysql2/lib/pool_cluster.js:96:31)
    at PoolCluster.getConnection (/tmp/node_modules/mysql2/lib/pool_cluster.js:121:24)
    at Object.<anonymous> (/tmp/test.js:8:9)
    at Module._compile (internal/modules/cjs/loader.js:707:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:718:10)
    at Module.load (internal/modules/cjs/loader.js:605:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:544:12)
    at Function.Module._load (internal/modules/cjs/loader.js:536:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:760:12)
```

**Comment by sidorares** [comment]
might be a regression caused by https://github.com/sidorares/node-mysql2/commit/4903428e2a0bf5482e4dfbfb1a9fd7367de05635  @SimonSchick

**Comment by sidorares** [comment]
really not sure why `new` here: https://github.com/sidorares/node-mysql2/blob/7c7fbf867e0c8e7f0c392de89a13f43af1418738/lib/pool_cluster.js#L36

**Comment by SimonSchick** [comment]
Yea, I just traced this, operator precisende here is super weird, to give you an example: 
```
> s = { a: function () { return () => 1; } }
{ a: [Function: a] }
> b = new s['a']()()
1
```

```
> s = { a() { return () => 1; } }
{ a: [Function: a] }
> b = new s['a']()()
TypeError: s.a is not a constructor
```

I'm suprised this worked at all lol.

**Comment by sidorares** [comment]
Unfortunately pool_cluster is not covered by tests, is not my code and I never used it myself (and looks like it's used by others)
I guess fix here is to remove `new`. Selector[strategy] is just a function that returns fresh selector function

**Comment by SimonSchick** [comment]
So, this is interesting, when you return an `object` type from _any_ constructor it overrides the returned value, this is what happened here.
JS can be completely dumb sometimes...

**Comment by sidorares** [comment]
yes, constructor can return any instance, not exactly "this". ( I actually used that once )

**Comment by sidorares** [comment]
https://github.com/sidorares/ntk/blob/c6233582c82b51b84ed6ae2d6e9f6735e23964bd/lib/window.js#L17

**Comment by SimonSchick** [comment]
Anyhow, @sidorares I suggest you rename `Selector` to `selector` to avoid class ambiguity and remove the `new` keyword, that should fix it :)

**Comment by SimonSchick** [comment]
That said, I apologize for causing this regression, but I'd never seen that one coming 😛

**Comment by sidorares** [comment]
@watson please try v1.6.3

**Comment by SimonSchick** [comment]
@sidorares might as well delete version 1.6.2 if possible :)

**Comment by watson** [comment]
@sidorares works now, thanks 👍
