### ISSUE TITLE
ETIMEDOUT when running node service in kubernetes container

### ISSUE THREAD

**Issue by mhdnp1234** [sidorares/node-mysql2#917]
mysql is running in local machine.  I am running my node service in minikube cluster. I am passing my machine's IP address as environment to node service but it fails. 
When i am running node service locally, it is working properly.

```events.js:173
      throw er; // Unhandled 'error' event
      ^
Error: connect ETIMEDOUT
    at Connection._handleTimeoutError (/usr/src/app/node_modules/mysql2/lib/connection.js:173:17)
    at listOnTimeout (timers.js:324:15)
    at processTimers (timers.js:268:5)
Emitted 'error' event at:
    at Connection._notifyError (/usr/src/app/node_modules/mysql2/lib/connection.js:219:18)
    at Connection._handleFatalError (/usr/src/app/node_modules/mysql2/lib/connection.js:155:16)
    at Connection._handleNetworkError (/usr/src/app/node_modules/mysql2/lib/connection.js:164:10)
    at Connection._handleTimeoutError (/usr/src/app/node_modules/mysql2/lib/connection.js:177:10)
    at listOnTimeout (timers.js:324:15)
    at processTimers (timers.js:268:5)```

**Comment by sidorares** [comment]
Can you check if you have similar behaviour with `mysqljs/mysql` driver? Might be issue outside of this library ( network setup, db access rules etc )

**Comment by mhdnp1234** [comment]
@sidorares  I have checked with this too. you are right, it seems other issue. Thank you for your response.

**Comment by mhdnp1234** [comment]
Wow, so when i run local docker container for mysql, my minikube cluster is able to access the database. But it is not working when running mysql locally. that is crazy.  any idea what could affect the connection?

**Comment by mhdnp1234** [comment]
it is not related to mysql issue for sure. so, closing the issue.

**Comment by sidorares** [comment]
Check what network minikube cluster is using, also what is port mapping

**Comment by mhdnp1234** [comment]
it's all appropriate, minikube network setting does not seems issue, because it work for 1 db out side (in docker) and does not work other db (locally).

**Comment by malimccalla** [comment]
@mhdnp1234 Did you get to the bottom of this? I'm having a similar issue

**Comment by mhdnp1234** [comment]
@malimccalla no I did not find any solution.  I started using mysql docker instead of local mysql.
