### ISSUE TITLE
ER_ACCESS_DENIED_ERROR when using socketPath

### ISSUE THREAD

**Issue by marcino239** [sidorares/node-mysql2#942]
Not sure if this is my config, but I am using stock mysql 5.7 on ubuntu 18.04 with nodejs 10.15.2.
I get ER_ACCESS_DENIED_ERROR for this code:
```
> var d = require( 'mysql2' )
> var c = d.createConnection({ database: 'kitchen', socketPath: '/var/run/mysqld/mysqld.sock' })
> { Error: Access denied for user ''@'localhost' (using password: NO)
    at Packet.asError (/work/a/kitchen-server/node_modules/mysql2/lib/packets/packet.js:684:17)
    at ClientHandshake.execute (/work/a/kitchen-server/node_modules/mysql2/lib/commands/command.js:28:26)
    at Connection.handlePacket (/work/a/kitchen-server/node_modules/mysql2/lib/connection.js:455:32)
    at PacketParser.onPacket (/work/a/kitchen-server/node_modules/mysql2/lib/connection.js:73:18)
    at PacketParser.executeStart (/work/a/kitchen-server/node_modules/mysql2/lib/packet_parser.js:75:16)
  code: 'ER_ACCESS_DENIED_ERROR',
  errno: 1045,
  sqlState: '28000',
  sqlMessage:
   'Access denied for user \'\'@\'localhost\' (using password: NO)',
```
I can log into mysql just by typing mysql.  The mysqld has skip-networking option set.

**Comment by sidorares** [comment]
> I can log into mysql just by typing mysql. The mysqld has skip-networking option set.

When you do cli mysql, do you have same sattings? ( connect with database name and no user / password )?

**Comment by sidorares** [comment]
The error usually indicates there is no access grant for given user / database / auth plugin / source ip combination.

**Comment by marcino239** [comment]
I have networking disabled on mysqld, so communication is only via unix socket.  Query via python works ok though.

```
a@u1804-dev:~/work/server$ netstat -tlnp
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 127.0.0.53:53           0.0.0.0:*               LISTEN      -                   
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      -                   
tcp        0      0 127.0.0.1:6010          0.0.0.0:*               LISTEN      -                   
tcp6       0      0 :::22                   :::*                    LISTEN      -                   
tcp6       0      0 ::1:6010                :::*                    LISTEN      -            

a@u1804-dev:~/work/server$ mysql
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 15
Server version: 5.7.25-0ubuntu0.18.04.2 (Ubuntu)

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> 

```
python works ok:
```
a@u1804-dev:~/work/server$ python3
Python 3.6.7 (default, Oct 22 2018, 11:32:17) 
[GCC 8.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import MySQLdb
>>> db = MySQLdb.connect( unix_socket='/var/run/mysqld/mysqld.sock' )
>>> c = db.cursor()
>>> c.execute( 'select 1 as one' )
1
```

**Comment by marcino239** [comment]
Hi @sidorares, here's a way to replicate the issue.  Perhaps if you could point me out how to show debug info then I can create an integration test:

Dockerfile:
```
FROM mysql:5.7

RUN useradd -ms /bin/bash user \
    && mkdir -p /home/user
RUN apt update
RUN apt -y install wget xz-utils
RUN wget https://nodejs.org/dist/v10.15.3/node-v10.15.3-linux-x64.tar.xz -O /tmp/node.tar.xz
RUN tar xf /tmp/node.tar.xz -C /usr/local
RUN echo 'export PATH=$PATH:/usr/local/node-v10.15.3-linux-x64/bin' >> /home/user/.bashrc

WORKDIR /home/user
USER user

RUN echo '[client]\n\
user=root\n\
password="1234"\n' >> .my.cnf

RUN echo 'INSTALL PLUGIN auth_socket SONAME '"'"'auth_socket.so'"'"';\n\
create user '"'"'user'"'"'@'"'"'localhost'"'"' identified with auth_socket;\n\
create database kitchen;\n\
grant all privileges on kitchen.* to '"'"'user'"'"'@'"'"'localhost'"'"';\n\
flush privileges;\n' >> start_script.sql

RUN echo 'cd test\n\
npm install mysql2\n' >> node_setup.sh

RUN mkdir test && echo 'var d = require( "mysql2" )\n\
var c = d.createConnection({ database: "kitchen", socketPath: "/var/run/mysqld/mysqld.sock" })\n' >> test/script.js 

RUN echo 'mysql -u root < start_script.sql\n\
bash node_setup.sh\n\
cd test\n\
node script.js\n' >> runme.sh

USER mysql
```
then start docker:
```
docker run -ti -e MYSQL_ROOT_PASSWORD=1234 mtest
```
then start the runme.sh
```
docker exec -ti -u user heuristic_stonebraker bash
user@bd0994b6664a:~$ bash runme.sh 
...
Error: Access denied for user ''@'localhost' (using password: NO)
    at Packet.asError (/home/user/test/node_modules/mysql2/lib/packets/packet.js:684:17)
    at ClientHandshake.execute (/home/user/test/node_modules/mysql2/lib/commands/command.js:28:26)
    at Connection.handlePacket (/home/user/test/node_modules/mysql2/lib/connection.js:449:32)
```

Thanks!

**Comment by nblasgen** [comment]
Just since this isn't closed yet:

(1) Your MySQL2 example uses the database "kitchen"
(2) Your Python and CLI don't use Kitchen
(3) Your example SELECT statement in Python doesn't query any data

So all you've shown is that no username / password is acceptable to access no databases.  That's a possibility.  But are your permissions set so that the same user has read access to Kitchen?
