### ISSUE TITLE
named-placeholder exceptions not working in async context

### ISSUE THREAD

**Issue by tobloef** [sidorares/node-mysql2#986]
First if all, if this is is better suited for an issue at the named-placeholder repo, let me know and I'll change it.

**What happens:**
When the named-placeholders module throws an exception when executing a query inside a promise/async function, the error ignores any catch statements and crashes the entire application.

**When is happens:**
I'm not sure if this happens for all errors, but it happens in the folowing scenario, where I accidentally tried to use an empty array as query parameters.

```javascript
async function execute(query, params) {
    const formattedQuery = mysql.format(query, params);
    return await pool.execute(formattedQuery);
}

try {
    const query = "REPLACE INTO performance_data SET ?";
    const params = [];
    const response = await test(query, params);
} catch (error) {
    // Won't get called, app just crashes
    console.error("Error:", error);
}
```

The full stack trace is:

```
C:\Users\toblo\Code\performance-app\backend\node_modules\named-placeholders\index.js:95
      throw new Error('Named query contains placeholders, but parameters object is undefined');
      ^

Error: Named query contains placeholders, but parameters object is undefined
    at toArrayParams (C:\Users\toblo\Code\performance-app\backend\node_modules\named-placeholders\index.js:95:13)
    at compile (C:\Users\toblo\Code\performance-app\backend\node_modules\named-placeholders\index.js:144:12)
    at PoolConnection._resolveNamedPlaceholders (C:\Users\toblo\Code\performance-app\backend\node_modules\mysql2\lib\connection.js:518:17)
    at PoolConnection.execute (C:\Users\toblo\Code\performance-app\backend\node_modules\mysql2\lib\connection.js:599:10)
    at C:\Users\toblo\Code\performance-app\backend\node_modules\mysql2\lib\pool.js:163:31
    at C:\Users\toblo\Code\performance-app\backend\node_modules\mysql2\lib\pool.js:44:37
    at processTicksAndRejections (internal/process/task_queues.js:82:9)
```

**Comment by sidorares** [comment]
did you mean `const response = await execute(query, params);`?

We might need to add try/catch around placeholder resolution code so that error is routed correctly (or alternatively extra try/catch in promise wrapper)

**Comment by tobloef** [comment]
> Did you mean `const response = await execute(query, params);`?
 Yes, my bad. Edited the question.
