### ISSUE TITLE
TypeError: Class constructor LRUCache cannot be invoked without 'new'

### ISSUE THREAD

**Issue by okunishinishi** [sidorares/node-mysql2#987]
```
Setup failed. retry to setup after 3000ms ... TypeError: Class constructor LRUCache cannot be invoked without 'new'
    at new Connection (xxxxxxxxxxxxxxxxxx/db/node_modules/mysql2/lib/connection.js:53:24)
    at Object.module.exports.createConnection (xxxxxxxxxxxxxxxxxx/db/node_modules/mysql2/index.js:10:10)
```

**Comment by okunishinishi** [comment]
https://github.com/sidorares/node-mysql2/blob/master/lib/connection.js#L51

LRUCache is class now and needs `new`

**Comment by okunishinishi** [comment]
sorry, this was a problem of my local environment.

LRUCache  in lru-cache@5.x is class, but not in 4.x。some how my local mysql2 references lru-cache@5.x.
